RetailCoder.VBE/Config/ConfigurationLoader.cs, RetailCoder.VBE/Config/IConfigurationService.cs
Fixes #140. I think we're ready to release v1.1.
=> ConfigurationLoader automatically adds newly implemented Code Inspections to Config

RetailCoder.VBE/UI/ToDoItems/ToDoExplorerDockablePresenter.cs, RetailCoder.VBE/UI/ToDoItems/ToDoExplorerWindow.cs, RetailCoder.VBE/UI/UnitTesting/TestExplorerDockablePresenter.cs
Closes #279 as well as the other referenced issues.
=> UI Cleanup - Bug Fixes

RetailCoder.VBE/UI/UnitTesting/TestExplorerWindow.Designer.cs, RetailCoder.VBE/UI/UnitTesting/TestExplorerWindow.resx
=> UI Cleanup

RetailCoder.VBE/Inspections/ConstantNotUsedInspection.cs, RetailCoder.VBE/Inspections/ImplicitByRefParameterInspection.cs, RetailCoder.VBE/Inspections/ImplicitPublicMemberInspection.cs, RetailCoder.VBE/Inspections/ImplicitVariantReturnTypeInspection.cs, RetailCoder.VBE/Inspections/MultipleDeclarationsInspection.cs, RetailCoder.VBE/Inspections/ObsoleteCallStatementInspection.cs, RetailCoder.VBE/Inspections/ObsoleteLetStatementInspection.cs, RetailCoder.VBE/Inspections/ObsoleteTypeHintInspection.cs, RetailCoder.VBE/Inspections/OptionBaseInspection.cs, RetailCoder.VBE/Inspections/ParameterCanBeByValInspection.cs, RetailCoder.VBE/Inspections/ParameterNotUsedInspection.cs, RetailCoder.VBE/Inspections/ProcedureNotUsedInspection.cs, RetailCoder.VBE/Inspections/UnassignedVariableUsageInspection.cs, RetailCoder.VBE/Inspections/VariableNotAssignedInspection.cs, RetailCoder.VBE/Inspections/VariableNotUsedInspection.cs, RetailCoder.VBE/Inspections/VariableTypeNotDeclaredInspection.cs
Changed <i>ObsoleteX</i> inspections to `Suggestion` severity and all other inspections to `Warning` severity.
=> Change default Inspection severity to Warning/Suggestion; Closes #400

Installer Build Script.iss
Hi guys,
Here are some changes to the installer script based on comments from previous PR.
=> Inno installer script updates.

RetailCoder.VBE/UI/RubberduckUI.sv.resx
Added first version of a Swedish translation
=> Swedish translation

RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/FileBrowserDialogFactory.cs, RetailCoder.VBE/UI/FolderBrowser.cs, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx, RetailCoder.VBE/UI/SourceControl/App.cs, RetailCoder.VBE/UI/SourceControl/SourceControlPresenter.cs, RetailCoder.VBE/UI/SourceControl/SourceControlProviderFactory.cs, RubberduckTests/SourceControl/SCPresenterTests.cs
=> Sourcecontrol - Dependency Injection and expanded SCPresenter Tests

RetailCoder.VBE/UI/SourceControl/App.cs, RetailCoder.VBE/UI/SourceControl/SettingsControl.Designer.cs, RetailCoder.VBE/UI/SourceControl/SettingsPresenter.cs, RetailCoder.VBE/UI/SourceControl/SourceControlPresenter.cs, Rubberduck.SourceControl/DefaultSettings.cs, Rubberduck.SourceControl/Rubberduck.SourceControl.csproj, RubberduckTests/SourceControl/SCPresenterTests.cs, RubberduckTests/SourceControl/SettingsPresenterTests.cs
Settings Control View & Presenter work and are now wired into the Git Integration plug-in.
=> Sourcecontrol - Settings Control

Installer Build Script.iss
This should cover off issue #597.
=> Updated installer

RetailCoder.VBE/UI/SourceControl/BranchesControl.cs, RetailCoder.VBE/UI/SourceControl/ChangesControl.cs, RetailCoder.VBE/UI/SourceControl/CreateBranchForm.cs, RetailCoder.VBE/UI/SourceControl/MergeForm.cs, RetailCoder.VBE/UI/SourceControl/SettingsControl.cs, RetailCoder.VBE/UI/SourceControl/SettingsPresenter.cs, RetailCoder.VBE/UI/SourceControl/SourceControlPanel.cs, RetailCoder.VBE/UI/SourceControl/SourceControlProviderFactory.cs, RetailCoder.VBE/UI/SourceControl/UnSyncedCommitsControl.cs, RubberduckTests/AssertTests.cs, RubberduckTests/ConfigurationTests.cs, RubberduckTests/RubberduckTests.csproj, RubberduckTests/SourceControl/SCPresenterTests.cs, RubberduckTests/SourceControl/SettingsPresenterTests.cs, RubberduckTests/UnitTesting/EngineTests.cs
This started as a refactor of the SC Presenter tests and ended up with expanded test coverage of the UnitTesting namespace.
=> Test Coverage & Refactor

RetailCoder.VBE/UI/ToDoItems/ToDoExplorerDockablePresenter.cs, RetailCoder.VBE/UI/ToDoItems/ToDoExplorerWindow.cs, Rubberduck.Parsing/VBA/RubberduckParser.cs, RubberduckTests/Mocks/MockFactory.cs, RubberduckTests/RubberduckTests.csproj, RubberduckTests/SourceControl/SCPresenterTests.cs, RubberduckTests/TodoExplorerTests.cs, RubberduckTests/UnitTesting/AssertTests.cs, RubberduckTests/packages.config
Along with the tests, comes a MockFactory to make life a bit easier when dealing with anything intimately related to the RubberduckParser or DockablePresenter.
=> Moar Tests

RubberduckTests/Mocks/MockFactory.cs, RubberduckTests/Mocks/MockWindowsCollection.cs, RubberduckTests/TodoExplorerTests.cs
Also removed some dead code. 
@Hosch250 @retailcoder let me know if any of the doc comments aren't clear.
=> Added doc comments to the MockFactory closes #630.

RetailCoder.VBE/App.cs, RetailCoder.VBE/Inspections/Inspector.cs
See what you think of these changes.  I didn't quite get what I wanted to done, but thought that this might be worth keeping.
=> Tidied up App class instantiation of fields.

RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/SourceControl/App.cs, RetailCoder.VBE/UI/SourceControl/IUnSyncedCommitsView.cs, RetailCoder.VBE/UI/SourceControl/SourceControlPanel.cs, RetailCoder.VBE/UI/SourceControl/SourceControlPresenter.cs, RetailCoder.VBE/UI/SourceControl/UnSyncedCommitsControl.Designer.cs, RetailCoder.VBE/UI/SourceControl/UnSyncedCommitsControl.cs, RetailCoder.VBE/UI/SourceControl/UnsyncedCommitsPresenter.cs, RubberduckTests/RubberduckTests.csproj, RubberduckTests/SourceControl/SCPresenterTests.cs, RubberduckTests/SourceControl/UnsyncedCommitsPresenterTests.cs
Also fixed bug in SCPresenter Test
Closes #452 *kind of*. I think at this point I'd like to track individual issues as they arise.
=> Basic "Sunny day" remote functionality

RetailCoder.VBE/UI/SourceControl/BranchesPresenter.cs, RetailCoder.VBE/UI/SourceControl/ISourceControlView.cs, RetailCoder.VBE/UI/SourceControl/SourceControlPanel.Designer.cs, RetailCoder.VBE/UI/SourceControl/SourceControlPanel.cs, RetailCoder.VBE/UI/SourceControl/SourceControlPresenter.cs, RubberduckTests/SourceControl/BranchesPresenterTests.cs, RubberduckTests/SourceControl/ChangesPresenterTests.cs, RubberduckTests/SourceControl/SCPresenterTests.cs, RubberduckTests/SourceControl/UnsyncedCommitsPresenterTests.cs
=> added collapsable split panel for displaying error states

.gitignore, RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/SourceControl/App.cs, RetailCoder.VBE/UI/SourceControl/FailedActionControl.Designer.cs, RetailCoder.VBE/UI/SourceControl/FailedActionControl.cs, RetailCoder.VBE/UI/SourceControl/FailedActionControl.resx, RetailCoder.VBE/UI/SourceControl/ISourceControlView.cs, RetailCoder.VBE/UI/SourceControl/LoginControl.Designer.cs, RetailCoder.VBE/UI/SourceControl/LoginControl.cs, RetailCoder.VBE/UI/SourceControl/LoginControl.resx, RetailCoder.VBE/UI/SourceControl/SourceControlPanel.Designer.cs, RetailCoder.VBE/UI/SourceControl/SourceControlPanel.cs, RetailCoder.VBE/UI/SourceControl/SourceControlPresenter.cs, RetailCoder.VBE/UI/SourceControl/SourceControlProviderFactory.cs, RetailCoder.VBE/UI/SourceControl/UnSyncedCommitsControl.Designer.cs, RetailCoder.VBE/UI/SourceControl/UnsyncedCommitsPresenter.cs, Rubberduck.SourceControl/Commit.cs, Rubberduck.SourceControl/GitProvider.cs, RubberduckTests/SourceControl/SCPresenterTests.cs
Some UI issues remain and I'm sure there are still bugs to work out and refactoring to do, but it's real. 7 months + in the making, but it's real and it's here. :confetti_ball:
=> Sourcecontrol - Beta ready

Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs
fixes resolver issue with ambiguous identifiers in returning member procedure (function / property getter).
=> resolver fix

RetailCoder.VBE/UI/RubberduckUI.de.resx
Added a complete German translation
Signed-off-by: Vogel612 <Vogel612@gmx.de>
=> Added translation to German

README.md
from "retailcoder" to "rubberduck-vba" repo.
=> fix links in readme.md

RetailCoder.VBE/Navigation/RegexSearchReplace/IRegexSearchReplace.cs, RetailCoder.VBE/Navigation/RegexSearchReplace/IRegexSearchReplaceView.cs, RetailCoder.VBE/Navigation/RegexSearchReplace/RegexSearchReplace.cs, RetailCoder.VBE/Navigation/RegexSearchReplace/RegexSearchReplaceModel.cs, RetailCoder.VBE/Navigation/RegexSearchReplace/RegexSearchReplacePresenter.cs, RetailCoder.VBE/Navigation/RegexSearchReplace/RegexSearchReplaceScope.cs, RetailCoder.VBE/Navigation/RegexSearchReplace/RegexSearchResult.cs, RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/RegexSearchReplace/RegexSearchReplaceDialog.Designer.cs, RetailCoder.VBE/UI/RegexSearchReplace/RegexSearchReplaceDialog.cs, RetailCoder.VBE/UI/RegexSearchReplace/RegexSearchReplaceDialog.resx, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx, RubberduckTests/RegexSearchReplace/RegexSearchReplaceTests.cs, RubberduckTests/RubberduckTests.csproj
=> RegexSearchReplace

.gitignore, RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/RubberduckUI.resx, RetailCoder.VBE/UnitTesting/PermissiveAssertClass.cs, Rubberduck.VBEEditor/Extensions/CodeModuleExtensions.cs, Rubberduck.VBEEditor/VBEHost/PowerPointApp.cs, Rubberduck.VBEEditor/VBEInterfaces/RubberduckCodePane/CodePaneWrapper.cs, RubberduckTests/RubberduckTests.csproj
The changes to project files were done by monodevelop. As such I can roll them back at any time and subsequently ignore the changes. 
I'm very interested in having unit-tests run, since an error in overload-handling for `Application.Run` (only visible in `WordApp` and `AccessApp`) prevents me from testing this on my dev machine.
Comments on the type-promotions performed are very welcome. 
Sidenote: I changed some lines in other .cs files which were marked as compiler errors by mono. Additionally I added the key `Language_JP` to the english resx file.
=> [WIP] Permissive assert

RetailCoder.VBE/UI/RubberduckUI.de.resx
I added some fixed to the Greman UI resource file.
=> small adjustments and typo fix

RetailCoder.VBE/Inspections/UntypedFunctionUsageInspection.cs, RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx, Rubberduck.Parsing/Grammar/Tokens.cs, Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs
=> UntypedFunctionUsageInspection

Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs
such a simple fix, for such an annoying bug!
=> fixed resolver bug. fixes #727

RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/Command/FindSymbolCommand.cs, RetailCoder.VBE/UI/Command/Refactorings/RefactorRenameCommand.cs
=> Close #760

RetailCoder.VBE/UI/RubberduckUI.de.resx
I added the German Translation
=> #translation

RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/BusyIndicator.xaml, RetailCoder.VBE/UI/BusyIndicator.xaml.cs, RetailCoder.VBE/UI/CodeInspections/InspectionResultsControl.xaml, RetailCoder.VBE/UI/CodeInspections/InspectionResultsViewModel.cs, RetailCoder.VBE/UI/UnitTesting/TestExplorerControl.xaml, RetailCoder.VBE/UI/UnitTesting/TestExplorerViewModel.cs, RetailCoder.VBE/UnitTesting/TestEngine.cs
Code taken from http://fredgrass.blogspot.ca/2015/07/wpf-busy-indicator.html
=> BusyIndicator

RetailCoder.VBE/App.cs, RetailCoder.VBE/Inspections/Inspector.cs, RetailCoder.VBE/UI/CodeInspections/InspectionResultsControl.xaml, RetailCoder.VBE/UI/CodeInspections/InspectionResultsViewModel.cs, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/Settings/SettingsDialog.cs
...from the Code Inspections toolwindow :smile: 
Also disabled the treeview while inspections are running:
=> Disable this inspection

RetailCoder.VBE/UI/RubberduckUI.de.resx
I decided not to translate ActiveWorkbook and ActiveSheet.
=> #translation: added new German translations

RetailCoder.VBE/Extension.cs, RetailCoder.VBE/UI/Command/ShowSourceControlPanelCommand.cs, RetailCoder.VBE/UI/SourceControl/SourceControlBindings.cs
Step 1: Make it so we can open the window again. (Check!)
Step 2: Fix the buggy behavior we're been hearing about. (Next)
Step 3: ???
Step 4: Profit!
=> Re-wired Source Control plug-in into IoC container

RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.de.resx, RetailCoder.VBE/UI/RubberduckUI.fr.resx, RetailCoder.VBE/UI/RubberduckUI.ja.resx, RetailCoder.VBE/UI/RubberduckUI.resx, RetailCoder.VBE/UI/RubberduckUI.sv.resx, RetailCoder.VBE/UI/SourceControl/BranchesControl.cs, RetailCoder.VBE/UI/SourceControl/SettingsControl.Designer.cs
Worked on the german translation for the source control window
=> Translation

RetailCoder.VBE/Refactorings/IntroduceField/IntroduceFieldRefactoring.cs, RetailCoder.VBE/Refactorings/IntroduceParameter/IntroduceParameterRefactoring.cs, RetailCoder.VBE/Refactorings/MoveCloserToUsage/MoveCloserToUsageRefactoring.cs, RetailCoder.VBE/Root/CommandBarsModule.cs, RetailCoder.VBE/UI/Command/MenuItems/ParentMenus/RefactoringsParentMenu.cs, RetailCoder.VBE/UI/Command/MenuItems/RefactorMoveCloserToUsageCommandMenuItem.cs, RetailCoder.VBE/UI/Command/Refactorings/RefactorMoveCloserToUsageCommand.cs, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx
@retailcoder @Vogel612 @ckuhn203 And anyone else who is interested: Please review this when you have time.
=> Move closer to usage refactoring

RetailCoder.VBE/Common/DeclarationExtensions.cs, RetailCoder.VBE/Refactorings/ExtractInterface/ExtractInterfaceModel.cs, RetailCoder.VBE/Refactorings/ExtractInterface/ExtractInterfacePresenter.cs, RetailCoder.VBE/Refactorings/ExtractInterface/ExtractInterfacePresenterFactory.cs, RetailCoder.VBE/Refactorings/ExtractInterface/ExtractInterfaceRefactoring.cs, RetailCoder.VBE/Refactorings/ExtractInterface/IExtractInterfaceView.cs, RetailCoder.VBE/Refactorings/ExtractInterface/InterfaceMember.cs, RetailCoder.VBE/Refactorings/ImplementInterface/ImplementInterfaceRefactoring.cs, RetailCoder.VBE/Refactorings/ImplementInterface/Parameter.cs, RetailCoder.VBE/Root/CommandBarsModule.cs, RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/Command/MenuItems/ParentMenus/RefactoringsParentMenu.cs, RetailCoder.VBE/UI/Command/MenuItems/RefactorExtractInterfaceCommandMenuItem.cs, RetailCoder.VBE/UI/Command/MenuItems/RefactorImplementInterfaceCommandMenuItem.cs, RetailCoder.VBE/UI/Command/Refactorings/RefactorExtractInterfaceCommand.cs, RetailCoder.VBE/UI/Command/Refactorings/RefactorImplementInterfaceCommand.cs, RetailCoder.VBE/UI/Refactorings/ExtractInterfaceDialog.Designer.cs, RetailCoder.VBE/UI/Refactorings/ExtractInterfaceDialog.cs, RetailCoder.VBE/UI/Refactorings/ExtractInterfaceDialog.resx, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx
=> Extract interface

RetailCoder.VBE/Refactorings/ExtractMethod/ExtractMethodModel.cs
See http://chat.stackexchange.com/transcript/message/26595334#26595334
=> Change && to || to fix just-caught Extract Method bug.

RetailCoder.VBE/UI/RubberduckUI.de.resx, RetailCoder.VBE/UI/RubberduckUI.fr.resx, RetailCoder.VBE/UI/RubberduckUI.ja.resx, RetailCoder.VBE/UI/RubberduckUI.resx, RetailCoder.VBE/UI/RubberduckUI.sv.resx
Added missing keys to all Translated resx files, Added some corrections to the German translation
=> Translation cleanup

Rubberduck.Parsing/Nodes/CommentNode.cs, RubberduckTests/Inspections/ObsoleteCommentSyntaxInspectionTests.cs
=> Fix bug getting a comment's text and reinstate Obsolete Comment tests.

Rubberduck.VBEEditor/VBEHost/PublisherApp.cs
This must never have worked - Was it tested ;)
=> Fixes Publisher

RetailCoder.VBE/UI/CodeInspections/InspectionResultsViewModel.cs
SelectedItem is never of type IInspection. Might be remnants of an old version?
=> enable "apply quick fix" if one is available (fixes #1075)

RetailCoder.VBE/UI/Command/AddTestModuleCommand.cs, RetailCoder.VBE/UI/Command/MenuItems/ParserStateCommandBar.cs, Rubberduck.VBEEditor/Extensions/VbeExtensions.cs, Rubberduck.VBEEditor/Rubberduck.VBEditor.csproj
Fix Crashes when there aren't any projects open
=> Fix for #1072

RetailCoder.VBE/Settings/ConfigurationLoader.cs, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx, RetailCoder.VBE/UI/Settings/GeneralSettingsViewModel.cs, RetailCoder.VBE/UI/Settings/IndenterSettingsViewModel.cs, RetailCoder.VBE/UI/Settings/InspectionSettings.xaml, RetailCoder.VBE/UI/Settings/SettingsControlViewModel.cs, RubberduckTests/RubberduckTests.csproj, RubberduckTests/Settings/CodeInspectionSettingsTests.cs, RubberduckTests/Settings/GeneralSettingsTests.cs, RubberduckTests/Settings/IndenterSettingsTests.cs, RubberduckTests/Settings/SettingsControlTests.cs, RubberduckTests/Settings/TodoSettingsTests.cs, RubberduckTests/Settings/UnitTestSettingsTests.cs
Need to adjust the parent VM to DI the child views for other tests.
=> Settings code tests are basically done.

RetailCoder.VBE/Inspections/InspectionsUI.de.resx, RetailCoder.VBE/UI/RubberduckUI.de.resx
I fixed some typos I made before
=> translation: fixed some typos

RetailCoder.VBE/Common/RubberduckHooks.cs, RetailCoder.VBE/Common/WinAPI/User32.cs
See: http://stackoverflow.com/a/4316557/5895299.
Key hooks still throw exceptions though, not sure what the plans there are so I left them as they were.
=> fix 64bit host applications crash (fixes #1268)

Rubberduck.Parsing/Grammar/VBAParser.cs, Rubberduck.Parsing/Grammar/VBAParser.g4, RubberduckTests/Grammar/VBAParserTests.cs
The For Each statement doesn't seem to allow type hints at all, still waiting for feedback there. The other issues have been fixed.
=> fix grammar bugs (#1267)

RetailCoder.VBE/Common/DeclarationExtensions.cs, RetailCoder.VBE/Inspections/ProcedureNotUsedInspection.cs, RetailCoder.VBE/Refactorings/ExtractInterface/ExtractInterfaceModel.cs, RetailCoder.VBE/Refactorings/ImplementInterface/ImplementInterfaceRefactoring.cs, RetailCoder.VBE/Refactorings/IntroduceParameter/IntroduceParameterRefactoring.cs, RetailCoder.VBE/Refactorings/RemoveParameters/RemoveParametersModel.cs, RetailCoder.VBE/Refactorings/RemoveParameters/RemoveParametersRefactoring.cs, RetailCoder.VBE/Refactorings/Rename/RenameRefactoring.cs, RetailCoder.VBE/Refactorings/ReorderParameters/ReorderParametersRefactoring.cs, RetailCoder.VBE/UI/Command/Refactorings/FormDesignerRefactorRenameCommand.cs, RetailCoder.VBE/UI/Command/Refactorings/ProjectExplorerRefactorRenameCommand.cs, RetailCoder.VBE/UI/Command/ShowParserErrorsCommand.cs, Rubberduck.Parsing/Symbols/Declaration.cs, Rubberduck.Parsing/Symbols/DeclarationFinder.cs, Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs
=> replaced Project.Equals with ProjectName.Equals everywhere

RetailCoder.VBE/Common/Hotkeys/Hotkey.cs, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.de.resx, RetailCoder.VBE/UI/RubberduckUI.resx
I worked on the transaltion of the HotKey invalid exception messages
=> Translation 

RetailCoder.VBE/App.cs, Rubberduck.Parsing/IRubberduckParser.cs, Rubberduck.Parsing/Rubberduck.Parsing.csproj, Rubberduck.Parsing/VBA/ReferencePriorityMap.cs, Rubberduck.Parsing/VBA/RubberduckParser.cs, Rubberduck.Parsing/VBA/RubberduckParserState.cs, Rubberduck.VBEEditor/Extensions/VbProjectExtensions.cs
Also, added support for prioritized project references (for resolver edge-cases; @autoboosh you're up!)
Parser state reporting feels a bit jumpy, but everything seems to work.
=> Stabilized parser

RetailCoder.VBE/Settings/ConfigurationLoader.cs, RetailCoder.VBE/UI/Command/CodeExplorerCommand.cs
It's not implemented yet, it won't be in the v2.0a pre-release.
=> Disabled Code Explorer

RetailCoder.VBE/UI/Command/ShowParserErrorsCommand.cs, Rubberduck.Parsing/Symbols/SyntaxErrorException.cs, Rubberduck.Parsing/VBA/RubberduckParser.cs, Rubberduck.Parsing/VBA/RubberduckParserState.cs
Locking on _state for all changes, Fixed NRE in SyntaxErrorException ctor and in ShowParserErrorsCommand.
Also reverted `EvaluateParserState` to state from before #1265
=> ParserFix to correct ParserState behaviour

RetailCoder.VBE/Inspections/InspectionsUI.de.resx, RetailCoder.VBE/UI/RubberduckUI.de.resx
I included the comment from #1361
=> translation: added one new German phrase, fixed some typos

RetailCoder.VBE/Root/RubberduckModule.cs, RetailCoder.VBE/UI/Command/AddTestMethodCommand.cs, RetailCoder.VBE/UI/Command/AddTestMethodExpectedErrorCommand.cs, RetailCoder.VBE/UI/Command/AddTestModuleCommand.cs, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx, RetailCoder.VBE/UI/UnitTesting/TestExplorerViewModel.cs, RetailCoder.VBE/UnitTesting/NewTestMethodCommand.cs, RetailCoder.VBE/UnitTesting/NewUnitTestModuleCommand.cs
=> Close #1335 & #1065

RetailCoder.VBE/Inspections/InspectionsUI.de.resx, RetailCoder.VBE/Inspections/InspectionsUI.fr.resx, RetailCoder.VBE/Inspections/InspectionsUI.ja.resx, RetailCoder.VBE/Inspections/InspectionsUI.resx, RetailCoder.VBE/Inspections/InspectionsUI.sv.resx, RetailCoder.VBE/UI/RubberduckUI.de.resx, RetailCoder.VBE/UI/RubberduckUI.fr.resx, RetailCoder.VBE/UI/RubberduckUI.ja.resx, RetailCoder.VBE/UI/RubberduckUI.resx, RetailCoder.VBE/UI/RubberduckUI.sv.resx, Rubberduck.Parsing/ParsingText.de.resx, Rubberduck.Parsing/ParsingText.fr.resx, Rubberduck.Parsing/ParsingText.ja.resx, Rubberduck.Parsing/ParsingText.resx, Rubberduck.Parsing/ParsingText.sv.resx, Rubberduck.SourceControl/SourceControlText.de.resx, Rubberduck.SourceControl/SourceControlText.fr.resx, Rubberduck.SourceControl/SourceControlText.ja.resx, Rubberduck.SourceControl/SourceControlText.resx, Rubberduck.SourceControl/SourceControlText.sv.resx, Rubberduck.VBEEditor/VBEEditorText.de.resx, Rubberduck.VBEEditor/VBEEditorText.fr.resx, Rubberduck.VBEEditor/VBEEditorText.ja.resx, Rubberduck.VBEEditor/VBEEditorText.resx, Rubberduck.VBEEditor/VBEEditorText.sv.resx
or to be more correct, all "Resouce Bundles", where a German resource bundle is present.
=> Ran Localization-File normalization over all resx files

RetailCoder.VBE/UI/Command/Refactorings/RefactorImplementInterfaceCommand.cs
This introduces a couple problems.  The code works, but now we have a bunch of duplication in the `Refactoring()` method(s).  Should this potentially be moved to a (static?) class somewhere so it is only used once?
=> Working implementation of CanExecute for Implement Interface

RetailCoder.VBE/Inspections/InspectionsUI.de.resx, RetailCoder.VBE/Inspections/InspectionsUI.resx, RetailCoder.VBE/Inspections/UntypedFunctionUsageInspectionResult.cs
see #1405, this should've happened instead of the hack at #1408
=> Fixed the QuickFix menu localization

RetailCoder.VBE/UI/RubberduckUI.de.resx
changed on German phrase as discussed in the previous pull request
=> Translation: changed on German phrase

RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx, RetailCoder.VBE/UI/SourceControl/BranchesViewViewModel.cs, RetailCoder.VBE/UI/SourceControl/ChangesViewViewModel.cs, RetailCoder.VBE/UI/SourceControl/IControlViewModel.cs, RetailCoder.VBE/UI/SourceControl/NotificationType.cs, RetailCoder.VBE/UI/SourceControl/SettingsViewViewModel.cs, RetailCoder.VBE/UI/SourceControl/SourceControlView.xaml, RetailCoder.VBE/UI/SourceControl/SourceControlViewViewModel.cs, RetailCoder.VBE/UI/SourceControl/UnsyncedCommitsViewViewModel.cs, RubberduckTests/SourceControl/ChangesViewModelTests.cs
=> Source control tweaks

RetailCoder.VBE/Inspections/EmptyStringLiteralInspection.cs, RetailCoder.VBE/Inspections/IInspection.cs, RetailCoder.VBE/Inspections/IInspector.cs, RetailCoder.VBE/Inspections/IParseTreeInspection.cs, RetailCoder.VBE/Inspections/Inspector.cs, RetailCoder.VBE/Inspections/ObsoleteCallStatementInspection.cs, RetailCoder.VBE/Inspections/ObsoleteLetStatementInspection.cs, RetailCoder.VBE/Inspections/ProcedureCanBeWrittenAsFunctionInspection.cs, RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/CodeInspections/InspectionResultsViewModel.cs, Rubberduck.Parsing/VBA/RubberduckParser.cs, RubberduckTests/Inspections/EmptyStringLiteralInspectionTests.cs, RubberduckTests/Inspections/ObsoleteCallStatementInspectionTests.cs, RubberduckTests/Inspections/ObsoleteLetStatementInspectionTests.cs, RubberduckTests/Inspections/ProcedureShouldBeFunctionInspectionTests.cs, RubberduckTests/Refactoring/IntroduceFieldTests.cs, RubberduckTests/Refactoring/IntroduceParameterTests.cs, RubberduckTests/Refactoring/MoveCloserToUsageTests.cs
Small change to the tests that check against Exception Messages to not assume that the running machine's locale be set to English,
Fixes #1441
=> Minimal changes

RetailCoder.VBE/Refactorings/Rename/RenameRefactoring.cs, Rubberduck.Parsing/Binding/SimpleNameDefaultBinding.cs, Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs, RubberduckTests/Refactoring/RenameTests.cs
I know the tests are failing, but that is a resolver bug.
=> Close #1169

Rubberduck.Parsing/Grammar/VBAParser.cs, Rubberduck.Parsing/Grammar/VBAParser.g4, Rubberduck.Parsing/Grammar/VBAParserBaseListener.cs, Rubberduck.Parsing/Grammar/VBAParserBaseVisitor.cs, Rubberduck.Parsing/Grammar/VBAParserListener.cs, Rubberduck.Parsing/Grammar/VBAParserVisitor.cs, Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs, Rubberduck.Parsing/Symbols/IdentifierReferenceListener.cs, Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs, RubberduckTests/Grammar/ResolverTests.cs, RubberduckTests/Grammar/VBAParserTests.cs
All examples in #1457 and the linked stack overflow post should parse correctly now.
=> fix if-statements (fixes #1457)

RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerItemViewModel.cs
I know this isn't much, but...
=> Implement Comparer<T> rather than IComparer<T> as recommended by MS

RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/CodeExplorer/CodeExplorerControl.xaml, RetailCoder.VBE/UI/CodeInspections/InspectionResultsControl.xaml, RetailCoder.VBE/UI/CodeInspections/InspectionResultsViewModel.cs, RetailCoder.VBE/UI/Converters/BoolToHiddenVisibilityConverter.cs, RetailCoder.VBE/UI/Converters/InvertBoolValueConverter.cs, RetailCoder.VBE/UI/ToDoItems/ToDoExplorerControl.xaml, RetailCoder.VBE/UI/ToDoItems/ToDoExplorerViewModel.cs, RetailCoder.VBE/UI/UnitTesting/TestExplorerControl.xaml, RetailCoder.VBE/UI/UnitTesting/TestExplorerViewModel.cs
=> Close #1471

RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/CodeExplorer/CodeExplorerControl.xaml, RetailCoder.VBE/UI/CodeInspections/InspectionResultsControl.xaml, RetailCoder.VBE/UI/Controls/LinkButton.xaml, RetailCoder.VBE/UI/Controls/LinkButton.xaml.cs, RetailCoder.VBE/UI/SourceControl/SourceControlView.xaml
Also, allow it to wrap its text at word breaks
=> Define LinkButton style

Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs, RubberduckTests/Grammar/ResolverTests.cs
=> Only set IsAssignment flag on last reference in a chain

RetailCoder.VBE/Inspections/ObsoleteTypeHintInspection.cs, RetailCoder.VBE/Inspections/UntypedFunctionUsageInspectionResult.cs
=> Fix UntypedFunction inspection quick fix

RetailCoder.VBE/Inspections/ObjectVariableNotSetInspection.cs
=> Fix Object Variable Not Set false positives

RetailCoder.VBE/UI/Command/IndentCurrentProcedureCommand.cs
=> Implement CanExecute for Indent Procedure

RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerItemViewModel.cs, RubberduckTests/CodeExplorer/CodeExplorerTests.cs
=> Code Explorer #1513

RetailCoder.VBE/Inspections/UntypedFunctionUsageInspection.cs
=> Only report untyped function usage when the reference identifier does not have the $

RetailCoder.VBE/Extension.cs, RetailCoder.VBE/Refactorings/ExtractMethod/ExtractMethodPresenter.cs, RetailCoder.VBE/Settings/ToDoListSettings.cs, RetailCoder.VBE/UI/Settings/IndenterSettingsViewModel.cs, RetailCoder.VBE/UI/Settings/TodoSettingsViewModel.cs, Rubberduck.Parsing/Symbols/ReferencedDeclarationsCollector.cs, Rubberduck.SmartIndenter/AbsoluteCodeLine.cs, Rubberduck.SmartIndenter/AlignmentToken.cs, Rubberduck.SmartIndenter/IIndenter.cs, Rubberduck.SmartIndenter/Indenter.cs, Rubberduck.SmartIndenter/LogicalCodeLine.cs, Rubberduck.SmartIndenter/Rubberduck.SmartIndenter.csproj, RubberduckTests/RubberduckTests.csproj, RubberduckTests/Settings/TodoSettingsTests.cs, RubberduckTests/SmartIndenter/EndOfLineCommentTests.cs, RubberduckTests/SmartIndenter/LineContinuationTests.cs, RubberduckTests/SmartIndenter/MiscAndCornerCaseTests.cs, RubberduckTests/SmartIndenter/MultiSegmentLineTests.cs, RubberduckTests/SmartIndenter/SpecificSettingTests.cs
Closes [#1291](https://github.com/rubberduck-vba/Rubberduck/issues/1291), [#1286](https://github.com/rubberduck-vba/Rubberduck/issues/1286), and [#1606](https://github.com/rubberduck-vba/Rubberduck/issues/1606).
=> Indenter.BallOfMud = new MuchSmallerBallOfMud(); Changed Assembly load to host context.

RetailCoder.VBE/App.cs, Rubberduck.Parsing/VBA/RubberduckParser.cs, Rubberduck.Parsing/VBA/RubberduckParserState.cs
=> I hate the cache

RetailCoder.VBE/UI/Settings/SettingsControl.xaml, RetailCoder.VBE/UI/Settings/SettingsForm.cs, RetailCoder.VBE/UI/Settings/TodoSettings.xaml.cs, RetailCoder.VBE/UI/Settings/TodoSettingsViewModel.cs, RubberduckTests/Settings/TodoSettingsTests.cs
=> Prevent duplicate todo markers

RetailCoder.VBE/App.cs, RetailCoder.VBE/Common/ApplicationConstants.cs, RetailCoder.VBE/Common/IOperatingSystem.cs, RetailCoder.VBE/Common/LogLevelHelper.cs, RetailCoder.VBE/Common/WindowsOperatingSystem.cs, RetailCoder.VBE/Root/RubberduckModule.cs, RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/CodeInspections/InspectionResultsViewModel.cs, RetailCoder.VBE/UI/Command/SettingsCommand.cs, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.de.resx, RetailCoder.VBE/UI/RubberduckUI.ja.resx, RetailCoder.VBE/UI/RubberduckUI.resx, RetailCoder.VBE/UI/Settings/GeneralSettings.xaml, RetailCoder.VBE/UI/Settings/GeneralSettingsViewModel.cs, RetailCoder.VBE/UI/Settings/SettingsForm.cs, RetailCoder.VBE/UI/ToDoItems/ToDoExplorerViewModel.cs, RetailCoder.VBE/UI/UnitTesting/TestExplorerViewModel.cs, Rubberduck.Parsing/VBA/AttributeParser.cs, RubberduckTests/Settings/GeneralSettingsTests.cs, RubberduckTests/TodoExplorer/TodoExplorerTests.cs
1. Adds a "Show Log Folder" button to the general settings window
2. Disables/Sets log levels of all configured targets now
3. Fixes an attribute parser "duplicate key" bug
Let me know if the GUI is ugly or something has to be changed.
=> fix #1648 (Logger)

Rubberduck.Parsing/Symbols/ReferencedDeclarationsCollector.cs, Rubberduck.Parsing/VBA/RubberduckParser.cs
Not needed and need to rule out the state machine's interaction with OLE.
=> Convert GetDeclarationsForReference return to List<Declaration> 

RetailCoder.VBE/Inspections/FunctionReturnValueNotUsedInspectionResult.cs, RetailCoder.VBE/Inspections/IdentifierNotUsedInspectionResult.cs, RetailCoder.VBE/Inspections/ImplicitPublicMemberInspectionResult.cs, RetailCoder.VBE/Inspections/ImplicitVariantReturnTypeInspection.cs, RetailCoder.VBE/Inspections/ImplicitVariantReturnTypeInspectionResult.cs, RetailCoder.VBE/Inspections/InspectionResultBase.cs, RetailCoder.VBE/Inspections/NonReturningFunctionInspectionResult.cs, RetailCoder.VBE/UI/Inspections/InspectionImageSourceConverter.cs, RetailCoder.VBE/UI/Inspections/InspectionResultsControl.xaml, RetailCoder.VBE/UI/Inspections/InspectionSeverityImageSourceConverter.cs
=> Fix selections for several inspections

Rubberduck.Parsing/Rubberduck.Parsing.csproj, Rubberduck.Parsing/Symbols/ComParameter.cs, Rubberduck.Parsing/Symbols/ParameterDeclaration.cs, Rubberduck.Parsing/Symbols/ReferencedDeclarationsCollector.cs, RubberduckTests/Settings/IndenterSettingsTests.cs
=> Fix ByRef, ParamArray, and array parameter declarations.

Rubberduck.Parsing/VBA/RubberduckParserState.cs
All @Hosch250's work
I did get some problems trying to execute tests across both projects, but I suspect that's another issue.
=> Careful assignment of ProjectID - Avoids project collisions

RetailCoder.VBE/App.cs, RetailCoder.VBE/UI/Command/MenuItems/UiDispatcher.cs, RetailCoder.VBE/UI/SourceControl/BranchesView.xaml, RetailCoder.VBE/UI/SourceControl/BranchesViewViewModel.cs
Only allow merging to/from a local branch.  Disable hooks during merges.
=> Prevent (mostly) SC crashes on merge

RetailCoder.VBE/App.cs, RetailCoder.VBE/UI/SourceControl/SourceControlViewViewModel.cs
=> Prevent hooks from requesting a parse for each component when opening a repo

RetailCoder.VBE/App.cs, RetailCoder.VBE/UI/SourceControl/BranchesViewViewModel.cs
=> Disable sinks for each loaded component.

RetailCoder.VBE/UI/SourceControl/BranchesView.xaml, RetailCoder.VBE/UI/SourceControl/BranchesViewViewModel.cs, RubberduckTests/SourceControl/BranchesViewModelTests.cs
=> Give Published/Unpublished branch lists context menus

Rubberduck.Parsing/VBA/RubberduckParser.cs
=> Prevent resolve if state is parser error

RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx, RetailCoder.VBE/UI/SourceControl/BranchesViewViewModel.cs, RetailCoder.VBE/UI/SourceControl/ChangesViewViewModel.cs, RetailCoder.VBE/UI/SourceControl/SourceControlView.xaml, RetailCoder.VBE/UI/SourceControl/SourceControlViewViewModel.cs, Rubberduck.SourceControl/GitProvider.cs, Rubberduck.SourceControl/ISourceControlProvider.cs, Rubberduck.SourceControl/SourceControlProviderBase.cs, RubberduckTests/SourceControl/SourceControlViewModelTests.cs
To use:
Create local repo
Create remote repo--don't add any files
Add remote repo path and branch name
Login if necessary and try again (attempting an action without credentials cancels it)
Success (well, hopefully...)
=> Allow pushing to an empty remote repo

RetailCoder.VBE/App.cs, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx, RetailCoder.VBE/UI/SourceControl/ChangesViewViewModel.cs, RetailCoder.VBE/UI/SourceControl/SourceControlViewViewModel.cs, Rubberduck.SourceControl/GitProvider.cs, Rubberduck.SourceControl/ISourceControlProvider.cs, Rubberduck.SourceControl/SourceControlProviderBase.cs, RubberduckTests/SourceControl/SourceControlViewModelTests.cs, appveyor.yml
=> Notify when source files are modified externally

Rubberduck.Parsing/Grammar/VBAParser.cs, Rubberduck.Parsing/Grammar/VBAParser.g4, Rubberduck.Parsing/Grammar/VBAParserBaseListener.cs, Rubberduck.Parsing/Grammar/VBAParserBaseVisitor.cs, Rubberduck.Parsing/Grammar/VBAParserListener.cs, Rubberduck.Parsing/Grammar/VBAParserVisitor.cs, Rubberduck.Parsing/Rubberduck.Parsing.csproj, Rubberduck.Parsing/Symbols/CustomDeclarations.cs, Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs, Rubberduck.Parsing/Symbols/IdentifierReferenceListener.cs, Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs, Rubberduck.Parsing/VBA/RubberduckParser.cs, RubberduckTests/Grammar/VBAParserTests.cs
There's a new debugPrintStmt with an (optional) output list as parameter. It seems to work but requires the Debug.Print call to be treated specially...
=> Debug.Print fix

RetailCoder.VBE/Common/RubberduckHooks.cs
=> Removed WM_ACTIVATEAPP handler from RubberduckHooks

RetailCoder.VBE/UnitTesting/TestEngine.cs, Rubberduck.VBEEditor/QualifiedModuleName.cs, Rubberduck.VBEEditor/VBEHost/ExcelApp.cs, Rubberduck.VBEEditor/VBEHost/WordApp.cs
Word and Excel specific. Will need to check other hosts.
=> Various fixes to allow Unit Tests in multiple projects to run

Rubberduck.Parsing/VBA/ComponentParseTask.cs, Rubberduck.Parsing/VBA/RubberduckParser.cs, Rubberduck.Parsing/VBA/RubberduckParserState.cs
Reverts rubberduck-vba/Rubberduck#1810
=> Revert "Make parser/resolver run more asynchronously."

RetailCoder.VBE/UI/CodeExplorer/Commands/CodeExplorer_AddClassModuleCommand.cs, RetailCoder.VBE/UI/CodeExplorer/Commands/CodeExplorer_AddStdModuleCommand.cs, RetailCoder.VBE/UI/CodeExplorer/Commands/CodeExplorer_AddTestModuleCommand.cs, RetailCoder.VBE/UI/CodeExplorer/Commands/CodeExplorer_AddUserFormCommand.cs, RubberduckTests/CodeExplorer/CodeExplorerTests.cs
=> Enhance CE Add commands

RetailCoder.VBE/UI/SourceControl/SettingsView.xaml
Forgot to reset this for #104 :frowning:
=> Reset settings tab to TabItem from UserControl

RetailCoder.VBE/UI/Command/RunAllTestsCommand.cs, RetailCoder.VBE/UI/UnitTesting/TestExplorerControl.xaml, RetailCoder.VBE/UI/UnitTesting/TestExplorerModel.cs, RetailCoder.VBE/UnitTesting/NewTestMethodCommand.cs, RetailCoder.VBE/UnitTesting/TestEngine.cs, RetailCoder.VBE/UnitTesting/TestMethod.cs, RetailCoder.VBE/UnitTesting/UnitTestHelpers.cs
Close #1806 (Tests not displaying correct project name.)
Make tests run immediately after test list is updated for Run All.
Don't reparse if there are no changes for Run All.
=> Unit test tweaks

RetailCoder.VBE/UI/Command/IndentCurrentModuleCommand.cs, RetailCoder.VBE/UI/Command/IndentCurrentProcedureCommand.cs
=> Leave indenter menu items enabled on parser error

RetailCoder.VBE/Inspections/ImplicitActiveSheetReferenceInspection.cs, Rubberduck.Parsing/Symbols/ClassModuleDeclaration.cs, Rubberduck.Parsing/Symbols/DeclarationFinder.cs, Rubberduck.Parsing/Symbols/ReferencedDeclarationsCollector.cs, Rubberduck.Parsing/VBA/Attributes.cs
=> Fix Implicit Reference to Active Sheet Inspection

RetailCoder.VBE/UI/CodeExplorer/CodeExplorerControl.xaml, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx
Close #1759
@INOPIAE @retailcoder You might be interested in this
=> Tweak resx string

Rubberduck.VBEEditor/NativeMethods.cs
Reverts rubberduck-vba/Rubberduck#1848
=> Revert "Changed ActivateWindow to send WM_MDIACTIVATE instead of simulated mo…"

RetailCoder.VBE/API/ParserState.cs, RetailCoder.VBE/Common/DeclarationExtensions.cs, RetailCoder.VBE/Inspections/ParameterCanBeByValInspection.cs, RetailCoder.VBE/Inspections/ProcedureNotUsedInspection.cs, RetailCoder.VBE/Root/RubberduckModule.cs, Rubberduck.Parsing/Rubberduck.Parsing.csproj, Rubberduck.Parsing/Symbols/DebugDeclarations.cs, Rubberduck.Parsing/Symbols/FormEventDeclarations.cs, Rubberduck.Parsing/Symbols/ICustomDelarationLoader.cs, Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs, Rubberduck.Parsing/Symbols/ReferencedDeclarationsCollector.cs, Rubberduck.Parsing/VBA/RubberduckParser.cs, RubberduckTests/MockParser.cs
=> Hard-code a few missing declarations

RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerItemViewModel.cs, RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerProjectViewModel.cs, RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerViewModel.cs, RetailCoder.VBE/UI/CodeExplorer/CodeExplorerControl.xaml
=> Code Explorer Enhancements

RetailCoder.VBE/Inspections/ParameterCanBeByValInspection.cs, RetailCoder.VBE/Inspections/VariableTypeNotDeclaredInspectionResult.cs
=> Fix invalid cast

Rubberduck.Parsing/Grammar/VBAParser.cs, Rubberduck.Parsing/Grammar/VBAParser.g4, Rubberduck.Parsing/Grammar/VBAParserBaseListener.cs, Rubberduck.Parsing/Grammar/VBAParserBaseVisitor.cs, Rubberduck.Parsing/Grammar/VBAParserListener.cs, Rubberduck.Parsing/Grammar/VBAParserVisitor.cs, Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs, RubberduckTests/Grammar/ResolverTests.cs, RubberduckTests/Grammar/VBAParserTests.cs
=> Fix the line label rule(s) in the grammar.  Add tests.

RetailCoder.VBE/App.cs, RetailCoder.VBE/UI/Command/NavigateCommand.cs
=> Prevent crash when navigating to a missing code module

RetailCoder.VBE/UI/Command/RunAllTestsCommand.cs, RetailCoder.VBE/UI/UnitTesting/TestExplorerViewModel.cs
=> Disable test running commands in TE if any of the projects in the VBE is not in break mode

RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerViewModel.cs, RetailCoder.VBE/UI/Command/MenuItems/FindSymbolCommandMenuItem.cs, RetailCoder.VBE/UI/Command/MenuItems/RunAllTestsCommandMenuItem.cs, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx, Rubberduck.Parsing/IParseResultProvider.cs, Rubberduck.Parsing/VBA/ParserState.cs, Rubberduck.Parsing/VBA/RubberduckParser.cs, Rubberduck.Parsing/VBA/RubberduckParserState.cs
=> Make CE display an error node if resolver fails while resolving declarations

Rubberduck.Parsing/Symbols/Declaration.cs, Rubberduck.Parsing/VBA/RubberduckParser.cs
=> Fix ObjectVariableIsSelfAssigned

RetailCoder.VBE/App.cs, RetailCoder.VBE/Refactorings/Rename/RenameRefactoring.cs
@retailcoder Can you look at this?
=> Prevent crash when renaming the main project component

RetailCoder.VBE/UI/SourceControl/SourceControlViewViewModel.cs, Rubberduck.SourceControl/GitProvider.cs, Rubberduck.SourceControl/ISourceControlProvider.cs, Rubberduck.SourceControl/Interop/GitProvider.cs, Rubberduck.SourceControl/Interop/ISourceControlProvider.cs, Rubberduck.SourceControl/SourceControlProviderBase.cs, RubberduckTests/SourceControl/SourceControlViewModelTests.cs
=> Allow passing credentials into Clone to clone a private repository

RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerViewModel.cs, RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/CodeExplorer/CodeExplorerControl.xaml, RetailCoder.VBE/UI/CodeExplorer/Commands/CodeExplorer_OpenProjectPropertiesCommand.cs, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx
=> Put Open Project Properties in Code Explorer node context menu

Rubberduck.Parsing/Binding/TypeBindingContext.cs, Rubberduck.Parsing/VBA/RubberduckParser.cs
=> Add overload to Visit in resolver

RetailCoder.VBE/Inspections/UntypedFunctionUsageInspection.cs, RetailCoder.VBE/Inspections/UntypedFunctionUsageInspectionResult.cs, Rubberduck.Parsing/Rubberduck.Parsing.csproj, Rubberduck.Parsing/Symbols/AliasDeclarations.cs, Rubberduck.Parsing/Symbols/FormEventDeclarations.cs, Rubberduck.Parsing/VBA/RubberduckParser.cs
Close #1918
Close #1475 
Close #1405
=> Untyped functions are now resolved correctly

RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx, RetailCoder.VBE/UI/SourceControl/ChangesView.xaml, RetailCoder.VBE/UI/SourceControl/Converters/ChangeTypesToTextConverter.cs
=> Localize file status values

RetailCoder.VBE/Inspections/ObsoleteTypeHintInspectionResult.cs, RetailCoder.VBE/UI/Command/MenuItems/RubberduckCommandBar.cs, Rubberduck.Parsing/Symbols/Declaration.cs, Rubberduck.Parsing/Symbols/TypeAnnotationPass.cs
=> Display correct type for type hints

RetailCoder.VBE/UI/CodeExplorer/CodeExplorerControl.xaml, RetailCoder.VBE/UI/SourceControl/SourceControlView.xaml
=> Fix broken bindings

RetailCoder.VBE/Properties/AssemblyInfo.cs, Rubberduck.VBEEditor/Extensions/VBComponentsExtensions.cs
=> Adjust if statement to execute correctly

RetailCoder.VBE/Inspections/SelfAssignedDeclarationInspection.cs
=> Exclude variables with AsTypeDeclaration as UDT

RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerMemberViewModel.cs
=> Make signature stay on same line

Rubberduck.Parsing/VBA/RubberduckParser.cs, Rubberduck.Parsing/VBA/RubberduckParserState.cs
also "works around" an `ObjectDisposedException`
=> ProjectRenamed sink handler logging fix

RetailCoder.VBE/UI/CodeExplorer/CodeExplorerControl.xaml
=> Wrap items in bottom panel of CE

RetailCoder.VBE/API/ParserState.cs, RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerViewModel.cs, Rubberduck.Parsing/VBA/RubberduckParser.cs, Rubberduck.Parsing/VBA/RubberduckParserState.cs, RubberduckTests/MockParser.cs
Close #1985 
Remove syncing the PE with the CE because it was incomplete and caused strange side effects.
=> Fix 101 bugs in various parts of the project.

RetailCoder.VBE/Sinks.cs, Rubberduck.Parsing/VBA/RubberduckParserState.cs
=> Fix COM exception and incorrect sink handling

RetailCoder.VBE/UnitTesting/NewUnitTestModuleCommand.cs
=> Indent late-binding initialization in test module init method

RetailCoder.VBE/UI/FindSymbol/FindSymbolControl.xaml, RetailCoder.VBE/UI/FindSymbol/FindSymbolViewModel.cs
=> Find Symbol bug fixes

RetailCoder.VBE/UI/CodeExplorer/Commands/ImportCommand.cs, RubberduckTests/CodeExplorer/CodeExplorerTests.cs
=> Fix crash in CE import command

Rubberduck.Parsing/Symbols/ReferencedDeclarationsCollector.cs, Rubberduck.SourceControl/Properties/AssemblyInfo.cs
=> Load COM information more fully

RetailCoder.VBE/Common/DeclarationExtensions.cs, RetailCoder.VBE/Inspections/ParameterCanBeByValInspection.cs, RetailCoder.VBE/Inspections/ParameterCanBeByValInspectionResult.cs, Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs, RubberduckTests/Grammar/ResolverTests.cs, RubberduckTests/Inspections/ParameterCanBeByValInspectionTests.cs
=> Parameter Can By ByVal and resolving IsAssignment

RetailCoder.VBE/Inspections/UnassignedVariableUsageInspection.cs
=> Ignore Len and LenB in UnassignedVariableUsage inspection

RetailCoder.VBE/UI/Command/MenuItems/RubberduckCommandBar.cs
=> Clear selection display when we find a null active codepane

RetailCoder.VBE/Inspections/ParameterCanBeByValInspection.cs
=> Fix UDT bug in ParamCanBeByVal

RetailCoder.VBE/Inspections/VariableTypeNotDeclaredInspectionResult.cs, RubberduckTests/Inspections/VariableTypeNotDeclaredInspectionTests.cs
=> Fix search/replace bug in VariableTypeNotDeclared quick fix

RetailCoder.VBE/Refactorings/EncapsulateField/EncapsulateFieldRefactoring.cs, RetailCoder.VBE/Refactorings/ExtractInterface/ExtractInterfaceRefactoring.cs, RetailCoder.VBE/Refactorings/ImplementInterface/ImplementInterfaceRefactoring.cs, RetailCoder.VBE/Refactorings/IntroduceField/IntroduceFieldRefactoring.cs, RetailCoder.VBE/Refactorings/IntroduceParameter/IntroduceParameterRefactoring.cs, RetailCoder.VBE/Refactorings/MoveCloserToUsage/MoveCloserToUsageRefactoring.cs, RetailCoder.VBE/Refactorings/RemoveParameters/RemoveParametersRefactoring.cs, RetailCoder.VBE/Refactorings/Rename/RenameRefactoring.cs, RetailCoder.VBE/Refactorings/ReorderParameters/ReorderParametersRefactoring.cs
Close #2077
I really don't care for the way I did this in each and every refactoring.  Any ideas?
=> Set selection after finishing refactoring

RetailCoder.VBE/Inspections/InspectionsUI.Designer.cs, RetailCoder.VBE/Inspections/InspectionsUI.resx
=> Untyped Function Usage meta update

RetailCoder.VBE/Inspections/InspectionsUI.de.resx, RetailCoder.VBE/Inspections/InspectionsUI.resx, RetailCoder.VBE/UI/RubberduckUI.de.resx, RetailCoder.VBE/UI/RubberduckUI.fr.resx, RetailCoder.VBE/UI/RubberduckUI.ja.resx, RetailCoder.VBE/UI/RubberduckUI.sv.resx
=> I18n updates and corrections

RetailCoder.VBE/Inspections/EncapsulatePublicFieldInspection.cs, RetailCoder.VBE/Inspections/EncapsulatePublicFieldInspectionResult.cs, RetailCoder.VBE/Refactorings/EncapsulateField/EncapsulateFieldRefactoring.cs, RetailCoder.VBE/UI/Command/Refactorings/RefactorEncapsulateFieldCommand.cs, RetailCoder.VBE/UI/Refactorings/EncapsulateFieldDialog.cs, RubberduckTests/Inspections/EncapsulatePublicFieldInspectionTests.cs, RubberduckTests/Refactoring/EncapsulateFieldTests.cs
=> Encapsulate Field uses indenter

RetailCoder.VBE/Settings/HotkeySettings.cs, RetailCoder.VBE/Settings/RubberduckHotkey.cs, RetailCoder.VBE/UI/Command/Refactorings/RefactorEncapsulateFieldCommand.cs, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx, RubberduckTests/Settings/HotkeySettingsTests.cs
=> Encapsulate Field hotkey

RetailCoder.VBE/Inspections/EncapsulatePublicFieldInspectionResult.cs, RetailCoder.VBE/Refactorings/EncapsulateField/EncapsulateFieldPresenter.cs, RetailCoder.VBE/UI/Command/Refactorings/RefactorEncapsulateFieldCommand.cs, RetailCoder.VBE/UI/Refactorings/EncapsulateFieldDialog.cs
=> Better name validation for encapsulate field

Rubberduck.Parsing/VBA/RubberduckParserState.cs
=> Fix cache bug causing KeyNotFoundInDictionary exception

RetailCoder.VBE/Inspections/UseMeaningfulNameInspection.cs
Reverts rubberduck-vba/Rubberduck#2209
=> Revert "Crashes Excel.exe on start up of VBA Editor #2177"

Rubberduck.RegexAssistant/Atom.cs, Rubberduck.RegexAssistant/IRegularExpression.cs, Rubberduck.RegexAssistant/Pattern.cs, Rubberduck.RegexAssistant/Quantifier.cs, Rubberduck.RegexAssistant/Tests/CharacterClassTests.cs, Rubberduck.RegexAssistant/Tests/LiteralTests.cs, Rubberduck.RegexAssistant/Tests/RegularExpressionTests.cs
partially incorporated changes suggested in reviews, fixed prior design mistake
=> RegEx Assistant "tuneups"

RetailCoder.VBE/Common/DeclarationExtensions.cs, RubberduckTests/Inspections/ProcedureNotUsedInspectionTests.cs
Thunderframe added some tests!
Fixes #2245
=> Make test for Class event procedures a case-insensitive test

RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerViewModel.cs, RetailCoder.VBE/Root/RubberduckModule.cs, RetailCoder.VBE/UI/CodeExplorer/CodeExplorerDockablePresenter.cs, RetailCoder.VBE/UI/CodeExplorer/Commands/CommitCommand.cs, RetailCoder.VBE/UI/CodeExplorer/Commands/UndoCommand.cs, RetailCoder.VBE/UI/Command/CodeExplorerCommand.cs, RetailCoder.VBE/UI/Command/InspectionResultsCommand.cs, RetailCoder.VBE/UI/Command/MenuItems/CodeExplorerCommandMenuItem.cs, RetailCoder.VBE/UI/Command/ShowSourceControlPanelCommand.cs, RetailCoder.VBE/UI/Command/TestExplorerCommand.cs, RetailCoder.VBE/UI/Command/ToDoExplorerCommand.cs, RetailCoder.VBE/UI/DockableToolwindowPresenter.cs, RetailCoder.VBE/UI/IdentifierReferences/IdentifierReferencesListDockablePresenter.cs, RetailCoder.VBE/UI/IdentifierReferences/ImplementationsListDockablePresenter.cs, RetailCoder.VBE/UI/ParserErrors/ParserErrorsPresenter.cs, RetailCoder.VBE/UI/SourceControl/BranchesViewViewModel.cs, RetailCoder.VBE/UI/SourceControl/SourceControlDockablePresenter.cs, RetailCoder.VBE/UI/SourceControl/SourceControlProviderFactory.cs, Rubberduck.SourceControl/GitProvider.cs, Rubberduck.SourceControl/Interop/GitProvider.cs, Rubberduck.VBEEditor/NativeMethods.cs, Rubberduck.VBEEditor/SafeComWrappers/VBA/Controls.cs
Still doesn't unload/reload properly, but now GitProvider instances and SC view model properly get disposed.
=> Source Control component disposal

RubberduckTests/Mocks/MockProjectBuilder.cs
Fixes:
- Discovery_DiscoversAnnotatedTestMethodsInGivenTestModule
- Factory_NullSelectionReturnsNullPresenter
=> Fixing up some tests

Rubberduck.SmartIndenter/AbsoluteCodeLine.cs, RubberduckTests/SmartIndenter/MiscAndCornerCaseTests.cs
See http://chat.stackexchange.com/transcript/message/33575758#33575758
=> Fix variables starting w. Sub or Function in indenter.

Rubberduck.Parsing/VBA/StringExtensions.cs, RubberduckTests/StringExtensionsTests.cs
=> fix for HasComment and non-standard REM comments

Rubberduck.SourceControl/GitProvider.cs, Rubberduck.VBEEditor/SafeComWrappers/VB6/CodeModule.cs, Rubberduck.VBEEditor/SafeComWrappers/VBA/CodeModule.cs, Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponents.cs
=> fix in COM wrappers for CodeModule.Clear

RetailCoder.VBE/AppMenu.cs, RetailCoder.VBE/Extension.cs, RetailCoder.VBE/UI/Command/MenuItems/CommandBars/AppCommandBarBase.cs, RetailCoder.VBE/UI/Command/MenuItems/CommandBars/RubberduckCommandBar.cs, RetailCoder.VBE/UI/Command/MenuItems/ParentMenus/ParentMenuItemBase.cs, Rubberduck.VBEEditor/SafeComWrappers/Office.Core/CommandBarButton.cs, Rubberduck.VBEEditor/SafeComWrappers/Office.Core/CommandBars.cs, Rubberduck.VBEEditor/SafeComWrappers/VBA/VBE.cs
don't ask how. just.... don't ask.
=> ladies & gentlemen, we have a clean exit

Rubberduck.VBEEditor/SafeComWrappers/VB6/CodePane.cs, Rubberduck.VBEEditor/SafeComWrappers/VBA/CodePane.cs
This _might_ fix #2331, but I've never been able to replicate that one.
=> Fix ForceFocus in CodePane(s)

RetailCoder.VBE/UI/Settings/IndenterSettings.xaml, RetailCoder.VBE/UI/Settings/IndenterSettingsViewModel.cs, Rubberduck.SmartIndenter/AbsoluteCodeLine.cs, Rubberduck.SmartIndenter/IIndenterSettings.cs, Rubberduck.SmartIndenter/Indenter.cs, Rubberduck.SmartIndenter/IndenterSettings.cs, RubberduckTests/CodeExplorer/CodeExplorerTests.cs, RubberduckTests/Commands/IndentCommandTests.cs, RubberduckTests/Refactoring/EncapsulateFieldTests.cs, RubberduckTests/Settings/IndenterSettingsTests.cs, RubberduckTests/SmartIndenter/MiscAndCornerCaseTests.cs
Commit message isn't strictly accurate - you need to undo _twice_ in the VBE - once to undo the insert, then again to undo the delete.
=> Remove Enable undo from Indenter settings, extend line number support.

RetailCoder.VBE/Inspections/InspectionsUI.Designer.cs, RetailCoder.VBE/Inspections/InspectionsUI.de.resx, RetailCoder.VBE/Inspections/InspectionsUI.fr.resx, RetailCoder.VBE/Inspections/InspectionsUI.resx
Wording wrongly assumed that the variable was assigned.
=> fixed "Variable not used" wording

RetailCoder.VBE/App.cs, RetailCoder.VBE/NLog.dll.nlog, Rubberduck.VBEEditor/Extensions/IDEExtensions.cs, Rubberduck.VBEEditor/Native/WinEvents.cs, Rubberduck.VBEEditor/Rubberduck.VBEditor.csproj, Rubberduck.VBEEditor/SafeComWrappers/VBA/VBE.cs
=> Add build number to logging, use `Application` to find host app, stubs event hooks.

Rubberduck.VBEEditor/Application/ExcelApp.cs, Rubberduck.VBEEditor/QualifiedModuleName.cs
=> Fix project names with spaces and dashes (and single quotes in Excel tests).

RetailCoder.VBE/API/ParserState.cs, RetailCoder.VBE/Inspections/QuickFixes/IgnoreOnceQuickFix.cs
=> Fix comment placement for IgnoreOnceQuickFix, Fix API initialization.

RetailCoder.VBE/Common/DeclarationExtensions.cs, RetailCoder.VBE/Inspections/ProcedureNotUsedInspection.cs
=> Performance enhancement for FindBuiltInEventHandlers, only handle auto_* events in Excel.

Rubberduck.Parsing/Symbols/DeclarationLoaders/FormEventDeclarations.cs, Rubberduck.Parsing/Symbols/ParameterDeclaration.cs
See http://chat.stackexchange.com/transcript/message/35073489#35073489
=> Fix IsImplicitByRef flags for built-in parameters.

Rubberduck.VBEEditor/SafeComWrappers/Office.Core/Abstract/IControl.cs
=> Get coclass name from IControl instead of interface name. Closes #2592

Rubberduck.Parsing/Symbols/DeclarationFinder.cs
More to be done here, but it's a start.
=> Add more thread safety to DeclarationFinder.

RetailCoder.VBE/Inspections/Abstract/IInspectionResult.cs, RetailCoder.VBE/Inspections/Abstract/InspectionResultBase.cs, RetailCoder.VBE/UI/Inspections/InspectionResultsViewModel.cs, Rubberduck.Parsing/Symbols/ProjectDeclaration.cs, Rubberduck.SmartIndenter/AbsoluteCodeLine.cs, Rubberduck.SmartIndenter/LogicalCodeLine.cs, Rubberduck.SmartIndenter/Rubberduck.SmartIndenter.csproj, Rubberduck.SmartIndenter/StringLiteralAndBracketEscaper.cs, Rubberduck.VBEEditor/QualifiedModuleName.cs, Rubberduck.VBEEditor/SafeComWrappers/Abstract/IVBComponent.cs, Rubberduck.VBEEditor/SafeComWrappers/Abstract/IVBProject.cs, Rubberduck.VBEEditor/SafeComWrappers/VB6/VBComponent.cs, Rubberduck.VBEEditor/SafeComWrappers/VB6/VBProject.cs, Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponent.cs, Rubberduck.VBEEditor/SafeComWrappers/VBA/VBProject.cs, RubberduckTests/SmartIndenter/MiscAndCornerCaseTests.cs
Don't know HTH #2604 slipped by so long - explains the state of indentation in the SO [vba] tag...
=> Fix clipboard text for inspections, Fix string literals in Indenter function aligner - Closes #2604

Rubberduck.Parsing/VBA/ParseCoordinator.cs
I changed the concurrency design for resolving the references so that cancellation will now stop the creation of further tasks. 
Moreover, I made setting the states concurrent and removed superfluous calls setting the state. (ResolvingReferences was set twice for every module.) This resulted in a significant performance improvement.
Furthermore, we now only add undeclared variables once and not every time a resolver task finishes.
Finally, made the overall state evaluate only after everything finished. Previously, the overall state could switch to ready before the last undeclared variables had been added.
=> Rework ParseCoordinator Part 3

Rubberduck.Parsing/VBA/ParseCoordinator.cs
Refactoring of SyncCOMReferences in ParseCoordinator.
=> Reworking the ParseCoordinator Part 5

RetailCoder.VBE/Inspections/ObsoleteGlobalInspection.cs, RetailCoder.VBE/Inspections/Results/ObsoleteGlobalInspectionResult.cs, RetailCoder.VBE/UI/SourceControl/SourceControlViewViewModel.cs, Rubberduck.Parsing/VBA/RubberduckParserState.cs, Rubberduck.VBEEditor/SafeComWrappers/Abstract/IVBComponents.cs, Rubberduck.VBEEditor/SafeComWrappers/Abstract/IVBProjects.cs, Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponents.cs, Rubberduck.VBEEditor/SafeComWrappers/VBA/VBProjects.cs
This may introduce an NRE on close - I'll take a look in the morning.
=> Stop colossal memory leak of event delegates.

RetailCoder.VBE/Refactorings/EncapsulateField/EncapsulateFieldPresenter.cs, RetailCoder.VBE/Refactorings/EncapsulateField/EncapsulateFieldRefactoring.cs, RetailCoder.VBE/Refactorings/EncapsulateField/IEncapsulateFieldDialog.cs, RetailCoder.VBE/Refactorings/EncapsulateField/PropertyGenerator.cs, RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/Refactorings/EncapsulateFieldDialog.cs, Rubberduck.VBEEditor/SafeComWrappers/VBA/VBProjects.cs, RubberduckTests/Refactoring/EncapsulateFieldTests.cs
Note - this disables a bunch of tests that _should_ have been failing, but were only testing mocked behavior.  This will need another round of refactoring before it's worthwhile to re-enable\re-write the tests.
=> EncapsulateFieldDialog fixes, refactor.

RetailCoder.VBE/App.cs, RetailCoder.VBE/AppMenu.cs, RetailCoder.VBE/Root/RubberduckModule.cs, RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/Command/MenuItems/CommandBars/AppCommandBarBase.cs, RetailCoder.VBE/UI/Command/MenuItems/CommandBars/IContextFormatter.cs, RetailCoder.VBE/UI/Command/MenuItems/CommandBars/RubberduckCommandBar.cs, RetailCoder.VBE/UI/SelectionChangeService.cs, Rubberduck.Parsing/VBA/RubberduckParserState.cs, Rubberduck.VBEEditor/SafeComWrappers/VBA/VBProjects.cs
=> Delegated selection event handling responsibilities out of App.cs.  

RubberduckTests/RubberduckTests.csproj, RubberduckTests/Symbols/DeclarationFinderTests.cs, RubberduckTests/Symbols/DeclarationFinderTests_VbaBlocks.cs
Addresses comment for PR #2872 to organize test VBA code in separate static class.
=> #2872 Tests refactoring 

RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerViewModel.cs, RetailCoder.VBE/UI/Command/RunAllTestsCommand.cs, RetailCoder.VBE/UI/Inspections/InspectionResultsViewModel.cs, RetailCoder.VBE/UI/SourceControl/SourceControlViewViewModel.cs, RetailCoder.VBE/UI/ToDoItems/ToDoExplorerViewModel.cs, RetailCoder.VBE/UI/UnitTesting/TestExplorerModel.cs, RetailCoder.VBE/UI/UnitTesting/TestExplorerViewModel.cs, RetailCoder.VBE/UnitTesting/UnitTestUtils.cs, Rubberduck.Parsing/VBA/RubberduckParserState.cs, RubberduckTests/SourceControl/SourceControlViewModelTests.cs
=> closes #1185, fixes "stuck" busy state in toolwindows

RetailCoder.VBE/Common/DeclarationExtensions.cs, RetailCoder.VBE/Root/RubberduckModule.cs, RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/Command/MenuItems/CommandBars/ContextDescriptionLabelMenuItem.cs, RetailCoder.VBE/UI/Command/MenuItems/CommandBars/ReferenceCounterLabelMenuItem.cs, RetailCoder.VBE/UI/Command/MenuItems/CommandBars/RubberduckCommandBar.cs, RetailCoder.VBE/UnitTesting/IAssert.cs, RetailCoder.VBE/UnitTesting/IFake.cs, RetailCoder.VBE/UnitTesting/IVerify.cs, Rubberduck.Parsing/ComReflection/ReferencedDeclarationsCollector.cs, Rubberduck.Parsing/Symbols/Declaration.cs
also collects docstrings from COM collector, and displays `VB_Description` attributes in RD commandbar.
=> add description attributes to unit testing API

Rubberduck.Inspections/QuickFixes/RemoveEmptyIfBlockQuickFix.cs
Only allow fixing one at a time
=> Tweak fix for #874

RetailCoder.VBE/UI/Refactorings/Rename/RenameView.xaml
Set IsDefault to "OK" button and IsCancel to "Cancel" button.
Closes #3087
=> Rename dialog button keyboard shortcuts

RetailCoder.VBE/Settings/CodeInspectionConfigProvider.cs, Rubberduck.Inspections/Concrete/LineLabelNotUsedInspection.cs, Rubberduck.Inspections/QuickFixes/RemoveUnusedDeclarationQuickFix.cs, Rubberduck.Inspections/Rubberduck.Inspections.csproj, Rubberduck.Parsing/Inspections/Resources/InspectionsUI.resx, Rubberduck.Parsing/Inspections/Resources/InspectionsUI1.Designer.cs, RubberduckTests/Inspections/GeneralInspectionTests.cs, RubberduckTests/Inspections/LineLabelNotUsedInspectionTests.cs, RubberduckTests/RubberduckTests.csproj
Simple inspection to see when a line label is not used.
I think I have everything squared away as it looks good to me.  However, everyone please take a good look at this.  Still very much a Noob. :)
Big thanks to @retailcoder for the help via chat!
Closes #2027.
=> Implements LineLabelNotUsedInspection

RetailCoder.VBE/Settings/CodeInspectionConfigProvider.cs, RetailCoder.VBE/Settings/CodeInspectionSettings.cs, RetailCoder.VBE/UI/Inspections/InspectionDescriptionConverter.cs, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.de.resx, RetailCoder.VBE/UI/RubberduckUI.resx, RetailCoder.VBE/UI/Settings/Converters/CodeInspectionSeverityEnumToTextConverter.cs, RetailCoder.VBE/UI/Settings/InspectionSettings.xaml.cs, RetailCoder.VBE/UI/Settings/InspectionSettingsViewModel.cs, Rubberduck.Inspections/Abstract/InspectionBase.cs, Rubberduck.Inspections/Abstract/InspectionResultBase.cs, Rubberduck.Parsing/Inspections/Resources/InspectionsUI.de.resx, Rubberduck.Parsing/Inspections/Resources/InspectionsUI.resx, Rubberduck.Parsing/Inspections/Resources/InspectionsUI1.Designer.cs, RubberduckTests/Inspections/UseMeaningfulNameInspectionTests.cs
current WIP for CodeInspectionSetting cleanup. When this is finished, it'll fix #3021 (and also include some German resources)
=> Inspection setting discovery

Rubberduck.Parsing/VBA/ParseCoordinator.cs
We are reresolving all modules that reference modules or references that got removed. This is necessary because the same identifers might now resolve to different declarations.
So far, a cancellation of a parsing run in which modules got removed caused us to loose the information that the modules referencing the removed modules had to be reresolved. Moreover, a parser error in some other module changed in the meantime would have caused the same loss.
With the changes in this PR this problem gets removed by setting the module state of the modules to be resolved to something else than `Ready` prior to the first possibility of cancellation after removing the modules. (Note that no there is no cancellation in the `COMSynchronizationRunner` after unloading references.) This has the effect that …
=> Improving Cancellation Safety

Rubberduck.Parsing/Grammar/PartialExtensions/VBAParserPartialExtensions.cs, Rubberduck.Parsing/Symbols/Identifier.cs, RubberduckTests/Refactoring/RenameTests.cs
Closes #3218.  Fixes RenameRefactoring of Enumerations and EnumerationMembers as well.
=> RenameRefactoring of Labels and Enums

Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs, Rubberduck.Parsing/Symbols/TypeAnnotationPass.cs
Fixes type annotation pass bug introduced with lazy-coded, unreviewed, rogue, late-night PR.
*slaps own wrist*
=> Type annotation hotfix

Rubberduck.Parsing/Rewriter/RewriterInfo/VariableRewriterInfoFinder.cs, RubberduckTests/QuickFixes/RemoveUnusedDeclarationQuickFixTests.cs
Additionally includes some unit tests for minor edge cases
Fixes #3288
=> Use target context for removal of a single declaration

RetailCoder.VBE/UI/Command/FindSymbolCommand.cs, RetailCoder.VBE/UI/FindSymbol/FindSymbolControl.xaml, RetailCoder.VBE/UI/FindSymbol/FindSymbolControl.xaml.cs, RetailCoder.VBE/UI/FindSymbol/FindSymbolDialog.cs, RetailCoder.VBE/UI/FindSymbol/FindSymbolViewModel.cs
=> FindSymbol focus on searchComboBox

RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerComponentViewModel.cs
=> Source Control Breaks Parsing

Rubberduck.Inspections/Concrete/EmptyConditionBlockInspection.cs, RubberduckTests/Inspections/EmptyConditionBlockInspectionTests.cs, RubberduckTests/QuickFixes/RemoveEmptyConditionBlockQuickFixTests.cs
Ninject issue from constructor injection taken care of.
=> EmptyConditionBlock

RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerViewModel.cs, RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/CodeExplorer/CodeExplorerControl.xaml, RetailCoder.VBE/UI/CodeExplorer/Commands/AddTestModuleWithStubsCommand.cs, RetailCoder.VBE/UI/Command/AddTestModuleCommand.cs, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx, RubberduckTests/CodeExplorer/CodeExplorerTests.cs, RubberduckTests/Commands/UnitTestCommandTests.cs
=> Implemented generating test stub for each public sub, function or property

RetailCoder.VBE/Settings/CodeInspectionSettings.cs, Rubberduck.Inspections/Concrete/AssignedByValParameterInspection.cs, Rubberduck.Inspections/Inspector.cs
This PR contains some changes to fix part of the problem with getting the settings for inspections.
=> Minor changes to settings handling for inspections.

Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponents.cs
=> Excel crashes with RubberDuck when closing an Excel workbook

RetailCoder.VBE/UI/Command/MenuItems/FormDesignerRefactorRenameCommandMenuItem.cs, RetailCoder.VBE/UI/Command/MenuItems/ParentMenus/ParentMenuItemBase.cs
=> 2.1.02314: Rubberduck not visible in menu

RetailCoder.VBE/Root/RubberduckModule.cs, RetailCoder.VBE/Rubberduck.csproj, RetailCoder.VBE/UI/Command/MenuItems/ParentMenus/RubberduckParentMenu.cs, RetailCoder.VBE/UI/Command/MenuItems/RefreshCommandMenuItem.cs, RetailCoder.VBE/UI/Command/RefreshCommand .cs, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx
=> Refresh command in RD menu

RetailCoder.VBE/UI/RubberduckUI.de.resx, RetailCoder.VBE/UI/RubberduckUI.fr.resx, RetailCoder.VBE/UI/RubberduckUI.resx, Rubberduck.Parsing/Inspections/Resources/InspectionsUI.de.resx, Rubberduck.Parsing/Inspections/Resources/InspectionsUI.fr.resx, Rubberduck.Parsing/Inspections/Resources/InspectionsUI.resx
Mise à jour des traductions en Français.
=> Petit Canard

appveyor.yml
includes a last-minute bugfix!
=> v2.1.0 ...take 3

RetailCoder.VBE/UnitTesting/Verifier.cs
=> Fix Verifier Logic

RetailCoder.VBE/UnitTesting/FakeBase.cs
=> Clear return configurations between tests

Rubberduck.Parsing/Inspections/Resources/InspectionsUI.de.resx
at least one Inspection, EmptyCaseBlockInspectionMeta
=> added new German translation

RetailCoder.VBE/UI/Settings/InspectionSettings.xaml
Now gives enough time to read long meta descriptions.
=> Fixes Issue #3487

RetailCoder.VBE/UI/CodeExplorer/Commands/AddComponentCommand.cs, Rubberduck.VBEEditor/SafeComWrappers/Abstract/ICodeModule.cs
=> Folder annotation scope

Rubberduck.Parsing/Binding/IndexDefaultBinding.cs, RubberduckTests/Grammar/ResolverTests.cs
=> add test and symptomatic fix for jagged arrray resolution

RetailCoder.VBE/UI/About/AboutControlViewModel.cs, RetailCoder.VBE/UI/CodeExplorer/CodeExplorerControl.xaml.cs, RetailCoder.VBE/UI/CodeExplorer/Commands/AddComponentCommand.cs, RetailCoder.VBE/UI/Controls/BindableSelectedItemBehavior.cs, RetailCoder.VBE/UI/Controls/BindableTextEditor.cs, RetailCoder.VBE/UI/Controls/DeclarationTypeToStringConverter.cs, RetailCoder.VBE/UI/Controls/EmptyUIRefresh.xaml.cs, RetailCoder.VBE/UI/Controls/GroupingGrid.xaml.cs, RetailCoder.VBE/UI/Controls/MenuItemGroup.cs, RetailCoder.VBE/UI/Controls/NumberPicker.xaml.cs, RetailCoder.VBE/UI/Controls/SearchResultItem.cs, RetailCoder.VBE/UI/Controls/SearchResultPresenterInstanceManager.cs, RetailCoder.VBE/UI/Controls/SearchResultsViewModel.cs, RetailCoder.VBE/UI/Controls/SearchResultsWindowViewModel.cs, RetailCoder.VBE/UI/FindSymbol/FindSymbolControl.xaml.cs, RetailCoder.VBE/UI/Inspections/InspectionImageSourceConverter.cs, RetailCoder.VBE/UI/ToDoItems/ToDoExplorerControl.xaml.cs, RetailCoder.VBE/UI/ToDoItems/ToDoExplorerViewModel.cs, RetailCoder.VBE/UI/UnitTesting/TestExplorerControl.xaml, RetailCoder.VBE/UI/UnitTesting/TestExplorerControl.xaml.cs, RetailCoder.VBE/UI/UnitTesting/TestExplorerModel.cs, RetailCoder.VBE/UI/UnitTesting/TestExplorerViewModel.cs, RetailCoder.VBE/UI/UnitTesting/TestOutcomeImageSourceConverter.cs, RetailCoder.VBE/UI/UnitTesting/TestResultToOutcomeTextConverter.cs, RetailCoder.VBE/UI/ViewModelBase.cs, RetailCoder.VBE/UnitTesting/TestMethod.cs, RetailCoder.VBE/UnitTesting/TestResult.cs
Closes #2946. F5 tested and UnitTested.
There appears to be some nasty hidden in here. I'll dig through to understand what's causing it. #3545  opened to bring attention to it.
=> Fix blue background.

RetailCoder.VBE/UI/About/AboutControl.xaml, RetailCoder.VBE/UI/About/AboutControlViewModel.cs, RetailCoder.VBE/UI/RubberduckUI.Designer.cs, RetailCoder.VBE/UI/RubberduckUI.resx
=> Dynamic current year on about window

Rubberduck.RegexAssistant/Atom.cs, Rubberduck.RegexAssistant/IRegularExpression.cs, Rubberduck.RegexAssistant/Pattern.cs, Rubberduck.RegexAssistant/Quantifier.cs, Rubberduck.RegexAssistant/Tests/CharacterClassTests.cs, Rubberduck.RegexAssistant/Tests/LiteralTests.cs, Rubberduck.RegexAssistant/Tests/QuantifierTests.cs, Rubberduck.RegexAssistant/Tests/RegularExpressionTests.cs
=> Rubberduck.regex assistant c#6&7 update

Rubberduck.Parsing/Inspections/Resources/InspectionsUI.de.resx, Rubberduck.Parsing/Inspections/Resources/InspectionsUI.fr.resx, Rubberduck.Parsing/Inspections/Resources/InspectionsUI.resx
Added translations in Rubberduck.Parsing/Inspections/Resources/InspectionsUI.de.resx + fixed some wrong   english descriptions (name tag didn't match text) in  Rubberduck.Parsing/Inspections/Resources/InspectionsUI.resx
=> German translation Inspections 

RetailCoder.VBE/UI/UnitTesting/TestExplorerControl.xaml, RetailCoder.VBE/UI/UnitTesting/TestExplorerControl.xaml.cs, RetailCoder.VBE/UI/UnitTesting/TestExplorerViewModel.cs
=> Issue3646 scroll wheel in tests panel

appveyor.yml
Also reinstates the ignoring of *.yml files for changes
=> fix AV passing with failing tests

RubberduckTests/Inspections/EmptyIfBlockInspectionTests.cs
This somehow got through @Duga.
=> Correct inspectionType

Rubberduck.Parsing/ComReflection/ComEnumerationMember.cs, Rubberduck.Parsing/ComReflection/ComMember.cs, Rubberduck.Parsing/ComReflection/ComModule.cs, Rubberduck.Parsing/ComReflection/ComProject.cs, Rubberduck.Parsing/ComReflection/ComStruct.cs
My first official PR :)
Very minor... just seeing how all this git stuff works.
=> Minor corrections to uses of ITypeLib/ITypeInfo

Rubberduck.Parsing/Grammar/VBAParser.g4, RubberduckTests/Grammar/VBAParserTests.cs
=> Fix SLL mode for array declarations

Rubberduck.VBEEditor/Application/PowerPointApp.cs, Rubberduck.VBEEditor/SafeComWrappers/VBA/VBE.cs
This PR fixes the crash on load in PowerPoint.
Moreover, it fixes an NRE encountered when running unit tests in PowerPoint.
=> Fix power point app

README.md
I also added a link to the installation instructions, and a note that "Getting started" is a usage guide.  I think that will help new users find what they are looking for more quickly.
=> Added download links for stable, dev.  Fixes #3802

License.rtf
=> Updated License.rtf

README.md
Add link to the thanks.md from the readme.md (part of #3803)
=> Add link to thanks.md (user testimonials)

Rubberduck.Main/Root/RubberduckIoCInstaller.cs
Thanks to MDoerner for finding the bug, fixes #3842
=> Register CodeExplorerCommands from the correct assembly

Rubberduck.Core/Navigation/CodeMetrics/CodeMetricsAnalyst.cs, RubberduckTests/Stats/ParseTreeMetricsAnalystTests.cs
This is a vastly superior way to determine nesting.
Fixes #3757
=> Determine nesting based on blocks, not spaces

RubberduckTests/Refactoring/MoveCloserToUsageTests.cs
... using `Single` instead of `First` to ensure it fails fast. Maybe that'll make AppVeyor happy?
=> Fix move closer UT again

Rubberduck.Deployment/InnoSetup/Installer Build Script.iss
=> Enable french translation now that we have the french custom message file

Rubberduck.Core/UI/About/AboutControl.xaml, Rubberduck.Core/UI/About/AboutDialog.Designer.cs, Rubberduck.Core/UI/RubberduckUI.Designer.cs, Rubberduck.Core/UI/RubberduckUI.resx
Users should now have an easier time reporting issues.
=> Update about control

Rubberduck.Core/UI/Command/Refactorings/ProjectExplorerRefactorRenameCommand.cs, Rubberduck.VBEditor.VB6/SafeComWrappers/VB/VBProject.cs
=> VB6 ProjectId saved to .vbp file

Rubberduck.Main/ComClientLibrary/Abstract/UnitTesting/IFakesProvider.cs, Rubberduck.Main/ComClientLibrary/UnitTesting/FakeBase.cs, Rubberduck.Main/ComClientLibrary/UnitTesting/Fakes/CurDir.cs, Rubberduck.Main/ComClientLibrary/UnitTesting/Fakes/Environ.cs, Rubberduck.Main/ComClientLibrary/UnitTesting/FakesProvider.cs, RubberduckTests/IntegrationTests/FakeTests.bas
Fixes for CurDir and Environ fakes. Integration tests pass in Excel.
Issue #2891 tracks the fakes which have been completed, so if this is accepted then the status can be updated for CurDir (Environ was already marked as complete although it had issues)
=> Fakes update

Rubberduck.VBEditor.VB6/SafeComWrappers/VB/VBProject.cs
=> VB6 - Fix project and component events

Rubberduck.Core/UI/Inspections/InspectionResultsControl.xaml, Rubberduck.Resources/Inspections/InspectionsUI.Designer.cs, Rubberduck.Resources/Inspections/InspectionsUI.resx
Closes #4106 
F5 tested & Unit tested
=> Clarify fix all occurrences

Rubberduck.Core/AutoComplete/AutoCompleteBase.cs, Rubberduck.Core/AutoComplete/AutoCompleteBlockBase.cs, Rubberduck.Core/AutoComplete/AutoCompleteFunctionBlock.cs, Rubberduck.Core/AutoComplete/AutoCompletePropertyBlock.cs, Rubberduck.Core/AutoComplete/AutoCompleteService.cs, Rubberduck.VBEEditor/Events/VBENativeServices.cs, Rubberduck.VBEEditor/SafeComWrappers/VB/Abstract/ICodePane.cs, Rubberduck.VBEEditor/Selection.cs, Rubberduck.VBEEditor/WindowsApi/CodePaneSubclass.cs, Rubberduck.VBEEditor/WindowsApi/WinEvent.cs
=> AutoComplete IV

Rubberduck.Parsing/Grammar/VBAParser.g4, RubberduckTests/Grammar/VBAParserTests.cs
Closes #4137 
Made leading tuple on line special form optional.
=> Grammar tweak for line special form

Rubberduck.Core/AutoComplete/AutoCompleteBase.cs
Fixes the off-by-one bug that sends everything up in flames when you type this:
Call Anything(
So the good news is that it's fixed. The "bad" news... is that when parenthesis autocompletion is enabled, `Call` statement is special-cased and stripped - because the lovely VBE is being "helpful" and instantly removes empty parentheses in `Call Something()`, leaving the `(` key appear to do exactly nothing.
Short of preventing the VBE from "prettifying" the replaced line, stripping the explicit `Call` statement is really the only thing AC could do.
[See it in action](https://www.dropbox.com/s/i6hwqapja5aicew/RD%20AC%20-%20CallStmt.mp4?dl=0)
=> Critical AC fixes

Rubberduck.Core/UI/CodeExplorer/Commands/AddComponentCommand.cs, Rubberduck.Resources/Settings/AutoCompletesPage.de.resx, Rubberduck.Resources/Settings/SettingsUI.de.resx
German translations for Autocompletion Settings + Issue #4016 
Next time I'll create different branches for those non related commits, but I thought I could create a PR for each.
=> German translations for Autocompletion Settings + Issue #4016

README.md, Rubberduck.Core/UI/About/AboutControl.xaml, Rubberduck.Deployment/Licenses/License.rtf, Rubberduck.Resources/About/AboutUI.Designer.cs, Rubberduck.Resources/About/AboutUI.cs.resx, Rubberduck.Resources/About/AboutUI.de.resx, Rubberduck.Resources/About/AboutUI.fr.resx, Rubberduck.Resources/About/AboutUI.resx, Rubberduck.VBEEditor/license.md
Also adds a few contributors that were missing.
=> Update copyright notice

Rubberduck.CodeAnalysis/Inspections/Concrete/ParameterCanBeByValInspection.cs, Rubberduck.Refactorings/Common/DeclarationExtensions.cs, RubberduckTests/RubberduckTests.csproj, RubberduckTests/Symbols/DeclarationExtensionTests.cs
=> Fix association of property implementations to declaring interfaces

Rubberduck.Core/UI/Settings/IndenterSettings.xaml, Rubberduck.Core/UI/Settings/IndenterSettingsViewModel.cs, Rubberduck.Resources/RubberduckUI.Designer.cs, Rubberduck.Resources/RubberduckUI.resx, Rubberduck.SmartIndenter/AbsoluteCodeLine.cs, Rubberduck.SmartIndenter/AlignmentToken.cs, Rubberduck.SmartIndenter/IIndenter.cs, Rubberduck.SmartIndenter/IIndenterSettings.cs, Rubberduck.SmartIndenter/Indenter.cs, Rubberduck.SmartIndenter/IndenterConfigProvider.cs, Rubberduck.SmartIndenter/IndenterSettings.cs, Rubberduck.SmartIndenter/LogicalCodeLine.cs, RubberduckTests/Commands/IndentCommandTests.cs, RubberduckTests/Settings/IndenterSettingsTests.cs, RubberduckTests/SmartIndenter/EndOfLineCommentTests.cs, RubberduckTests/SmartIndenter/LineContinuationTests.cs, RubberduckTests/SmartIndenter/MiscAndCornerCaseTests.cs, RubberduckTests/SmartIndenter/SpecificSettingTests.cs, RubberduckTests/SmartIndenter/VerticalSpacingTests.cs
Using this to help tag all the fixed issues by ref'ing them. Will remove WIP tag when they're all ready to go.
=> Indenter fixes

Rubberduck.CodeAnalysis/Inspections/Concrete/ObsoleteCallingConventionInspection.cs, Rubberduck.CodeAnalysis/Rubberduck.CodeAnalysis.csproj, Rubberduck.Core/Properties/Settings.Designer.cs, Rubberduck.Core/Properties/Settings.settings, Rubberduck.Core/app.config, Rubberduck.Parsing/Grammar/VBALexer.g4, Rubberduck.Parsing/Grammar/VBAParser.g4, Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs, Rubberduck.Resources/Inspections/InspectionInfo.resx, Rubberduck.Resources/Inspections/InspectionNames.Designer.cs, Rubberduck.Resources/Inspections/InspectionNames.resx, Rubberduck.Resources/Inspections/InspectionResults.Designer.cs, Rubberduck.Resources/Inspections/InspectionResults.resx, RubberduckTests/Inspections/ObsoleteCallingConventionInspectionTests.cs, RubberduckTests/RubberduckTests.csproj
=> Make parser aware of CDecl, add inspection for its use

Rubberduck.Refactorings/Rename/RenameRefactoring.cs
=> VB6 - Fix CE rename command

Rubberduck.CodeAnalysis/Inspections/Concrete/ObjectVariableNotSetInspection.cs, Rubberduck.CodeAnalysis/Inspections/Concrete/VariableRequiresSetAssignmentEvaluator.cs, Rubberduck.Parsing/Symbols/BoundExpressionVisitor.cs, Rubberduck.Parsing/Symbols/Declaration.cs, Rubberduck.Parsing/Symbols/DeclarationFinder.cs, Rubberduck.Parsing/Symbols/IdentifierReference.cs, Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs
Fixes horrendous performance of object variable not set inspection.
=> ObjectVariableNotSetInspection? O(Yeah!)

Rubberduck.CodeAnalysis/Inspections/Concrete/VariableRequiresSetAssignmentEvaluator.cs, RubberduckTests/Inspections/ObjectVariableNotSetInspectionTests.cs
Ignore implicit sets in For Each statements. Addresses #4294 Ref #4318
=> Missing commit from #4314 

Rubberduck.Core/AutoComplete/AutoCompleteBlockBase.cs, Rubberduck.Core/AutoComplete/AutoCompleteService.cs, Rubberduck.VBEEditor/Events/AutoCompleteEventArgs.cs, Rubberduck.VBEEditor/Events/KeyPressEventArgs.cs, Rubberduck.VBEEditor/WindowsApi/CodePaneSubclass.cs
This could probably use a little refactor love eventually, but that would probably be more in scope for future AC fixes.
=> Sort out keys and chars. Should close #4293 AFAICT

docs/About.md
With the decision to remove source control from RD the page needed to be updated to reflect this.
=> Update about page

Rubberduck.Core/UI/UnitTesting/TestResultToOutcomeTextConverter.cs, Rubberduck.Resources/UnitTesting/TestExplorer.Designer.cs, Rubberduck.Resources/UnitTesting/TestExplorer.resx, Rubberduck.UnitTesting/UnitTesting/TestMethod.cs, RubberduckTests/UnitTesting/TestMethodTests.cs
Close #4386. Adds implicit categorization for tests.
=> Fix unit tests grouping by outcome

Rubberduck.CodeAnalysis/Inspections/Concrete/ModuleWithoutFolderInspection.cs, Rubberduck.CodeAnalysis/Rubberduck.CodeAnalysis.csproj, Rubberduck.Core/Properties/Settings.Designer.cs, Rubberduck.Core/Properties/Settings.settings, Rubberduck.Core/app.config, Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs, Rubberduck.Resources/Inspections/InspectionInfo.resx, Rubberduck.Resources/Inspections/InspectionNames.Designer.cs, Rubberduck.Resources/Inspections/InspectionNames.resx, Rubberduck.Resources/Inspections/InspectionResults.Designer.cs, Rubberduck.Resources/Inspections/InspectionResults.resx, RubberduckTests/Inspections/ModuleWithoutFolderInspectionTests.cs, RubberduckTests/RubberduckTests.csproj
=> Module without folder annotation

RubberduckCodeAnalysis/ChainedWrapperAnalyzer.cs, RubberduckCodeAnalysis/Resources.resx, RubberduckCodeAnalysis/RubberduckCodeAnalysis.csproj
imma gonna lemme teh pic speak fer itsolf:
=> Improve the messaging for the chained wrapper analyzer rule

Rubberduck.CodeAnalysis/Inspections/Concrete/OnLocalErrorInspection.cs, Rubberduck.CodeAnalysis/QuickFixes/RemoveLocalErrorQuickFix.cs, Rubberduck.CodeAnalysis/Rubberduck.CodeAnalysis.csproj, Rubberduck.Core/Properties/Settings.Designer.cs, Rubberduck.Core/Properties/Settings.settings, Rubberduck.Core/app.config, Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs, Rubberduck.Resources/Inspections/InspectionInfo.resx, Rubberduck.Resources/Inspections/InspectionNames.Designer.cs, Rubberduck.Resources/Inspections/InspectionNames.resx, Rubberduck.Resources/Inspections/InspectionResults.Designer.cs, Rubberduck.Resources/Inspections/InspectionResults.resx, Rubberduck.Resources/Inspections/QuickFixes.Designer.cs, Rubberduck.Resources/Inspections/QuickFixes.resx, RubberduckTests/Inspections/OnLocalErrorInspectionTests.cs, RubberduckTests/QuickFixes/RemoveLocalErrorQuickFixTests.cs, RubberduckTests/RubberduckTests.csproj
=> On local error inspection

docs/About.md
=> Fix typo in About.md

Rubberduck.VBEEditor/ComManagement/ComSafeBase.cs, Rubberduck.VBEEditor/ComManagement/StrongComSafe.cs, Rubberduck.VBEEditor/ComManagement/WeakComSafe.cs
Thanks to @retailcoder  for pointing out the little whoopsie I left in the ComBaseSafe regarding dispose.
=> Fix up the Dispose methods

appveyor.yml
Set AV cloning to shallow, be explicit in what kind of scripts we run
=> AppVeyor config updates

appveyor.yml
Upload Github artifacts by name instead of path
=> Fix Release Upload

Rubberduck.VBEEditor/VBERuntime/Settings/VBESettings.cs, Rubberduck.VBEEditor/VBERuntime/VBEDllVersion.cs, Rubberduck.VBEEditor/VBERuntime/Vb6NativeApi.cs, Rubberduck.VBEEditor/VbeRuntime/VbeNativeApiAccessor.cs
=> Sort out dlls for different versions.

Rubberduck.Deployment/BuildRegistryScript.ps1, Rubberduck.Deployment/IdlGeneration/IdlGenerator.cs
Add path checks & directory creation for missing folders.
Add pragmas to generated IDL files to ignore MIDL 2400 and 2401 warnings.
=> Deployment bug fixes

Rubberduck.Parsing/ComReflection/ComInterface.cs
[See chat](https://chat.stackexchange.com/transcript/message/47743401#47743401).
=> Release correct TypeAttr pointer...  Closes #3938

Rubberduck.CodeAnalysis/Inspections/Concrete/SheetAccessedUsingStringInspection.cs, Rubberduck.Core/UI/Inspections/InspectionResultsViewModel.cs, Rubberduck.Core/UI/UnitTesting/Commands/AddTestModuleCommand.cs, Rubberduck.Parsing/VBA/RubberduckParserState.cs, Rubberduck.Parsing/VBA/StateProjectManagerBase.cs, Rubberduck.VBEEditor/SourceCodeHandling/CodePaneSourceCodeHandler.cs
The name says it all.
Closes #4553
=> Fix some scw disposal

Rubberduck.Parsing/Rubberduck.Parsing.csproj, Rubberduck.Resources/CodeExplorer/CodeExplorerUI.resx, Rubberduck.Resources/CommandBarIcons.resx, Rubberduck.Resources/Inspections/InspectionsUI.resx, Rubberduck.Resources/RubberduckUI.resx, Rubberduck.VBEEditor/SafeComWrappers/SafeComWrapper.cs, RubberduckTests/Inspections/UntypedFunctionUsageInspectionTests.cs, RubberduckTests/Mocks/MockParser.cs, RubberduckTests/Mocks/MockVbeBuilder.cs, RubberduckTests/QuickFixes/IgnoreOnceQuickFixTests.cs, RubberduckTests/QuickFixes/UntypedFunctionUsageQuickFixTests.cs, RubberduckTests/Refactoring/RenameTests.cs
Currently, if one has the (bright?) idea to a make one's repository directories case-sensitive to match git's behaviour, RD does not build because of various case issues. This PR fixes them.
Moreover, this PR corrects the minor version of the referenced VBA library in several tests.
=> Case Corrections

Rubberduck.Core/Common/IOperatingSystem.cs, Rubberduck.Core/Common/WinAPI/SHCore.cs, Rubberduck.Core/Common/WindowsOperatingSystem.cs, Rubberduck.Core/Common/WindowsVersion.cs, Rubberduck.Core/Rubberduck.Core.csproj, Rubberduck.Core/Settings/GeneralSettings.cs, Rubberduck.Core/UI/Settings/GeneralSettings.xaml, Rubberduck.Core/UI/Settings/GeneralSettingsViewModel.cs, Rubberduck.Main/Extension.cs, Rubberduck.Resources/RubberduckUI.resx
Closes #4555.
Note, per-host settings not included in this PR, I think that may be a more wide-ranging change, see discussion on 4555.
=> Fix for High-DPI bug

Rubberduck.Core/UI/Inspections/InspectionResultsViewModel.cs, Rubberduck.Core/UI/Settings/SettingsForm.cs, Rubberduck.Core/UI/ToDoItems/ToDoExplorerViewModel.cs, Rubberduck.Core/UI/UnitTesting/TestExplorerViewModel.cs
Closes rubberduck-vba/Rubberduck#4610 and 2 more settings icon with the same problem.
I`m new here (and on GitHub) so please let me know if I did it correctly
=> Selecting the right Settings section

Rubberduck.Core/UI/AddRemoveReferences/AddRemoveReferencesWindow.xaml
Closes rubberduck-vba/Rubberduck#4662  I changed AddRemoveReferencesWindow HorizontalScrollBarVisibility to Auto
=> Add HorizontalScrollBar Closes rubberduck-vba/Rubberduck#4662

Rubberduck.Core/UI/UnitTesting/TestExplorerControl.xaml, Rubberduck.Core/UI/UnitTesting/TestExplorerControl.xaml.cs
I've added some code to the code behind - hopefully there isn't a simple way to link the column widths using XAML alone 
Closes #3831
=> Adjust column widths

Rubberduck.Core/Navigation/CodeExplorer/CodeExplorerCustomFolderViewModel.cs, Rubberduck.Core/UI/CodeExplorer/Commands/AddComponentCommand.cs, RubberduckTests/CodeExplorer/CodeExplorerFolderTests.cs
=> Code Explorer folder hotfix 2

Rubberduck.Resources/CodeExplorer/CodeExplorerUI.fr.resx, Rubberduck.Resources/Inspections/InspectionInfo.fr.resx, Rubberduck.Resources/Inspections/InspectionNames.fr.resx, Rubberduck.Resources/Inspections/InspectionResults.fr.resx, Rubberduck.Resources/Inspections/QuickFixes.fr.resx, Rubberduck.Resources/Menus/RubberduckMenus.fr.resx, Rubberduck.Resources/RubberduckUI.fr.resx, Rubberduck.Resources/Settings/SettingsUI.fr.resx, Rubberduck.Resources/Templates.fr.resx, RubberduckCodeAnalysis/Resources.fr.resx
(regex lingo still not translated though)
=> French translations for Reference Explorer and other missing French resources

Rubberduck.Deployment.Build/RubberduckPostBuildTask.cs
=> Prevent overwriting the 64-bit type library

Rubberduck.Core/Navigation/CodeExplorer/CodeExplorerItemComparer.cs, Rubberduck.Core/Navigation/CodeExplorer/CodeExplorerViewModel.cs, Rubberduck.Core/UI/CodeExplorer/CodeExplorerControl.xaml, Rubberduck.Core/UI/CodeExplorer/CodeExplorerControl.xaml.cs, Rubberduck.Core/UI/CodeExplorer/Commands/RenameCommand.cs, Rubberduck.Core/UI/Converters/CodeExplorerNodeToIconConverter.cs
Closes #3537 and closes #4759.  Also addresses [this issue from chat](https://chat.stackexchange.com/transcript/message/48822023#48822023).
=> CE bug fixes.

Rubberduck.Core/UI/About/AboutControl.xaml
=> Correct word wrapping on about dialog

Rubberduck.SettingsProvider/XmlPersistanceServiceBase.cs
Ensure created config file has root node. Closes #4816
=> Settings hot-fix.

.github/ISSUE_TEMPLATE/bug_report.md
Fix typos and capitalise for consistency
=> Minor corrections to bug_report.md

Rubberduck.Resources/About/AboutUI.cs.resx, Rubberduck.Resources/CodeExplorer/CodeExplorerUI.cs.resx, Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs, Rubberduck.Resources/Inspections/InspectionInfo.cs.resx, Rubberduck.Resources/Inspections/InspectionInfo.resx, Rubberduck.Resources/Inspections/InspectionNames.cs.resx, Rubberduck.Resources/Inspections/InspectionResults.cs.resx, Rubberduck.Resources/Inspections/InspectionsUI.cs.resx, Rubberduck.Resources/Menus/RubberduckMenus.cs.resx, Rubberduck.Resources/RubberduckUI.cs.resx, Rubberduck.Resources/Settings/UnitTestingPage.cs.resx, Rubberduck.Resources/Templates.cs.resx, Rubberduck.Resources/UnitTesting/TestExplorer.cs.resx
=> czech language for v2019-03-xx

Rubberduck.CodeAnalysis/Inspections/Concrete/ObsoleteWhileWendStatementInspection.cs, Rubberduck.CodeAnalysis/QuickFixes/ReplaceWhileWendWithDoWhileLoopQuickFix.cs, Rubberduck.Core/UI/CodeExplorer/CodeExplorerControl.xaml, Rubberduck.Core/UI/Inspections/InspectionResultsControl.xaml, Rubberduck.Core/UI/UnitTesting/TestExplorerControl.xaml, Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs, Rubberduck.Resources/Inspections/InspectionInfo.fr.resx, Rubberduck.Resources/Inspections/InspectionInfo.resx, Rubberduck.Resources/Inspections/InspectionNames.Designer.cs, Rubberduck.Resources/Inspections/InspectionNames.fr.resx, Rubberduck.Resources/Inspections/InspectionNames.resx, Rubberduck.Resources/Inspections/InspectionResults.Designer.cs, Rubberduck.Resources/Inspections/InspectionResults.fr.resx, Rubberduck.Resources/Inspections/InspectionResults.resx, Rubberduck.Resources/Inspections/QuickFixes.Designer.cs, Rubberduck.Resources/Inspections/QuickFixes.fr.resx, Rubberduck.Resources/Inspections/QuickFixes.resx, RubberduckTests/Inspections/ObsoleteWhileWendInspectionTests.cs, RubberduckTests/QuickFixes/ReplaceObsoleteErrorStatementQuickFixTests.cs, RubberduckTests/QuickFixes/ReplaceWhileWendWithDoWhileLoopQuickFixTests.cs
Reimplements #4859 (without the weird .csproj diffs)
Accidentally includes the commits of #4941.
=> ObsoleteWhileWendStatementInspection

Rubberduck.API/Rubberduck.API.csproj, Rubberduck.CodeAnalysis/Rubberduck.CodeAnalysis.csproj, Rubberduck.Core/Rubberduck.Core.csproj, Rubberduck.Deployment/Rubberduck.Deployment.csproj, Rubberduck.Interaction/Rubberduck.Interaction.csproj, Rubberduck.Parsing/Rubberduck.Parsing.csproj, Rubberduck.Refactorings/Rubberduck.Refactorings.csproj, Rubberduck.RegexAssistant/Rubberduck.RegexAssistant.csproj, Rubberduck.SettingsProvider/Rubberduck.SettingsProvider.csproj, Rubberduck.SmartIndenter/Rubberduck.SmartIndenter.csproj, Rubberduck.UnitTesting/Rubberduck.UnitTesting.csproj, Rubberduck.VBEEditor/Rubberduck.VBEditor.csproj, Rubberduck.VBEditor.VB6/Rubberduck.VBEditor.VB6.csproj, Rubberduck.VBEditor.VBA/Rubberduck.VBEditor.VBA.csproj, RubberduckTests/RubberduckTests.csproj
=> Update copyright year

docs/GettingStarted.md
Adding things that I found useful to get started that weren't very obvious here..
Hi @retailcoder 
I love that the getting started guide is very detailed and thorough 😄 
I would have loved it even better if it were a little more targeted towards newcomers like me 
and highlight some of the cool features here to get me started quickly!!
I would like to propose a revamp of this guide to get your guys' feedback 😃 
I just tried to give a flavor of my proposal here and can work on it based on your thoughts..
please let me know.
Cheers!
=> Enhancing the GettingStarted guide

Rubberduck.Core/UI/Controls/SearchBox.xaml.cs, Rubberduck.Core/UI/RegexAssistant/RegexAssistantViewModel.cs, Rubberduck.RegexAssistant/Atoms/Group.cs, Rubberduck.RegexAssistant/Expressions/ConcatenatedExpression.cs, Rubberduck.RegexAssistant/Expressions/SingleAtomExpression.cs, Rubberduck.RegexAssistant/QuantifierExtensions.cs
Small things I caught while closing open windows.
=> Correct minor issues

Rubberduck.CodeAnalysis/Inspections/Concrete/ArgumentWithIncompatibleObjectTypeInspection.cs, Rubberduck.CodeAnalysis/Inspections/Concrete/ImplementedInterfaceMemberInspection.cs, Rubberduck.CodeAnalysis/Inspections/Concrete/SetAssignmentWithIncompatibleObjectTypeInspection.cs
Website only reads xmldocs for inspection classes, at the class level.
=> Fixes xmldocs for new inspections

Rubberduck.Parsing/ComReflection/ComField.cs, Rubberduck.Parsing/ComReflection/ComParameter.cs, Rubberduck.Parsing/Symbols/DocumentModuleDeclaration.cs, Rubberduck.Parsing/Symbols/EventDeclaration.cs, Rubberduck.Parsing/Symbols/ProceduralModuleDeclaration.cs, RubberduckTests/Grammar/ResolverTests.cs, RubberduckTests/Inspections/ValueRequiredInspectionTests.cs
=> Fix as type names for array types resolved from COM

Rubberduck.Parsing/VBA/DeclarationCaching/DeclarationFinder.cs, RubberduckTests/Symbols/DeclarationFinderTests.cs
=> Rename conflict detection respects Project scope

Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/UnreachableCaseInspection.cs, Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs, Rubberduck.Resources/Inspections/InspectionInfo.cs.resx, Rubberduck.Resources/Inspections/InspectionInfo.de.resx, Rubberduck.Resources/Inspections/InspectionInfo.es.resx, Rubberduck.Resources/Inspections/InspectionInfo.fr.resx, Rubberduck.Resources/Inspections/InspectionInfo.resx, Rubberduck.Resources/Inspections/InspectionResults.Designer.cs, Rubberduck.Resources/Inspections/InspectionResults.cs.resx, Rubberduck.Resources/Inspections/InspectionResults.de.resx, Rubberduck.Resources/Inspections/InspectionResults.es.resx, Rubberduck.Resources/Inspections/InspectionResults.fr.resx, Rubberduck.Resources/Inspections/InspectionResults.resx
=> Improve Unreachable Case Inspection Messages

Rubberduck.CodeAnalysis/Inspections/Concrete/UnderscoreInPublicClassModuleMemberInspection.cs, RubberduckTests/Inspections/UnderscoreInPublicClassModuleMemberInspectionTests.cs
=> Fix Ignore and IgnoreModule for UnderscoreInPublicMemberName Inspection

Rubberduck.Core/UI/Settings/SettingsControl.xaml, Rubberduck.Resources/RubberduckUI.resx
=> Change in Ok button text to better represent actual functionality

Rubberduck.Core/UI/Converters/ImageSourceConverter.cs
Reverts rubberduck-vba/Rubberduck#5211
Provide a release to verify whether this still crashes - see #5217
=> Revert "Plug the WPF leak... maybe."

Rubberduck.Core/UI/Refactorings/EncapsulateField/EncapsulateFieldView.xaml
Fixes #5200 
Enabled Vertical scrollbar to auto.
Added Min height.
=> "Encapsulate Field" Enable Vertical scrollbar and Set Min Height

Rubberduck.Core/UI/UnitTesting/TestExplorerControl.xaml, Rubberduck.Core/UI/UnitTesting/TestExplorerControl.xaml.cs
Enabled a horizontal scrollbar to appear automatically when the window size is decreased for the Test Explorer.
Closes #5133.
=> Enabled automatic horizontal scrollbar for the Test Explorer window.

Rubberduck.Parsing/ComReflection/ComModule.cs, Rubberduck.Parsing/VBA/ParseCoordinator.cs, Rubberduck.VBEEditor/ComManagement/TypeLibs/TypeInfoConstantsCollection.cs, Rubberduck.VBEEditor/ComManagement/TypeLibs/Utility/VarDescExtensions.cs
That is the missing commit for the PR #5246 that was merged just a wee bit prematurely.
=> Move the extension class and use constant range instead.

Rubberduck.Deployment.Build/RubberduckPostBuildTask.cs, Rubberduck.Deployment.Build/RubberduckPreBuildTask.cs
Fixes #5254
Also adds some xmldocs to provide some context on how it works. Hopefully it is sufficient to provide the big picture and the rest of code should be self-documenting.
=> Build quote path everywhere and add some comments.

Rubberduck.Core/UI/CodeExplorer/CodeExplorerControl.xaml
=> Fix Add menu in CE

Rubberduck.Core/UI/Controls/ToolBar.xaml, Rubberduck.Core/UI/Inspections/InspectionResultsControl.xaml
…where they have been introduced in PR #5263
=> Replace tabs by spaces in XAML 

Rubberduck.Resources/CodeExplorer/CodeExplorerUI.fr.resx, Rubberduck.Resources/Experimentals/ExperimentalNames.fr.resx, Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs, Rubberduck.Resources/Inspections/InspectionInfo.fr.resx, Rubberduck.Resources/Inspections/InspectionInfo.resx, Rubberduck.Resources/Inspections/InspectionNames.fr.resx, Rubberduck.Resources/Inspections/InspectionResults.Designer.cs, Rubberduck.Resources/Inspections/InspectionResults.fr.resx, Rubberduck.Resources/Inspections/InspectionResults.resx, Rubberduck.Resources/Inspections/InspectionsUI.fr.resx, Rubberduck.Resources/Inspections/QuickFixes.fr.resx, Rubberduck.Resources/RubberduckUI.fr.resx, Rubberduck.Resources/Settings/SettingsUI.fr.resx, Rubberduck.Resources/UnitTesting/AssertMessages.fr.resx, Rubberduck.Resources/UnitTesting/TestExplorer.fr.resx
Draft for now - there will be at least one more commit to cover the rest of the keys.
=> French translations update

Rubberduck.Resources/CodeExplorer/CodeExplorerUI.de.resx, Rubberduck.Resources/RubberduckUI.Designer.cs, Rubberduck.Resources/RubberduckUI.cs.resx, Rubberduck.Resources/RubberduckUI.de.resx, Rubberduck.Resources/RubberduckUI.es.resx, Rubberduck.Resources/RubberduckUI.fr.resx, Rubberduck.Resources/Settings/SettingsUI.de.resx, Rubberduck.Resources/UnitTesting/TestExplorer.de.resx
Also removes some no longer used keys.
=> More German translations

Rubberduck.Parsing/Annotations/Concrete/ExcelHotKeyAnnotation.cs, RubberduckTests/Annotations/AttributeAnnotationTests.cs, RubberduckTests/Grammar/AnnotationTests.cs, RubberduckTests/QuickFixes/AddMissingAttributeQuickFixTests.cs
=> Fix Excel hotkey attribute annotation value

Rubberduck.CodeAnalysis/Inspections/Abstract/QuickFixBase.cs, Rubberduck.CodeAnalysis/Inspections/Concrete/ImplicitlyTypedConstInspection.cs, Rubberduck.Parsing/Grammar/PartialExtensions/VBAParserPartialExtensions.cs, Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs, Rubberduck.Resources/Inspections/InspectionInfo.resx, Rubberduck.Resources/Inspections/InspectionNames.Designer.cs, Rubberduck.Resources/Inspections/InspectionNames.resx, Rubberduck.Resources/Inspections/InspectionResults.Designer.cs, Rubberduck.Resources/Inspections/InspectionResults.resx, RubberduckTests/Inspections/ImplicitlyTypedConstInspectionTests.cs, RubberduckTests/Mocks/MockVbeBuilder.cs, RubberduckTests/QuickFixes/IgnoreOnceQuickFixTests.cs, RubberduckTests/StringExtensionsTests.cs
Close #5314.
I'm leaning heavily on Rubberduck.Inspections.Concrete.UntypedFunctionUsageInspection and its unit tests to build this inspection.
=> Add ImplicitlyTypedConstInspection and tests

Rubberduck.Core/AutoComplete/SelfClosingPairs/SelfClosingPairHandler.cs, RubberduckTests/AutoComplete/SelfClosingPairHandlerTests.cs
Closes #5341
Still working on the other SCP issues, but this one doesn't need to wait.
=> Honor SCP killswitch setting

Rubberduck.Parsing/VBA/DeclarationCaching/DeclarationFinder.cs, RubberduckTests/Grammar/ResolverTests.cs
Closes #3371
This adds the declaration type of the enclosing procedure to the key of the collection for new unresolved declarations, which makes the key unique per variable scope. Previously, property Get Lat and Set shared their undeclared variable declarations leading to bugs down the line.
=> Generate distinct unresolved variable declarations in Get Set and Let

README.md
Creating a branch+PR rather than a direct commit, because preview isn't rendering the Paypal button
=> Adding donate button

Rubberduck.Resources/Inspections/InspectionResults.de.resx
=> Fixed typo

Rubberduck.CodeAnalysis/Inspections/Concrete/ProcedureNotUsedInspection.cs, RubberduckTests/Inspections/ProcedureNotUsedInspectionTests.cs
=> ProcedureNotUsedInspection false positive for PropertyLet

Rubberduck.Resources/CodeExplorer/CodeExplorerUI.es.resx, Rubberduck.Resources/Experimentals/ExperimentalNames.es.resx, Rubberduck.Resources/Inspections/InspectionInfo.es.resx, Rubberduck.Resources/Inspections/InspectionNames.cs.resx, Rubberduck.Resources/Inspections/InspectionNames.de.resx, Rubberduck.Resources/Inspections/InspectionNames.es.resx, Rubberduck.Resources/Inspections/InspectionNames.fr.resx, Rubberduck.Resources/Inspections/InspectionNames.resx, Rubberduck.Resources/Inspections/InspectionResults.es.resx, Rubberduck.Resources/Inspections/InspectionsUI.es.resx, Rubberduck.Resources/Inspections/QuickFixes.es.resx, Rubberduck.Resources/Menus/RubberduckMenus.es.resx, Rubberduck.Resources/Refactorings/Refactorings.es.resx, Rubberduck.Resources/RegexAssistant/RegexAssistantUI.es.resx, Rubberduck.Resources/RubberduckUI.es.resx, Rubberduck.Resources/Settings/AutoCompletesPage.es.resx, Rubberduck.Resources/Settings/SettingsUI.es.resx, Rubberduck.Resources/Settings/ToDoExplorerPage.es.resx, Rubberduck.Resources/Settings/UnitTestingPage.es.resx, Rubberduck.Resources/ToDoExplorer/ToDoExplorerUI.es.resx, Rubberduck.Resources/UnitTesting/AssertMessages.es.resx, Rubberduck.Resources/UnitTesting/TestExplorer.es.resx
This resources were edited/created following Rubberduck recomendations (RESX Manager)
I'll be working in further standardization (same word -> same translation) and maybe you will receive another pull request later.
=> Spanish translations for new resource items

Rubberduck.Resources/Inspections/InspectionInfo.es.resx, Rubberduck.Resources/Inspections/InspectionNames.es.resx, Rubberduck.Resources/Inspections/InspectionResults.es.resx, Rubberduck.Resources/Inspections/InspectionsUI.es.resx, Rubberduck.Resources/Inspections/QuickFixes.es.resx, Rubberduck.Resources/RegexAssistant/RegexAssistantUI.es.resx, Rubberduck.Resources/Settings/AutoCompletesPage.es.resx
Minor changes in the rest of the resources (not only the new keys)
=> Definitively translations for spanish version

Rubberduck.Core/UI/CodeExplorer/Commands/ExportCommand.cs, Rubberduck.Core/UI/Command/ComCommands/ExportAllCommand.cs, Rubberduck.VBEEditor/SafeComWrappers/VB/Abstract/IVBComponent.cs, Rubberduck.VBEditor.VB6/SafeComWrappers/VB/VBComponent.cs, Rubberduck.VBEditor.VBA/SafeComWrappers/VB/VBComponent.cs, RubberduckTests/CodeExplorer/CodeExplorerViewModelTests.cs
Patches #5343 to get all tests green. Creds to @IvenBach for this one, my commit is just a minor tweak.
=> Completes #5343

Rubberduck.RegexAssistant/i18n/AssistantResources.Designer.cs, Rubberduck.RegexAssistant/i18n/AssistantResources.cs.resx, Rubberduck.Resources/CodeExplorer/CodeExplorerUI.Designer.cs, Rubberduck.Resources/CodeExplorer/CodeExplorerUI.cs.resx, Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs, Rubberduck.Resources/Inspections/InspectionInfo.cs.resx, Rubberduck.Resources/Inspections/InspectionNames.Designer.cs, Rubberduck.Resources/Inspections/InspectionNames.cs.resx, Rubberduck.Resources/Inspections/InspectionResults.Designer.cs, Rubberduck.Resources/Inspections/InspectionResults.cs.resx, Rubberduck.Resources/Inspections/InspectionsUI.Designer.cs, Rubberduck.Resources/Inspections/InspectionsUI.cs.resx, Rubberduck.Resources/Inspections/QuickFixes.Designer.cs, Rubberduck.Resources/Inspections/QuickFixes.cs.resx, Rubberduck.Resources/Menus/RubberduckMenus.Designer.cs, Rubberduck.Resources/Menus/RubberduckMenus.cs.resx, Rubberduck.Resources/Refactorings/Refactorings.Designer.cs, Rubberduck.Resources/Refactorings/Refactorings.cs.resx, Rubberduck.Resources/RegexAssistant/RegexAssistantUI.Designer.cs, Rubberduck.Resources/RegexAssistant/RegexAssistantUI.cs.resx, Rubberduck.Resources/RubberduckUI.Designer.cs, Rubberduck.Resources/RubberduckUI.cs.resx, Rubberduck.Resources/RubberduckUI.resx, Rubberduck.Resources/UnitTesting/TestExplorer.Designer.cs, Rubberduck.Resources/UnitTesting/TestExplorer.cs.resx
=> Czech translations v2.5.1

Rubberduck.Core/UI/AddRemoveReferences/AddRemoveReferencesWindow.xaml.cs
Related to https://github.com/rubberduck-vba/Rubberduck/issues/5553
=> Add additional checks to ensure that selection is valid

Rubberduck.Refactorings/EncapsulateField/EncapsulateFieldInsertNewCode/EncapsulateFieldCodeBuilder.cs, RubberduckTests/Refactoring/EncapsulateField/EncapsulateFieldCodeBuilderTests.cs
This PR fixes a regression bug identified in #5609 resulting from PR #5578.
=> Fix EncapsulateFieldRefactoring regression bug

Rubberduck.Core/UI/UnitTesting/TestExplorerControl.xaml, Rubberduck.Core/UI/UnitTesting/TestExplorerViewModel.cs, Rubberduck.Resources/RubberduckUI.Designer.cs, Rubberduck.Resources/RubberduckUI.resx
=> Add toggle to hide ignored tests

Rubberduck.CodeAnalysis/Inspections/Concrete/ImplicitPublicMemberInspection.cs, Rubberduck.Parsing/Grammar/VBABaseParserRuleContext.cs, Rubberduck.Parsing/VBA/DeclarationResolving/DeclarationSymbolsListener.cs, Rubberduck.Parsing/VBA/ParseCoordinator.cs, Rubberduck.Parsing/VBA/Parsing/ModuleParser.cs, Rubberduck.Parsing/VBA/Parsing/ParseRunner.cs, Rubberduck.Parsing/VBA/Parsing/ParseRunnerBase.cs, Rubberduck.Parsing/VBA/Parsing/SynchronousParseRunner.cs, RubberduckTests/Inspections/ImplicitPublicMemberInspectionTests.cs, RubberduckTests/Mocks/MockParser.cs
=> Include enums in ImplicitPublicMemberInspection

Rubberduck.CodeAnalysis/Inspections/Concrete/MisleadingByRefParameterInspection.cs, RubberduckTests/Inspections/MisleadingByRefParameterInspectionTests.cs
=> Fix  MisleadingByRefParameterInspection false positive: array parameters

Rubberduck.Parsing/ComHelper.cs
Wrap conditionals, Inline declaration, make `string.Empty` use explicit, and pattern matching.
=> Opportunistic edits

appveyor.yml
Branch was already renamed; YAML config needs to follow.
=> renamed 'master' to 'main'

Rubberduck.CodeAnalysis/Inspections/Concrete/IsMissingOnInappropriateArgumentInspection.cs, Rubberduck.CodeAnalysis/Inspections/Concrete/UseMeaningfulNameInspection.cs, Rubberduck.Core/UI/Command/ComCommands/FindAllReferencesCommand.cs, Rubberduck.Core/UI/Command/Refactorings/RefactorRemoveParametersCommand.cs, Rubberduck.Core/UI/Command/Refactorings/RefactorReorderParametersCommand.cs, Rubberduck.Parsing/VBA/DeclarationCaching/DeclarationFinder.cs, Rubberduck.Refactorings/Rename/RenameComponentOrProjectRefactoringAction.cs, Rubberduck.UnitTesting/CodeGeneration/TestCodeGeneratorStatics.cs, Rubberduck.VBEditor.VB6/SafeComWrappers/VB/VBComponent.cs, Rubberduck.VBEditor.VBA/SafeComWrappers/VB/VBComponent.cs, RubberduckTests/Inspections/IsMissingOnInappropriateArgumentInspectionTests.cs, RubberduckTests/QuickFixes/IsMissingOnInappropriateArgumentQuickFixTests.cs, RubberduckTests/Refactoring/Rename/RenameTests.cs
- Stops flagging IsMissing used with a ParamArray parameter
- Swallows any exceptions thrown from VBComponent.HasDesigner
=> Address a couple of low-hanging fruits

Rubberduck.Core/UI/Refactorings/Rename/RenameViewModel.cs, Rubberduck.Parsing/VBA/DeclarationCaching/DeclarationFinder.cs, RubberduckTests/Symbols/DeclarationFinderTests.cs
Closes #5694 
Closes #5695
This PR is submitted  in lieu of PR #5708.
=> 5694 RenameRefactoring false positive conflict

Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseEvaluation/UnreachableCaseInspector.cs, Rubberduck.Core/Navigation/CodeExplorer/CodeExplorerViewModel.cs, Rubberduck.Core/UI/CodeExplorer/CodeExplorerControl.xaml, Rubberduck.Core/UI/UnitTesting/TestExplorerViewModel.cs, RubberduckTests/CodeExplorer/MockedCodeExplorer.cs
=> Add expand/collapse all nodes to code explorer

Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs, Rubberduck.Resources/Inspections/InspectionInfo.de.resx, Rubberduck.Resources/Inspections/InspectionInfo.resx, Rubberduck.Resources/Inspections/InspectionNames.Designer.cs, Rubberduck.Resources/Inspections/InspectionNames.de.resx, Rubberduck.Resources/Inspections/InspectionNames.resx, Rubberduck.Resources/Inspections/InspectionResults.de.resx, Rubberduck.Resources/Inspections/QuickFixes.de.resx, Rubberduck.Resources/RubberduckUI.de.resx
Also adjusts some English resources slightly for consistency and because I am a pedantic mathematician.
I am very open to any suggestions to improve the translations.
=> Add German translations for 2.5.2

Rubberduck.VBEditor.VB6/SafeComWrappers/VB/AddIn.cs
Reverts commit 8ee1b175 (get VB6 menu positions by name, reverts to by index)
=> 2.5.2 Hotfix for VB6

Rubberduck.Core/UI/Controls/PersistGroupExpandedStateBehavior.cs, Rubberduck.Core/UI/ToDoItems/ToDoExplorerControl.xaml, Rubberduck.Core/UI/ToDoItems/ToDoExplorerViewModel.cs, Rubberduck.Resources/ToDoExplorer/ToDoExplorerUI.Designer.cs, Rubberduck.Resources/ToDoExplorer/ToDoExplorerUI.it.resx, Rubberduck.Resources/ToDoExplorer/ToDoExplorerUI.resx
I read PR #5627 and related #5483 Issue and try to solve. In my test Filter box appears and it is localized too.
Please put your attention to ToDoExplorerViewModel.cs where I had to sustitute
`... || CurrentUICulture.CompareInfo.IndexOf(...`
with
`... || CultureInfo.CurrentUICulture.CompareInfo.IndexOf(...`
to compile.
=> Try to solve Issue #5483 pr #5627

Rubberduck.Resources/Inspections/InspectionResults.de.resx
=> Added Space before variable

appveyor.yml
This hopefully restores coverage report uploads to our external coverage provider thingy.
=> Appveyor.yml shenanigans

Rubberduck.Resources/CodeExplorer/CodeExplorerUI.de.resx
Tried to use Visual Studio's translations or ones used already in this project when possible, otherwise went with what sounded better and/or more understandable to me.
=> Fixed spelling & improved wording of German translation

Rubberduck.UnitTesting/CodeGeneration/TestCodeGeneratorStatics.cs
Closes #5963 
Implements the solution proposed in #5963
=> Modify TestMethod template

Rubberduck.Core/UI/AddRemoveReferences/AddRemoveReferencesUI.it.resx, Rubberduck.Refactorings/RefactoringsUI.it.resx, Rubberduck.Resources/CodeExplorer/CodeExplorerUI.it.resx, Rubberduck.Resources/Inspections/InspectionResults.it.resx, Rubberduck.Resources/Menus/RubberduckMenus.it.resx, Rubberduck.Resources/Settings/SettingsUI.it.resx
I realized I never translated a lot of comments in resource files. Now most of them are.
=> Comments translation

Rubberduck.SmartIndenter/LogicalCodeLine.cs, RubberduckTests/SmartIndenter/MultiSegmentLineTests.cs
Fix for Indenter Bug #6007 .
Comments with colons were evaluated for Indent/Outdent.
=> Fix Indenter #6007

Rubberduck.CodeAnalysis/Inspections/Concrete/MultipleDeclarationsInspection.cs
=> Issue  #5829 Added the required example to documentation.

Rubberduck.Resources/Inspections/InspectionInfo.it.resx, Rubberduck.Resources/Inspections/InspectionNames.it.resx, Rubberduck.Resources/Inspections/InspectionResults.it.resx
Italian translation for new resources from #6035 PR
=> Italian translation for new resources from #6035 PR

Rubberduck.Core/Navigation/CodeExplorer/CodeExplorerSubMemberViewModel.cs
Tested in Excel for adding, modifying and removing enum values but couldn't figure out how to create an automated test case
=> Change enum signature to be updatable in code explorer

Rubberduck.Core/UI/About/AboutControl.xaml, Rubberduck.Core/UI/AddRemoveReferences/AddRemoveReferencesWindow.xaml
#5451  First form fixed.
I search all System Color references and transform to Dynamic.
=> AboutControl Dynamic

Rubberduck.Core/App.cs
=> Decode Windows version in RD logs

Rubberduck.Core/UI/AddRemoveReferences/AddRemoveReferencesWindow.xaml
=> #5451 AddRemoveReferences Form Convert

Rubberduck.Core/UI/Settings/IndenterSettingsUI.es.resx, Rubberduck.Refactorings/RefactoringsUI.es.resx, Rubberduck.Resources/RubberduckUI.Designer.cs, Rubberduck.Resources/RubberduckUI.es.resx
Hi guys! I am just getting started with using Visual Studio just for the purpose to help you guys somehow and to getting involved in the project as a thanks message for all your hard work.
I just added a few Spanish translations (which is my native language) just to make sure I am not messing anything up. If you guys can verify that I did the right thing. Then, I have the green light to put more work into it and create other pull requests later.
Please let me know if I need to do something else or something different.
Best,
=> Added some translations (es)

Rubberduck.Refactorings/RefactoringsUI.it.resx, Rubberduck.Refactorings/RefactoringsUI.resx, Rubberduck.Resources/Refactorings/Refactorings.it.resx
Italian traslation update and little typo in en-us version.
=> Italian traslation update and little typo in en-us version.

Rubberduck.Resources/Menus/RubberduckMenus.it.resx, Rubberduck.Resources/RubberduckUI.it.resx
=> Italian translation update

Rubberduck.Core/UI/CodeExplorer/CodeExplorerControl.xaml
Continue With #5451 
CodeExplorerControl.xaml
=>  #5451 CodeExplorerToDynamic

Rubberduck.Core/UI/CodeMetrics/CodeMetricsControl.xaml
Continue With #5451 
CodeMetricControl.xaml
=>  #5451 CodeMetricControl To DynamicResource

Rubberduck.Core/UI/FindSymbol/FindSymbolControl.xaml
=> Continue With #5451

README.md
=> Merge main into next
