- RetailCoder.VBE/UI/CodeInspections/CodeInspectionsDockablePresenter.cs
- RubberduckTests/UnitTesting/EngineTests.cs
`-=` some handlers in the `Dispose()` method - these handlers are nasty.
> Fixes issue #621

- RetailCoder.VBE/UnitTesting/NewUnitTestModuleCommand.cs
- RetailCoder.VBE/UnitTesting/ProjectTestExtensions.cs
- RetailCoder.VBE/UnitTesting/TestEngine.cs
- RubberduckTests/UnitTesting/EngineTests.cs
Expanded code coverage for issue #611; closes #623;
Moved `EnsureReference` extension method from `NewUnitTestModule` to `ProjectTestExtensions`. It seemed to fit better there now that the behavior has changed.
> Added Missing TestEngine tests

- Rubberduck.Parsing/Symbols/IdentifierReferenceListener.cs
Might not address all use cases - `With` blocks are nasty.
> Fixed With block resolution

- RetailCoder.VBE/Inspections/ParameterCanBeByValInspectionResult.cs
- RetailCoder.VBE/Properties/AssemblyInfo.cs
Fixes a bug where the quickfix would not remove an existing `ByRef` when changing a parameter to `ByVal`.
Repro:
Public Sub DoSomething(ByRef value)
End Sub
The quickfix would result in this broken code:
Public Sub DoSomething(ByRef ByVal value)
End Sub
> Fix for ParameterCanBeByValInspectionResult quickfix

- RetailCoder.VBE/Refactorings/ExtractMethod/ExtractMethodPresenter.cs
- RetailCoder.VBE/Refactorings/ExtractMethod/ExtractMethodPresenterFactory.cs
- RetailCoder.VBE/Refactorings/ExtractMethod/ExtractMethodRefactoring.cs
- RetailCoder.VBE/UI/CodeExplorer/CodeExplorerWindow.cs
- RubberduckTests/Mocks/MockFactory.cs
- RubberduckTests/Refactoring/ExtractMethodTests.cs
- RubberduckTests/Refactoring/RefactoringTestBase.cs
- RubberduckTests/Refactoring/RemoveParametersTests.cs
- RubberduckTests/Refactoring/ReorderParametersTests.cs
- RubberduckTests/RubberduckTests.csproj
Also extracted common setup code for the different refactorings into a common base class.
This brings us up to 20% coverage excluding the parser. 
The parser itself is 15% covered through indirect tests.
> ExtractMethodRefactoring test harness

- RubberduckTests/Mocks/MockFactory.cs
- RubberduckTests/Mocks/MockProjectBuilder.cs
- RubberduckTests/Mocks/MockVbeBuilder.cs
- RubberduckTests/Mocks/MockWindowsCollection.cs
- RubberduckTests/RubberduckTests.csproj
- RubberduckTests/VbeTestBase.cs
> implemented mock builders

- RetailCoder.VBE/Inspections/CodeInspectionQuickFix.cs
- RetailCoder.VBE/Rubberduck.csproj
- RetailCoder.VBE/UI/BindableSelectedItemBehavior.cs
- RetailCoder.VBE/UI/CodeInspections/CodeInspectionsDockablePresenter.cs
- RetailCoder.VBE/UI/CodeInspections/CodeInspectionsMenu.cs
- RetailCoder.VBE/UI/CodeInspections/InspectionResultsControl.xaml
- RetailCoder.VBE/UI/CodeInspections/InspectionResultsControl.xaml.cs
- RetailCoder.VBE/UI/CodeInspections/InspectionResultsViewModel.cs
- RetailCoder.VBE/UI/Command/RunCodeInspectionsCommand.cs
- RetailCoder.VBE/UI/UnitTesting/TestExplorerControl.xaml
- RetailCoder.VBE/UI/UnitTesting/TestExplorerControl.xaml.cs
This is a work-in-progress, merges work done by @Hosch250 on PR #721 and implements a proper composition root; most notable changes include: Rubberduck menu completely handled by IoC; all (most) components are now decoupled and sitting there, waiting to be "reconnected" - at this point only Unit Testing functionality works.
Other functionalities (code inspections, refactorings, etc.) are still "disconnected" - to "reconnect" them all that needs to happen is to implement the `ICommand` for them; this can be collaboratively worked on, hence I'm merging what I have at this point, because "reconnecting" all the components is quite a bit of work.
In the process, I've decided to re-implement the UI in WPF/XAML. Test Explorer is done, Inspection Results is in progress; rest of the UI hasn't been …
> Architecture changes (IoC)

- RetailCoder.VBE/UI/RubberduckUI.de.resx
- RetailCoder.VBE/UI/RubberduckUI.fr.resx
- RetailCoder.VBE/UI/RubberduckUI.jp.resx
- RetailCoder.VBE/UI/RubberduckUI.resx
- RetailCoder.VBE/UI/RubberduckUI.sv.resx
removed unused keys and added new keys to de, fr, jp and sv translations
> Ran TranslationHelper locale file normalization

- RetailCoder.VBE/Root/CommandBarsModule.cs
- RetailCoder.VBE/UI/RubberduckUI.de.resx
- RetailCoder.VBE/UI/RubberduckUI.resx
CommandBarsModule is now independent of String keys. This fixes #778 more future-proof than #779 
Also: minor corrections to German locale.
note: the indices are taken from the screenshot attached in #778
> Locale independence

- RetailCoder.VBE/Inspections/UntypedFunctionUsageInspection.cs
- RetailCoder.VBE/Inspections/UntypedFunctionUsageInspectionResult.cs
- RetailCoder.VBE/Rubberduck.csproj
- RetailCoder.VBE/UI/CodeInspections/InspectionResultsControl.xaml
- RetailCoder.VBE/UI/RubberduckUI.Designer.cs
- RetailCoder.VBE/UI/RubberduckUI.resx
- Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs
> Resolver picks up references to built-in type functions (e.g. Chr$)

- RetailCoder.VBE/Root/RubberduckModule.cs
- RetailCoder.VBE/UI/SourceControl/SourceControlBindings.cs
The UI isn't working, but the factories it relies on are being correctly bound to the IoC container now.
I can start debugging the *actual* issues next weekend.
> Fixed SourceControl factory IoC bindings

- RetailCoder.VBE/UI/ToDoItems/ToDoExplorerControl.xaml
- RetailCoder.VBE/UI/ToDoItems/ToDoExplorerControl.xaml.cs
- RetailCoder.VBE/UI/ToDoItems/ToDoExplorerViewModel.cs
- RubberduckTests/SourceControl/SCPresenterTests.cs
Fix double-click bug in Todo explorer, add new param to SC tests, make Todo explorer use config instead of defaults.
> Bug blipper

- Rubberduck.Parsing/Symbols/AdodbObjectModel.cs
- Rubberduck.Parsing/Symbols/ExcelObjectModel.cs
- Rubberduck.Parsing/Symbols/VbaStandardLib.cs
Apparently Visual Studio 2015 uses a new compiler which generates different code that in turn affects what GetNestedTypes() returns. See: http://stackoverflow.com/questions/31542076/behavior-of-assembly-gettypes-changed-in-visual-studio-2015.
This change resulted in a compiler generated class being returned for the built-in declarations which lead to an invalid cast exception. The fix simply ignores the compiler generated types.
Hosch250 tested the fix in Visual Studio 2013 and it seemed to work. I'm not sure if it'll work on Vista as well though.
> fix visual studio 2015 invalidcastexception for built-in declarations

- RetailCoder.VBE/Inspections/InspectionsUI.Designer.cs
- RetailCoder.VBE/Inspections/InspectionsUI.resx
- RetailCoder.VBE/Inspections/MoveFieldCloserToUsageInspection.cs
- RetailCoder.VBE/Inspections/MoveFieldCloserToUsageInspectionResult.cs
- RetailCoder.VBE/UI/RubberduckUI.de.resx
- MoveFieldCloseToUsageInspection -> MoveFieldCloserToUsageInspection (the inspection result was shown without name)
- German translation typo fix
> some small typo fixes

- RetailCoder.VBE/Inspections/ImplicitPublicMemberInspectionResult.cs
- RubberduckTests/Inspections/ImplicitPublicMemberInspectionTests.cs
Fixed to no longer rewrite entire procedure; quickfix simply adds access modifier to existing line and restores it as-is.
> ImplicitPublicMemberInspection

- Rubberduck.Parsing/Grammar/VBA.g4
also reordered them according to their size, because why not?
Integer | Long | LongLong | Single | Double | Currency | String
> updates for missing typedeclaration for LongLong

- RetailCoder.VBE/App.cs
- RetailCoder.VBE/Rubberduck.csproj
- RetailCoder.VBE/UI/Command/MenuItems/RubberduckCommandBar.cs
- RetailCoder.VBE/UI/Command/ShowParserErrorsCommand.cs
- RetailCoder.VBE/UI/Command/SyntaxErrorExtensions.cs
- Rubberduck.Parsing/VBA/RubberduckParser.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
Clicking the RubberduckCommandBar status label/button when parser state is `ParseError` will now bring up the "Search Results" toolwindow with a new tab showing parser errors.
> closes #1246

- RetailCoder.VBE/Inspections/InspectionBase.cs
- RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerViewModel.cs
- RetailCoder.VBE/UI/ToDoItems/ToDoExplorerViewModel.cs
- Rubberduck.Parsing/Symbols/IdentifierReference.cs
- Rubberduck.VBEEditor/QualifiedModuleName.cs
1. The "for next statement" can now have more than one type hint which caused an exception. Not quite sure why it's checking the parent for the type hint though since in the case of a "for next statement" the declaration of the variable including type hint could have happened somewhere else?
2. The other cases are mostly just switching the check from ParserState.Parsed to ParserState.Ready. The ToDoExplorerViewModel previously reloaded the configuration once per module which made everything slow down.
> Small parser/resolver performance improvements

- RetailCoder.VBE/UI/Command/Refactorings/RefactorExtractInterfaceCommand.cs
- Rubberduck.Parsing/Rubberduck.Parsing.csproj
- Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs
- Rubberduck.Parsing/Symbols/ProjectDeclaration.cs
- Rubberduck.Parsing/Symbols/ProjectReference.cs
- Rubberduck.Parsing/Symbols/ReferencedDeclarationsCollector.cs
- Rubberduck.Parsing/VBA/ReferencePriorityMap.cs
- Rubberduck.Parsing/VBA/RubberduckParser.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
- Rubberduck.VBEEditor/Extensions/VbProjectExtensions.cs
- Rubberduck.VBEEditor/QualifiedModuleName.cs
There's a new class ProjectDeclaration that contains the references to other projects with the priorities. Because this happens in the declaration gathering phase we can't add ProjectDeclarations as other references.
I changed the Reference.ReferenceId to ProjectId and also switched from using the ProjectName as ProjectId for references to using a combination of the name + path. Otherwise could not differentiate between two libraries with the same name. Not sure if this will always work though, there might be some cases I don't know about. Not so sure whether it's possible to reference two libraries with the same name in the same DLL either.
> associate project references correctly and in the correct order (#1340, #1347)

- Rubberduck.Parsing/VBA/RubberduckParser.cs
- Rubberduck.VBEEditor/QualifiedModuleName.cs
Class modules have their own declaration class now. Furthermore all built-in class modules have to be instantiated with IsExposed=true otherwise they won't be found as that specifies whether a class module is referenceable from external projects. Also for referenced projects / built-in projects a project path has to be passed to QualifiedModuleName, otherwise an incorrect project id will be created.
> fix wrong declaration type instantiated

- RetailCoder.VBE/Inspections/InspectionsUI.de.resx
- RetailCoder.VBE/Inspections/InspectionsUI.fr.resx
- RetailCoder.VBE/Inspections/InspectionsUI.ja.resx
- RetailCoder.VBE/Inspections/InspectionsUI.sv.resx
- RetailCoder.VBE/UI/RubberduckUI.de.resx
I added the German translation.
I found the following keys that are seemed to be obsolete:
Inspections_DeclarationOf
Inspections_UsageOf
CodeExplorer_AddClassText  here as been "&" in the text
Can these be removed?
I see that you look at the obsolete Let statement (key: ObsoleteLetStatementInspectionResultFormat).
Should't be there a check about the Set statement as well?
> Translation

- Rubberduck.Parsing/VBA/RubberduckParserState.cs
- RubberduckTests/Inspections/EmptyStringLiteralInspectionTests.cs
Removed Purged Inspections from RubberduckParserState, see #1441, removed unneeded Parser.State injections in EmptyStringLiteralsTest
> Followup for #1453

- RetailCoder.VBE/Common/RubberduckHooks.cs
- RetailCoder.VBE/Settings/HotkeySettings.cs
- RubberduckTests/RubberduckTests.csproj
- RubberduckTests/Settings/HotkeySettingsTests.cs
1. Only settings that match a member of the RubberduckHotkey Enum can be added to HotkeySettings.Settings. 
2. Only settings that can be successfully used to build a Hotkey can be added to HotkeySettings.Settings.
3. Missing members of the RubberduckHotkey Enum (no settings found in the config file) are added to HotkeySettings.Settings.
4. If more than one Hotkey is configured to use the same key binding - after the first binding is found all additional hotkeys assigned to that binding are disabled.
> Added input validation to HotkeySettings - closes #1281

- Rubberduck.Parsing/Binding/BindingService.cs
- Rubberduck.Parsing/Binding/DefaultBindingContext.cs
- Rubberduck.Parsing/Binding/IndexDefaultBinding.cs
- Rubberduck.Parsing/Binding/MemberAccessDefaultBinding.cs
- Rubberduck.Parsing/Binding/MemberAccessTypeBinding.cs
- Rubberduck.Parsing/Binding/SimpleNameDefaultBinding.cs
- Rubberduck.Parsing/Binding/SimpleNameProcedurePointerBinding.cs
- Rubberduck.Parsing/Binding/SimpleNameTypeBinding.cs
- Rubberduck.Parsing/Binding/VBAExpressionParser.cs
- Rubberduck.Parsing/Binding/VBAExpressionParser.g4
- Rubberduck.Parsing/Binding/VBAExpressionParserBaseListener.cs
- Rubberduck.Parsing/Binding/VBAExpressionParserBaseVisitor.cs
- Rubberduck.Parsing/Binding/VBAExpressionParserListener.cs
- Rubberduck.Parsing/Binding/VBAExpressionParserVisitor.cs
- Rubberduck.Parsing/Grammar/VBAParser.cs
- Rubberduck.Parsing/Grammar/VBAParser.g4
- Rubberduck.Parsing/Grammar/VBAParserBaseListener.cs
- Rubberduck.Parsing/Grammar/VBAParserBaseVisitor.cs
- Rubberduck.Parsing/Grammar/VBAParserListener.cs
- Rubberduck.Parsing/Grammar/VBAParserVisitor.cs
- Rubberduck.Parsing/Symbols/AccessibilityCheck.cs
- Rubberduck.Parsing/Symbols/ClassModuleDeclaration.cs
- Rubberduck.Parsing/Symbols/DeclarationFinder.cs
- Rubberduck.Parsing/Symbols/IdentifierReferenceListener.cs
- Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs
- Rubberduck.Parsing/VBA/RubberduckParser.cs
- RubberduckTests/Grammar/ResolverTests.cs
- RubberduckTests/Grammar/VBAParserTests.cs
File statement grammar rules have been cleaned up a bit. Marked file numbers can now be resolved as well (e.g. #filenumber). Input and InputB special forms should be parseable as well now.
Range should now be correctly resolved as _Worksheet.Range (the logic is there but since we can't link up ThisWorkbook/Sheet1/... up with their inherited types it doesn't actually work in practice yet). I'm not sure what the rules are for accessing inherited members tbh so I really hope there won't be false matches this way. All members of all inherited types are now considered part of the enclosing module. "Normal" interfaces are ignored because they don't allow such behavior.
The last change is the addition of the Circle and Scale special forms. They are not treated specially in the grammar. The …
> clean up file statements + consider inherited members as belonging to enclosed module + special forms

- Rubberduck.Parsing/Symbols/AccessibilityCheck.cs
- Rubberduck.Parsing/Symbols/Declaration.cs
- Rubberduck.Parsing/Symbols/DeclarationFinder.cs
- Rubberduck.Parsing/Symbols/FunctionDeclaration.cs
- Rubberduck.Parsing/Symbols/PropertyGetDeclaration.cs
- Rubberduck.Parsing/Symbols/ReferencedDeclarationsCollector.cs
- Rubberduck.Parsing/Symbols/TypeAnnotationPass.cs
I'll look at the failing test separately, because it seems like quite a few changes might be necessary, hope that's OK.
Edit: This might also be a fix for #1608 because apparently UDT members had array types that couldn't be resolved.
> fix built-in enums/udts can't be resolved because of missing parent

- Rubberduck.Parsing/Binding/IndexDefaultBinding.cs
- Rubberduck.Parsing/Binding/MemberAccessDefaultBinding.cs
- Rubberduck.Parsing/Symbols/ClassModuleDeclaration.cs
- Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs
- RubberduckTests/CodeExplorer/CodeExplorerTests.cs
1. Resolver test fixed, the member access expr now assumes that missing referenced declaration == something like variant/object (since we don't have declarations for those).
2. Built-In class modules were incorrectly marked as isexposed=false which lead to expressions like Err.Number not being resolved correctly. The number property couldn't be resolved, now it can.
3. Ignored the display name related test since it is a known issue and "hides" the other failed tests (such as the resolver test which I didn't notice unfortunately).
> fix failing resolver test + ignore display name related test + fix isexposed

- Rubberduck.Parsing/Symbols/ReferencedDeclarationsCollector.cs
These should be ignored universally, not only for events. 
Excel alone -= ~11000 declarations.
That should reduce the resolver overhead a bit...
> Generalized RD's ignorance of IDispatch and IUnknown members.

- RetailCoder.VBE/UnitTesting/TestEngine.cs
Sample output (with 2 tests in each of 3 modules)
```text
ModuleInitialize (TestModule3)
TestInitialize (TestModule3)
TestMethod33 (TestModule3)
TestCleanup (TestModule3)
TestInitialize (TestModule3)
TestMethod3 (TestModule3)
TestCleanup (TestModule3)
ModuleCleanup (TestModule3)
ModuleInitialize (TestModule1)
TestInitialize (TestModule1)
TestMethod11 (TestModule1)
TestCleanup (TestModule1)
TestInitialize (TestModule1)
TestMethod1 (TestModule1)
TestCleanup (TestModule1)
ModuleCleanup (TestModule1)
ModuleInitialize (TestModule2)
TestInitialize (TestModule2)
TestMethod22 (TestModule2)
TestCleanup (TestModule2)
TestInitialize (TestModule2)
TestMethod2 (TestModule2)
TestCleanup (TestModule2)
ModuleCleanup (TestModule2)
```
> Fixes #1711 to run module-specific test methods, for each module

- RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerViewModel.cs
- RetailCoder.VBE/UI/Command/MenuItems/RubberduckCommandBar.cs
- RetailCoder.VBE/UI/UnitTesting/TestExplorerModel.cs
- Rubberduck.Parsing/VBA/ParserState.cs
- Rubberduck.Parsing/VBA/RubberduckParser.cs
Refresh CE and TE after declarations are resolved, rather than waiting for inspections and reference resolving. Prevent reparse without changes from firing Ready when state is Error.
> Parser issues

- Rubberduck.Parsing/Grammar/VBAParser.cs
- Rubberduck.Parsing/Grammar/VBAParser.g4
- Rubberduck.Parsing/Grammar/VBAParserBaseListener.cs
- Rubberduck.Parsing/Grammar/VBAParserBaseVisitor.cs
- Rubberduck.Parsing/Grammar/VBAParserListener.cs
- Rubberduck.Parsing/Grammar/VBAParserVisitor.cs
- Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs
- Rubberduck.Parsing/Symbols/Identifier.cs
- Rubberduck.Parsing/Symbols/IdentifierReferenceListener.cs
- Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs
- RubberduckTests/Grammar/VBAParserTests.cs
* UDT parser rule looks more like the one in the VBA spec now. Not sure if it's preferrable to make one udt declaration instead of splitting it up into private/public (at least now it's clear what the default accessibility is)
* Enums don't seem to allow reserved keywords (unless I've missed one)
* Constant expressions inside of arraydims in udt members are resolved properly now ("dimspecs", e.g. udtMember(a To b))
With this PR all issues described in #1766 should be fixed.
> allow reserved keywords as udt members (fixes #1766)

- RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerViewModel.cs
Close #1783
Looks as if it was accidentally removed while resolving conflicts.
> Re-subscribe to event in ctor

- RetailCoder.VBE/Inspections/ObsoleteCallStatementInspection.cs
- RubberduckTests/Inspections/ObsoleteCallStatementInspectionTests.cs
> Do not fire Obsolete Call inspection when call has instruction separators

- RetailCoder.VBE/Inspections/IInspector.cs
- RetailCoder.VBE/Inspections/Inspector.cs
- RetailCoder.VBE/UI/Inspections/InspectionResultsViewModel.cs
- RubberduckTests/Inspections/EmptyStringLiteralInspectionTests.cs
- RubberduckTests/Inspections/ObsoleteCallStatementInspectionTests.cs
- RubberduckTests/Inspections/ObsoleteLetStatementInspectionTests.cs
- RubberduckTests/Inspections/ProcedureShouldBeFunctionInspectionTests.cs
This reverts commit 1288f95ff6f65b497ada9b1887217fa136bdc8b4.
Reverting because I don't have any hard proof that this is better and because we need this to be an async method.
> Revert "Tweak inspection UI performance"

- RetailCoder.VBE/Inspections/IParseTreeInspection.cs
- RetailCoder.VBE/Inspections/InspectionsUI.Designer.cs
- RetailCoder.VBE/Inspections/InspectionsUI.resx
- RetailCoder.VBE/Inspections/Inspector.cs
- RetailCoder.VBE/Inspections/MalformedAnnotationInspection.cs
- RetailCoder.VBE/Properties/AssemblyInfo.cs
- RetailCoder.VBE/Rubberduck.csproj
- Rubberduck.Parsing/Annotations/FolderAnnotation.cs
- Rubberduck.Parsing/Annotations/IgnoreAnnotation.cs
- RubberduckTests/Grammar/AnnotationTests.cs
- RubberduckTests/Inspections/MalformedAnnotationInspectionTests.cs
- RubberduckTests/RubberduckTests.csproj
> Prevent ctor throwing/create inspection for malformed annotations

- RetailCoder.VBE/Inspections/CodeInspectionQuickFix.cs
- RetailCoder.VBE/UI/Settings/Settings.cs
Close #2035 
Note that this will not update the menu when the language is changed until the inspection list is refreshed.
> Make inspection quick fix menu use correct localization

- RetailCoder.VBE/UI/Inspections/InspectionResultsViewModel.cs
> Disable Fix in Module/Project when parser state is not Ready

- RetailCoder.VBE/UI/Command/RunAllTestsCommand.cs
- RetailCoder.VBE/UI/UnitTesting/TestExplorerViewModel.cs
If any tests have the `AsTypeName` of `Rubberduck.PermissiveAssertClass` or `Rubberduck.AssertClass`, that is.
Close #2056
> Ensure projects reference the RD library before running tests

- RetailCoder.VBE/Inspections/ObjectVariableNotSetInspection.cs
- RubberduckTests/Inspections/ObjectVariableNotSetInpsectionTests.cs
Expanded ObjectVariableNotSet to check Functions and PropertyGet, fixes #2199
> ObjectVariableNotSet adjustments for Functions and Property Get

- RetailCoder.VBE/Inspections/UseMeaningfulNameInspection.cs
Possible fix for #2177 
Able to reproduce by deleting AppData\Roaming\Rubberduck\rubberduck.config
Looks like UseMeaningfulNameInspection.GetInspectionResults() was expecting IPersistence service to throw an IOException if config file not found; it actually returns null in this case, causing an object reference exception.
Maybe should be using CodeInspectionConfigProvider instead?
> Crashes Excel.exe on start up of VBA Editor #2177

- RetailCoder.VBE/Inspections/Inspector.cs
- RetailCoder.VBE/Inspections/ProcedureCanBeWrittenAsFunctionInspection.cs
- RetailCoder.VBE/Settings/CodeInspectionSettings.cs
- Rubberduck.Parsing/VBA/CombinedParseTreeListener.cs
fixes #2179 and now honors `@Ignore ProcedureCanBeWrittenAsFunction` annotation.
> Honor DoNotShow severity level for ParseTree inspections

- RetailCoder.VBE/Inspections/ObjectVariableNotSetInspection.cs
Partial fix for #2265. Requires a fix for #2266 before *all* functions
returning arrays are excluded.
> ignore functions returning arrays AND variable array assignments

- RetailCoder.VBE/Common/RubberduckHooks.cs
- RetailCoder.VBE/Common/WinAPI/User32.cs
Also fixed signature for `CallWindowProc`. `lpPrevWndFunc` can be a raw function pointer, also no need to create a delegate for the old WndProc, because it shouldn't ever be called directly.
> Remove subclass from RubberduckHooks in Dispose(). 

- RetailCoder.VBE/AutoSave/AutoSave.cs
- RetailCoder.VBE/Extension.cs
- Rubberduck.SettingsProvider/XmlPersistanceService.cs
The method `InitializeAddIn` in Extension.cs now loads the settings via a `GeneralSettingsProvider` instead of directly querying the `XmlPersistencyService`.  
This should fix issue #2347.
Additionally, this contains two small refactorings for code clarity I made along the way.
> Fix for issue #2347

- RetailCoder.VBE/Inspections/NonReturningFunctionInspectionResult.cs
- RubberduckTests/Inspections/NonReturningFunctionInspectionTests.cs
I added the `IgnoreOnce` quickfix to the list of quickfixes for the `NonReturningFunction` inspection in the case that the function is part of implementing an interface. 
A viable case for this was presented in issue #2365.
I also amended the corresponding test that verified that no quickfixes are provided in the interface case. Now, it verifies that exactly the `IgnoreOnce` quickfix is provided.
> IgnoreOnce quickfix for NonReturningFunction inspection in interface case

- RetailCoder.VBE/App.cs
- RetailCoder.VBE/Common/RubberduckHooks.cs
- RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerViewModel.cs
- RetailCoder.VBE/Root/RubberduckModule.cs
- RetailCoder.VBE/UI/CodeExplorer/Commands/AddClassModuleCommand.cs
- RetailCoder.VBE/UI/CodeExplorer/Commands/AddStdModuleCommand.cs
- RetailCoder.VBE/UI/CodeExplorer/Commands/AddUserFormCommand.cs
- RetailCoder.VBE/UI/CodeExplorer/Commands/ExportCommand.cs
- RetailCoder.VBE/UI/CodeExplorer/Commands/ImportCommand.cs
- RetailCoder.VBE/UI/Command/MenuItems/RubberduckCommandBar.cs
- RetailCoder.VBE/UI/Command/ReparseCommand.cs
- RetailCoder.VBE/UI/Inspections/InspectionResultsViewModel.cs
- Rubberduck.Parsing/VBA/RubberduckParser.cs
This PR potentially fixes a number of pending issues, by skipping the loading of type library `Rubberduck.tlb` (using GUID:{E07C841C-14B4-4890-83E9-8C80B06DD59D}) which has been seen "stalling' the *loading references* parser state; logging any ther type loader errors, so failing at that step shouldn't stall the parser state on "loading referenes" anymore.
The 'Refresh' command in Code Explorer and Inspection Results toolwindows now behaves more instinctively; also adjusted "busy" state in inspection results.
> Standardized Reparsing from Code Explorer and Inspection Results toolwindows

- RetailCoder.VBE/Common/ExportFormatter.cs
- RetailCoder.VBE/Navigation/RegexSearchReplace/RegexSearchReplace.cs
- RetailCoder.VBE/Navigation/RegexSearchReplace/RegexSearchReplacePresenter.cs
- RetailCoder.VBE/UI/Command/MenuItems/CommandBars/AppCommandBarBase.cs
- RetailCoder.VBE/UI/Command/MenuItems/ParentMenus/ParentMenuItemBase.cs
- RetailCoder.VBE/UI/Command/RegexSearchReplaceCommand.cs
- Rubberduck.Parsing/ComHelper.cs
- Rubberduck.Parsing/Properties/AssemblyInfo.cs
- Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs
- Rubberduck.VBEEditor/Rubberduck.VBEditor.csproj
- Rubberduck.VBEEditor/SafeComWrappers/Abstract/IVBComponents.cs
- Rubberduck.VBEEditor/SafeComWrappers/Office.Core/CommandBarButton.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/VBE.cs
- RubberduckTests/Grammar/ResolverTests.cs
- RubberduckTests/Mocks/MockUserFormBuilder.cs
- RubberduckTests/Refactoring/ExtractMethod/ExtractMethodParameterClassificationTests.cs
- RubberduckTests/SourceControl/ChangesViewModelTests.cs
- no more skipped tests (okay, except one, but it's tied to a specific documented issue#)
- cleaned up CommandBarButton wrapper event handling
- cleaned up compiler warnings (only `ExtractMethod` warnings remain)
> some cleanups

- Rubberduck.SmartIndenter/LogicalCodeLine.cs
- RubberduckTests/SmartIndenter/LineContinuationTests.cs
This is a straight-up hack, but it closes #2402
> FunctionAlign tweak for named parameters split by a line continuation.

- RetailCoder.VBE/Inspections/ChangeParameterByRefByValQuickFix.cs
- RetailCoder.VBE/Inspections/PassParameterByValueQuickFix.cs
- Rubberduck.SmartIndenter/AbsoluteCodeLine.cs
- Rubberduck.SmartIndenter/LogicalCodeLine.cs
- RubberduckTests/Inspections/ImplicitByRefParameterInspectionTests.cs
- RubberduckTests/Inspections/ParameterCanBeByValInspectionTests.cs
- RubberduckTests/SmartIndenter/LineContinuationTests.cs
- RubberduckTests/SmartIndenter/MiscAndCornerCaseTests.cs
- RubberduckTests/SmartIndenter/SpecificSettingTests.cs
2 tests are asserted as inconclusive pending more comprehensive (and probably easy) fixes.  Partially addresses  #2408 (cases without line continuations), closes #2407, handles numerous indenter issues that I was too lazy to open, probably some that I was never aware of.
> Various indenter fixes, partial fix for PassParameterByValueQuickFix

- Rubberduck.SmartIndenter/AbsoluteCodeLine.cs
- Rubberduck.SmartIndenter/Indenter.cs
- RubberduckTests/SmartIndenter/MiscAndCornerCaseTests.cs
Finishes handling of @ThunderFrame's evil bracketed identifier. May be some additional refactoring stemming from this.
> Ignore line numbers in continuations when indenting. 

- Rubberduck.Parsing/Symbols/AccessibilityCheck.cs
- Rubberduck.Parsing/Symbols/AliasDeclarations.cs
- Rubberduck.Parsing/Symbols/ClassModuleDeclaration.cs
- Rubberduck.Parsing/Symbols/DebugDeclarations.cs
- Rubberduck.Parsing/Symbols/FormEventDeclarations.cs
- RubberduckTests/Symbols/AccessibilityCheckTests.cs
- RubberduckTests/Symbols/ClassModuleDeclarationTests.cs
- RubberduckTests/Symbols/ConstantDeclarationTests.cs
- RubberduckTests/Symbols/ExternalProcedureDeclarationTests.cs
- RubberduckTests/Symbols/FunctionDeclarationTests.cs
- RubberduckTests/Symbols/ParameterDeclarationTests.cs
- RubberduckTests/Symbols/ProceduralModuleDeclarationTests.cs
- RubberduckTests/Symbols/ProjectDeclarationTests.cs
- RubberduckTests/Symbols/SubroutineDeclarationTests.cs
I added unit tests for the various subtypes of Declaration and refactored the three inventories for built-in declarations: `AliasDeclarations`, `DebugDeclarations`, and `FormEventDeclarations`.
Moreover, I added another test to those for `AccessibilityCheck` to document its limitations.
Doing this, several questions came to my mind, which you can read in the comments to my commits.
> Unit tests for subtypes of Declaration and refactorings

- RetailCoder.VBE/Inspections/Resources/InspectionsUI.de.resx
- RetailCoder.VBE/UI/RubberduckUI.de.resx
- RetailCoder.VBE/UI/RubberduckUI.fr.resx
- Rubberduck.thp
THP declaration for InspectionsUI needed updating after the namespace cleanup
additionally normalizes french RubberduckUI and provides updated German
Translations for RubberduckUI and InspectionsUI
> update German Translations and THP-Declarations

- Rubberduck.Parsing/Symbols/DeclarationFinder.cs
This passes the enum with the same name as the function test, but it's probably more generalizable to a more comprehensive solution to how enums are treated in the resolver.  Call it a shim ATM.
> Prefer parent procedure name for variable declarations with same name.

- RetailCoder.VBE/UI/Command/MenuItems/CommandBars/IContextFormatter.cs
- Rubberduck.Parsing/Symbols/AliasDeclarations.cs
- Rubberduck.Parsing/Symbols/DebugDeclarations.cs
- Rubberduck.Parsing/Symbols/DeclarationFinder.cs
- Rubberduck.Parsing/Symbols/FormEventDeclarations.cs
- Rubberduck.Parsing/Symbols/SpecialFormDeclarations.cs
- RubberduckTests/Inspections/UntypedFunctionUsageInspectionTests.cs
Aligned the load behaviour of the implementations of ICustomdeclarationLoader: now, they use the declarations at the time of the actual load of the declarations. Moreover, the declarations for the VBA project are only loaded once. (Also there is no hard fail anymore in the SpacialFormDeclarations in the situation that the VBA project is there, but not the information module.)
Furthermore, fixed a bug in FormsEventDeclarations I introduced yesterday.
Also includes the changes from PR #2487 of @retailcoder and the fixes of the failing tests.
> Custom declaration loading and some fixes from retailcoder

- Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponent.cs
Substitutes illegal characters with underscores.
There could be naming collisions using this approach - These 2 names would rename to the *same* name.
- `Report_Foo_Bar\Fizz`
- `Report_Foo\Bar_Fizz`
It might be safer to use a hash when choosing a name.
> Allow special characters in Access Forms and Reports

- RetailCoder.VBE/UI/Command/FindAllImplementationsCommand.cs
- RetailCoder.VBE/UI/Command/FindAllReferencesCommand.cs
- RetailCoder.VBE/UI/Command/ShowParserErrorsCommand.cs
- RetailCoder.VBE/UI/UnitTesting/TestExplorerModel.cs
- Rubberduck.VBEEditor/SafeComWrappers/Office.Core/CommandBar.cs
- Rubberduck.VBEEditor/SafeComWrappers/Office.Core/CommandBarButton.cs
- Rubberduck.VBEEditor/SafeComWrappers/Office.Core/CommandBarControl.cs
- Rubberduck.VBEEditor/SafeComWrappers/Office.Core/CommandBarControls.cs
- Rubberduck.VBEEditor/SafeComWrappers/Office.Core/CommandBarPopup.cs
- Rubberduck.VBEEditor/SafeComWrappers/Office.Core/CommandBars.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/AddIn.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/AddIns.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/CodeModule.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/CodePane.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/CodePanes.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/Control.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/Controls.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/LinkedWindows.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/Properties.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/Property.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/References.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponent.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponents.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/VBE.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/VBProject.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/VBProjects.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/Window.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/Windows.cs
Unfortunately it still crashes the host, but _much_ less dramatically.  All the WER logs now include clr information, so this is probably a step in the right direction at least.
> Add IsWrappingNullReference tests on setters and methods of SafeComWrappers.

- Rubberduck.Parsing/Preprocessing/LivelinessExpression.cs
It _might_ have been possible to fix this in the `VBAConditionalCompilationParser` grammar, but I was never able to track down what expression was responsible for the extra newline.  Regardless, this ensures that the selections aren't compressed when code is marked as dead.
> Fix MarkAsDead so it doesn't eat too extra NewLines. Closes #2022

- Rubberduck.Parsing/Symbols/DeclarationLoaders/AliasDeclarations.cs
- Rubberduck.Parsing/Symbols/DeclarationLoaders/DebugDeclarations.cs
- Rubberduck.Parsing/Symbols/DeclarationLoaders/FormEventDeclarations.cs
- Rubberduck.Parsing/Symbols/DeclarationLoaders/SpecialFormDeclarations.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
Made CustomDeclarationLoaders use the DeclarationFinder on the RubberduckParserState.
> CustomDeclarationLoaders now use finder on parser state 

- RetailCoder.VBE/Inspections/UseMeaningfulNameInspection.cs
- RubberduckTests/Inspections/UseMeaningfulNameInspectionTests.cs
Checks for declarations consisting of the same character repeated any number of times.
Added unit test and refactored similar tests in the class to remove duplicate code.
> #2260 Meaningful names inspection doesn't catch consecutive vowels

- Rubberduck.Parsing/VBA/ComponentParseTask.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
This fixes the wrong behaviour on parser errors and parser cancellation I introduced previously.
> Rework parse coordinator part1 bugfix

- RetailCoder.VBE/Refactorings/ExtractInterface/ExtractInterfaceRefactoring.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
This PR introduces a possibility to opt out of evaluating the overall parser state when setting module states and a method to trigger the evaluation manually.
This then gets used to set the module states for all components concurrently.
Furthermore, cancelation on reparse is introduced for the tests and `OperationCanceledExceptions`  in the `ParseCoordinator` are now handled (by swallowing them).
Moreover, the module states are now set before parsing or resolving the declarations, removing the flickering parser state.
> Rework parse coordinator part2

- RetailCoder.VBE/Inspections/ProcedureNotUsedInspection.cs
- Rubberduck.Parsing/Symbols/ProceduralModuleDeclaration.cs
Still need to catch the default member/indexer thing.
> Fix naming collision for built in enums and types. Ref #2620

- Rubberduck.Parsing/VBA/ComponentParseTask.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
I changed the locking in the `ParseCoordinator` on the parser runs such that we should have only one parsing run running a time  (except maybe in the tests where reparses run on the thread requesting them.)
Moreover, I introduced locking on setting the cancellation and exchanging the `CancellationTokenSources` in the `ParseCoordinator` to guarantee that each parsing run has a unique `CancellationTokenSource` that gets set to cancelled before the next parse is requested.
Furthermore, I changed the cancellation handling in the `ParseCoordinator` to `ThrowIfCancellationRequested` from just returning. That guarantees that we always return to the handler where we want the cancellations to stop.
Finally, I made the `ComponentParseTask` report all exceptions during the parse to its …
> Rework parse coordinator part4

- RetailCoder.VBE/App.cs
- RetailCoder.VBE/Extension.cs
- Rubberduck.VBEEditor/Events/VBENativeServices.cs
- Rubberduck.VBEEditor/Events/WindowChangedEventArgs.cs
- Rubberduck.VBEEditor/Rubberduck.VBEditor.csproj
- Rubberduck.VBEEditor/WindowsApi/CodePaneSubclass.cs
- Rubberduck.VBEEditor/WindowsApi/DesignerWindowSubclass.cs
- Rubberduck.VBEEditor/WindowsApi/FocusSource.cs
- Rubberduck.VBEEditor/WindowsApi/NativeMethods.cs
- Rubberduck.VBEEditor/WindowsApi/User32.cs
This should get @ThunderFrame's missing functionality back. It's still a bit tweaky though (updates the status bar twice) - I need to add code to discriminate between clicks **_in_** the Project Window and selection changes in the tree-view due to switching panes via their MDI windows.
> Add event source to track selection changes originating in Project Window.

- Rubberduck.Parsing/Symbols/DeclarationFinder.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
Made the `ParseCoordinator` remove all references upon reparse and not only those to the built-in declarations and the modules that have been modified.
This will have to change again, when I implement selective reference resolving.
This PR will make issue #2737 more obscure since there will never be a `DeclarationFinder` at whose time of construction any references are are resolved.
> Remove references of not reparsed components.

- Rubberduck.Parsing/Symbols/DeclarationFinder.cs
- Rubberduck.Parsing/VBA/ModuleState.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
I set up the infrastructure for saving module to module references on the `ModuleStates` and added the handling to the `ParseCoodinator`.  This will be used later on to enable selective reference resolving only for those modules for which the references might have changed.
I would appreciate any featback on this PR before I go on and implement the selective resolving.
In the implementation I opted to add the module to module references after all references have been resolved. I did this simply because it is much simpler than doing it while resolving the references. (One would have to get a reference to the correct `ModuleState` or the `RubberduckParserState` at the point where the references are added, the `BoundExpressionVisitor` if I see it correctly.) 
Although the path I have taken …
> Saving module to module references

- Rubberduck.Parsing/ComReflection/ComAlias.cs
- Rubberduck.Parsing/ComReflection/ComParameter.cs
Ref #2770.   This should close the issue, but I need someone with a 64 bit Office install to test it.
> Make retrieval of TypeName safe with 64 bit typelibs. 

- Rubberduck.Parsing/VBA/ParseCoordinator.cs
With this PR, not only those modules get reparsed that have been modified or which are new, but also all modules that are not in the state `Ready`.
The situation that a module is not modified or new and is not in the ready state can happen when there has been some an error or a cancellation in the last parsing run.
As an added benefit, switching to a `HashSet` to save the components to reparse improved the performance.
> Added reparsing of modules not in the ready state.

- Rubberduck.Parsing/Binding/SimpleNameDefaultBinding.cs
This PR basically prevents the creation of an undeclared variable Declaration with an identifier name of `Mid`.  This masks the underlying issue in #2618, which is that `Mid` is used in the grammar as both a statement (LHS) and a function (RHS). The only _visible_ side effect of this hack should be that it won't always show the function details on the command bar when the `Mid` is selected in a code pane.  This should be safe if the function is hidden by a user declaration - it would only effect an undeclared use, and that would result in a compile error.
Leaving #2618 open (even though this resolves the symptom) to track the need for a grammar fix.
> Hide the grammar issue around `Mid$` from the user.

- Rubberduck.Parsing/VBA/ParseCoordinator.cs
This introduces a hack to circumvent the cause of issue #2773.
In `ParseAllInternal`, which is only called in the live code, I added a delay of 50ms before refreshing the projects from the VBE so that the VBE has time to actually release components before we query it, in case the parse is requested from the handler for the component removed event.
> Hack for 2773

- Rubberduck.VBEEditor/Events/VBENativeServices.cs
- Rubberduck.VBEEditor/WindowsApi/User32.cs
Closes #2814
This is a temporary fix pending some better method of matching an `hWnd` to a `CodePane` than testing all of the captions in the CodePanes collection. Not sure if the VBE recycles all of the windows when it removes one, but if so we should be able to get a hook in there and manually track the window associations.
> Validate handles and catch COM errors when matching code panes.

- RetailCoder.VBE/UnitTesting/TestEngine.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.VBEEditor/Application/ExcelApp.cs
This and that:
1) Slightly more safety for long procedure names in Excel. (If > 255 chars, drop the filename.)
2) Catching and logging of COMExceptions thrown during running the unit tests. (`Application.Run` might not like what we are feeding it.) Exception gets logged and test gets set to `Inconclusive - Unexpected COM error`.
3) Small refactoring of `SyncCOMReferences` in the `ParseCoordinator`. Now, the setup for parallelism gets only performed if there is actually soemthing to load.
> Exception handling for unit tests and more

- Rubberduck.Parsing/Symbols/DeclarationFinder.cs
This should fix the second batch of errors from the log posted in issue #2912.
Previously the `Members` function on the `DeclarationFinder` assumed that we only look for declarations belonging to QMNs that exist in the `_declarations` collection.
> Added safe value retrieval to Members function on the DeclarationFinder

- RetailCoder.VBE/Root/RubberduckModule.cs
- Rubberduck.Parsing/Rubberduck.Parsing.csproj
- Rubberduck.Parsing/VBA/IDeclarationFinderProvider.cs
- Rubberduck.Parsing/VBA/IParseTreeProvider.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
In my previous PR, I assumed that our default interface binding was in singleton scope, which is not true.
This PR rebinds the runners and their likes in singleton scope.
The code in the previous PR only works because because everything uses the `RubberduckParserState` at the moment, which is bound in singleton scope.
> Extract class on parse coordinator - Fix of binding

- RetailCoder.VBE/API/ParserState.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.Parsing/VBA/ReferenceResolveRunner.cs
- Rubberduck.Parsing/VBA/ReferenceResolveRunnerBase.cs
- Rubberduck.Parsing/VBA/SynchronousReferenceResolveRunner.cs
- RubberduckTests/Mocks/MockParser.cs
This PR improves the cleanup in the ParseCoordinator.
1. Now, modules referencing removed modules will get reresolved no matter whether they have been modified or not.
2.  Module-to-module references get cleared correctly for removed modules.
3. The `ReferenceResolveRunner` now removes all references by the modules to resolve. This is safer than doing it in the `ParseCoordinator` because we have to cache the references to resolve for a potential cancellation. (The unresolved declarations would get loast otherwise.) 
4. The module-to-module references also get removed in the ReferenceResolveRunner` now. Again, this solves potential issues with cancelled parsing runs.
Moreover, superfluous state changes have been removed in the case that we do not parse anything. (These previously caused …
> Improvements on cleanup in ParseCoordinator

- RetailCoder.VBE/API/ParserState.cs
- Rubberduck.Parsing/Symbols/DeclarationFinder.cs
- Rubberduck.Parsing/VBA/ReferenceRemover.cs
- Rubberduck.Parsing/VBA/ReferenceRemoverBase.cs
- Rubberduck.Parsing/VBA/SynchronousReferenceRemover.cs
This removes a premature optimization in the `ReferenceRemoverBase` because of which eferences got only removed from user declarations. 
Closes #3002
> Fix issue 3002

- RetailCoder.VBE/API/ParserState.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.Parsing/VBA/ReferenceRemover.cs
- Rubberduck.Parsing/VBA/ReferenceRemoverBase.cs
- Rubberduck.Parsing/VBA/ReferenceResolveRunner.cs
- Rubberduck.Parsing/VBA/ReferenceResolveRunnerBase.cs
- Rubberduck.Parsing/VBA/SynchronousReferenceRemover.cs
- Rubberduck.Parsing/VBA/SynchronousReferenceResolveRunner.cs
The optimization removed in my last PR was not really premature.
This PR reintroduces the optimization. The bug fixed by removing the optimization is kept fixed by actually saving all module-to-module references, not just those to user-defined modules.
This saves about a second every parsing run in my test project. Here, the time saved does not scale with the number of modules to parse but with the total number of declarations, including those in referenced projects.
> Re-optimize reference removal

- RetailCoder.VBE/API/ParserState.cs
- RetailCoder.VBE/Root/RubberduckModule.cs
- Rubberduck.Parsing/Rubberduck.Parsing.csproj
- Rubberduck.Parsing/Symbols/ClassModuleDeclaration.cs
- Rubberduck.Parsing/Symbols/DeclarationFinder.cs
- Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs
- Rubberduck.Parsing/Symbols/TypeHierarchyPass.cs
- Rubberduck.Parsing/VBA/IParsingCacheService.cs
- Rubberduck.Parsing/VBA/ISupertypeClearer.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.Parsing/VBA/ParsingCacheService.cs
- Rubberduck.Parsing/VBA/SupertypeClearer.cs
- Rubberduck.Parsing/VBA/SupertypeClearerBase.cs
- Rubberduck.Parsing/VBA/SynchronousSupertypeClearer.cs
- RubberduckTests/Mocks/MockParser.cs
- RubberduckTests/Symbols/ClassModuleDeclarationTests.cs
This PR introduces a mechanism to clean up the super- and subtypes for modules that do not get reparsed themselves but implement one that does or are implemented by one that does.
Previously, the modules were left with stale super- and subtypes, respectively.
This fixes issue #2987.
> Cleaning up Super- and Subtypes

- Rubberduck.Parsing/Symbols/DeclarationFinder.cs
- Rubberduck.Parsing/Symbols/ICompilationPass.cs
- Rubberduck.Parsing/Symbols/ProjectDeclaration.cs
- Rubberduck.Parsing/Symbols/ProjectReferencePass.cs
- Rubberduck.Parsing/Symbols/TypeAnnotationPass.cs
- Rubberduck.Parsing/Symbols/TypeHierarchyPass.cs
- Rubberduck.Parsing/VBA/BuiltInDeclarationLoader.cs
- Rubberduck.Parsing/VBA/COMReferenceSynchronizerBase.cs
- Rubberduck.Parsing/VBA/ICOMReferenceSynchronizer.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.Parsing/VBA/ParsingStageService.cs
- Rubberduck.Parsing/VBA/ReferenceResolveRunnerBase.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
- RubberduckTests/Symbols/ProjectDeclarationTests.cs
Previously, the compilation passes always ran for all modules/declarations. This PR restricts them to those declarations for which they need to run. 
This should typically save about 1s on reparses since most of the time is spent in the `TypeAnnotationPass` for referenced projects, which typically do not change. (The performance measure is from my test project for performance tests where 90% of the declarations in that pass are built-in ones (of about 19000).)
This closes #2986. However, I forgot to put this into the appropriate commit message, which is not the last one. So I will close the issue manually after this PR got merged.
Moreover, this PR improves cache invalidation for module-to-module references in the case that project references get unloaded.
> Restricting compilation passes

- Rubberduck.Inspections/Concrete/MissingAttributeInspection.cs
- Rubberduck.Parsing/VBA/Attributes.cs
- RubberduckTests/Inspections/MissingAttributeInspectionTests.cs
The PR #3046 introduced a bug mentioned to us as a new issue in issue #3051:
Running the inspections failed with a false assertion whenever there have been annotations other than the attribute annotations.
This PR fixes this by removing the `Debug.Assert` and replacing it by returning `false`, if the annotation passed in does not have the `Attribute` flag.
> Remove HasAttribute Bug

- RetailCoder.VBE/UI/Refactorings/Rename/RenameView.xaml
- RetailCoder.VBE/UI/Refactorings/Rename/RenameView.xaml.cs
I admit that I don't understand how this works...
But eventually I will learn enough to understand.
Closes #3090
> Rename dialog - select all text in textbox when loading

- Rubberduck.Parsing/VBA/ComponentParseTask.cs
To be able to better pinpoint the location of non-syntax exceptions thrown while parsing I added the module name to the log message, as suggested in issue #3093.
> Report Module in Exception Log Message for Exceptions Thrown Parsing a Module

- Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs
- RubberduckTests/Inspections/NonReturningFunctionInspectionTests.cs
This PR fixes both #2803 and #2868.
The common issue was that in the resolver an assignment was never treated as such if the target had a default member. For let statements, this is correct. However, this is not correct for set statements; these never assign to the default member.
This PR does not contain any tests covering the issues, simply because I currently do not know how to set up a test including a type with a default member.
> Fixing Set Assignments

- Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs
As discussed in #3084, declarations which contain type hints should not be treated as `"Variant"`. The fix assigns proper `AsTypeName` property value for such declarations.
> Fixed AsTypeName for declarations with type hints

- RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerViewModel.cs
- Rubberduck.Parsing/Symbols/DeclarationFinder.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
So far, the module states of a project got removed in the event sinks, which is problematic for several reasons. First, they simply do not get removed in case the events are deactivated, e.g. because code is running. Second, for its own cache invalidation the `ParseCoordinator` needs to know which components got removed. That is not possible if they got removed already in the sinks.  
I added the cache invalidation for projects to the `ParseCoordinator` and removed the cache invalidation in the sinks. (They always initiate a parse.) There is only one exception. Currently, the entire project gets cleared if a component is renamed that has the supertype `Worksheet`. Since I could not find out the reasoning behind it, I left the code there and added a corresponding _todo_ remark. 
Fixes …
> Cache Invalidation for Projects Outside of the Sinks

- Rubberduck.Parsing/VBA/ParseCoordinator.cs
So far, there have been two different cache invalidation strategies in the `ParseCoordinator`. The production version took care to invalidate just as much cache as necessary given which modules had been added, removed or modified. In contrast, the test version cleared all declarations every time.
The reasoning to remove all declarations on every reparse while running tests was that the cache invalidation for removed and renamed projects happened in the sinks, which do not run in tests. (The mock VBE does not raise events.) Now that all the cache invalidation moved to the start of the production version, there is no need anymore to throw away everything in the tests.
So, in addition to a few tweaks to the cache invalidation, I went in and removed the special treatment of tests. Now, the …
> Unify Parse Running

- Rubberduck.Inspections/Concrete/IntegerDataTypeInspection.cs
- Rubberduck.Inspections/QuickFixes/ChangeIntegerToLongQuickFix.cs
- Rubberduck.Inspections/Rubberduck.Inspections.csproj
- Rubberduck.Parsing/Inspections/Resources/InspectionsUI.resx
- Rubberduck.Parsing/Inspections/Resources/InspectionsUI1.Designer.cs
- RubberduckTests/Inspections/IntegerDataTypeInspectionTests.cs
- RubberduckTests/RubberduckTests.csproj
Closes #3084 
I challenge anyone to find a bug :-)
I believe this inspection accounts for all possibilities, including type hint/no type hint combinations in interface and its implementation.
@retailcoder I have changed the proposed 
> {0} '{1}' is declared 'As Integer'
to
> {0} '{1}' is declared as Integer
because in case of type hints the literal 'As Integer' quote does not apply.
> Created IntegerDataTypeInspection

- RetailCoder.VBE/Root/RubberduckModule.cs
- RetailCoder.VBE/Settings/GeneralConfigProvider.cs
- RetailCoder.VBE/Settings/GeneralSettings.cs
- RetailCoder.VBE/UI/CodeExplorer/CodeExplorerControl.xaml
- RetailCoder.VBE/UI/RubberduckUI.Designer.cs
- RetailCoder.VBE/UI/RubberduckUI.resx
- RetailCoder.VBE/UI/Settings/GeneralSettings.xaml
- RetailCoder.VBE/UI/Settings/GeneralSettingsViewModel.cs
- RubberduckTests/Settings/GeneralSettingsTests.cs
This PR adds a "Experimental Features:" section to the bottom of the General Settings window, and a checkbox to "Enable Source Control".
The text box changes a Boolean value in the Settings store, which is read during the launch of RD to enable (or not) the presence of the Source Control item in the `Rubberduck` --> `Tools` menu.  It requires a restart to take effect, but since most users who will use SC will toggle it on once and leave it, I figure that requiring a restart should be fine.
When the checkbox is checked, a "Warning: this feature is Experimental! Use at your own risk!" message in red color appears above the checkbox.  I wanted to change the caption for the checkbox, but that would have involved some sort of event-handling which I didn't quite understand how to do yet, nor …
> Implement checkbox in Settings to enable Source Control.  SC disabled by default.

- RetailCoder.VBE/Common/LogLevelHelper.cs
This fixes the regression introduced in PR #3106.
At the beginning of `setMinimumLogLevel` a check was added to see if the new `minimumLogLevel` was same as the current log level.  That check also needed to see if this was the first time setting a minimum log level, as told by the `LogHeaderWritten` bool.
> Fix log levels greater than Info not appearing in logs

- Rubberduck.Parsing/Symbols/DeclarationFinder.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
- RubberduckTests/Symbols/DeclarationFinderTests.cs
So far, declarations can be accessed via the `DeclarationFinder` and directly via `AllDeclarations` and `AllUserDeclarations` on the `RubberduckParserState`. 
This PR rewires how the access on the `RubberduckParserState` works. Now, the public properties just refer to the corresponding properties on the `DeclarationFinder`. In addition, there is a new private property working like the old `AllDeclarations`, which is used to provide the declarations for constructing the `DeclarationFinder`.
Moreover, a new function got introduced returning whether there are declarations at all. This is used in the sinks instead of the old method of using `AllDeclarations.Count`. (This actually queried all all declarations every time.)
> All Declarations belong to the DeclarationFinder

- Installer Build Script.iss
- appveyor.yml
Makes it easier to integrate into AppVeyor's CI deployment scripts.
> removing version number from setup executable's filename

- Rubberduck.Parsing/VBA/ReferenceResolveRunnerBase.cs
In my last PR #3155 I optimized the way we try to find the supertype of document modules a bit. Unfortunately, I broke the handling of COM exceptions. This PR reintroduces proper handling of potential COM exceptions.
This should fix #3160
> Fix For 3160

- Rubberduck.Inspections/Concrete/ObjectVariableNotSetInspection.cs
- Rubberduck.Inspections/VariableRequiresSetAssignmentEvaluator.cs
- Rubberduck.Parsing/Grammar/VBAParser.g4
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.Parsing/VBA/ParsingCacheService.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
- Rubberduck.Parsing/VBA/SynchronousReferenceResolveRunner.cs
- RubberduckTests/Inspections/ObjectVariableNotSetInspectionTests.cs
This Pr includes some tweaks to the `ObjectVariableNotSetInspection`. Now, it will fire for a let assignment of `Nothing` to a `Variant` and never for any other literal. Moreover, it no longer crashes for assignments other than set and let assignments.
Fixes #3181
> Tweaks to the ObjectVariableNotSetInspection

- Rubberduck.VBEEditor/Rubberduck.VBEditor.csproj
- Rubberduck.VBEEditor/SafeComWrappers/Office.Core/CommandBarControl.cs
- Rubberduck.VBEEditor/SafeComWrappers/Office.Core/CommandBarControlCaptionGuard.cs
- RubberduckTests/RubberduckTests.csproj
- RubberduckTests/Symbols/CommandBarControlCaptionGuardTests.cs
This PR fixes #3082 by introducing a guard clause when the CommandBarControlCaption property is set.  When there is an attempt to set the Caption property to a string with more than 255 characters, the clause checks for a pattern match to apply specific reduction logic.  If the input string length exceeds 255 and the pattern match fails, the clause simply truncates the string and appends an ellipsis to prevent an exception/crash.
> 3082 long procedure names

- Rubberduck.Parsing/Symbols/DeclarationLoaders/FormEventDeclarations.cs
In my PR #3171 I forgot to change the parameter declarations in `FormEventDeclarations` to non-user-defined. This PR fixes that.
Closes #3189
> Fix for 3189

- RetailCoder.VBE/AppMenu.cs
- RetailCoder.VBE/Extension.cs
- RetailCoder.VBE/UI/Command/MenuItems/CommandBars/AppCommandBarBase.cs
- RetailCoder.VBE/UI/Command/MenuItems/CommandBars/IAppCommandBar.cs
- RetailCoder.VBE/UI/Command/MenuItems/CommandBars/RubberduckCommandBar.cs
- RetailCoder.VBE/UI/Command/MenuItems/ParentMenus/IParentMenuItem.cs
- RetailCoder.VBE/UI/Command/MenuItems/ParentMenus/ParentMenuItemBase.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.VBEEditor/SafeComWrappers/Office.Core/CommandBarButton.cs
- Rubberduck.VBEEditor/SafeComWrappers/Office.Core/CommandBarControl.cs
- Rubberduck.VBEEditor/SafeComWrappers/Office.Core/CommandBarControls.cs
- Rubberduck.VBEEditor/WindowsApi/SubclassingWindow.cs
- RubberduckTests/Inspections/ObjectVariableNotSetInspectionTests.cs
This PR is a first step towards a clean exist; it fixes one reason of the crash on exit: we have not been unregistering the `Click` events from the `CommandBarButton`s, neither in the command bar nor in the menus.  This leads to a fatal error on shutdown.
This PR changes the `CommandBarControl`s to be added permanently and to be removed explicitly on shutdown, removing the `Click` handlers as well. Moreover, as a safety measure, the GC gets invoked at the end of the shutdown.
There are more problematic sections I have identified and I am looking into. However, although there are still plenty of COM access violations on shutdown, I get a clean exit in Excel in production now, but not when debugging.
ref issue #3213
> First step towards clean exit

- .gitignore
- RetailCoder.VBE/Rubberduck.csproj.DotSettings
- Rubberduck.Inspections/Concrete/IllegalAnnotationInspection.cs
- RubberduckTests/Inspections/IllegalAnnotationsInspectionTests.cs
- RubberduckTests/Mocks/MockVbeBuilder.cs
- RubberduckTests/RubberduckTests.csproj
- RubberduckTests/packages.config
- Fixes *IllegalAnnotationInspection* false positive issue.
- Introduces `MockVbeBuilder.BuildFromStdModules` method, to facilitate setup for test cases that need two or more standard modules in the mock project.
> Fixes IllegalAnnotationInspection (#3339)

- Rubberduck.Inspections/Concrete/ShadowedDeclarationInspection.cs
This PR contains some performance tweaks for the `ShadowedDeclarationInspection`.
The is the same but looping through collections and walking trees is minimized using the work the parsing engine has already done.
> Shadowed declarations performance tweaks

- Rubberduck.Parsing/VBA/AttributeParser.cs
- Rubberduck.Parsing/VBA/ComponentParseTask.cs
- Rubberduck.Parsing/VBA/IAttributeParser.cs
- Rubberduck.Parsing/VBA/VBAModuleParser.cs
- RubberduckTests/Mocks/TestAttributeParser.cs
This PR kind of addreses issue #3180.
It does not directly implement what has been proposed there, but instead reverts the order of the attributes pass and the code pane pass. This way, any parser error that happens also happens in the code pane pass will happen there. Only the very rare parser errors that only happen in the attributes pass will get a line number from the exported modules.
As a littele add-on, this PR contains a little refactoring of the `ComponentsParseTask` and the parseres with a little C#7 tuple niceness.
> Fixing the reported line number on parser errors

- Rubberduck.Inspections/Concrete/BooleanAssignedInIfElseInspection.cs
- Rubberduck.Inspections/Inspector.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
This PR has three parts:
1) I made the `Inspector` use `Parallel.ForEach` in one task to run all inspections. `Parrallel.ForEach` is more optimized towards computation bound tasks than running everything in separate tasks.
2) Testing that 1. did not break things, I found a missing null check in the `BooleanIsAssignedInIfElseInspection`. (It now bails out if there is no else block instead of crashing the inspection.) 
3)  I simplified the handling of cancellation token sources in the `ParseCoordinator`. We really only ever have one active cancellation token source and replace it under a lock. So there is no need for a collection.
> Small process adjustments

- RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerViewModel.cs
- RetailCoder.VBE/UI/Command/AddTestMethodCommand.cs
- RetailCoder.VBE/UI/Command/AddTestMethodExpectedErrorCommand.cs
- RetailCoder.VBE/UI/Command/AddTestModuleCommand.cs
- RetailCoder.VBE/UI/Command/IndentCurrentModuleCommand.cs
- RetailCoder.VBE/UI/Command/IndentCurrentProcedureCommand.cs
- RetailCoder.VBE/UI/Command/Refactorings/RefactorExtractMethodCommand.cs
- RetailCoder.VBE/UI/Command/ShowParserErrorsCommand.cs
- Rubberduck.Parsing/IParseResultProvider.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
This PR removes the last questionable uses of `IVBComponents` from the `RubberduckParserState`: the `ParserProgressEventArgs` now contain a QMN instead of the component and the saved exceptions now use QMNs as keys. 
These changes allow the `SearchResultViewModel` to find module declarations without any COM access. This should eliminate the non-recoverable parser error after removing a component that had a parser error.
Moreover, I took the liberty to remove the second optional argument from `OnParseRequested`, which was a lie, anyway: there is no possibility to request a parse just for one module, nor would that make too much sense. (Everything in a dirty state has to be parsed to produce a sensible result.)
> QMNs for module state changes and saved exceptions

- Rubberduck.Inspections/Concrete/EmptyModuleInspection.cs
- Rubberduck.Inspections/Rubberduck.Inspections.csproj
- Rubberduck.Parsing/Inspections/Resources/InspectionsUI.de.resx
- Rubberduck.Parsing/Inspections/Resources/InspectionsUI.resx
- Rubberduck.Parsing/Inspections/Resources/InspectionsUI1.Designer.cs
- RubberduckTests/Inspections/EmptyModuleInspectionTests.cs
- RubberduckTests/RubberduckTests.csproj
This PR closes #1732 
I went and implemented the empty module inspectioan. This deems a module empty if there is nothing but module options, comments, and def directives, which all do not constitute functionality.
It uses a parse tree visitor to check whether a module is empty. I chose this approach over a listener since the inspection only has to look at the top levels of the parse tree to determine whether it is empty.
> Empty module inspection

- RetailCoder.VBE/Common/ModuleExporter.cs
- Rubberduck.Parsing/VBA/AttributeParser.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponent.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponents.cs
Doing some reseach, I found an MS support reply that stated that the VBE always uses the ANSI codepage from the windows settings of the system a project has last been saved on. For our purposes, this should always be the current system, I think.
Accordingly, I changed the encoding for reading and writing the code of user forms, for which we have a special handling, to the current windows ANSI codepage, `Encoding.Default`. Previously, we read the file as UTF7, which eliminates all `+` characters since these are special characters in UTF7. Then we wrote the results of the special handling to the file in the default UTF8 encoding. When importing the file, we still used the default encoding heuristic.
In addition, I made it explicit in the code that the code in document modules gets exported …
> Bring user form export encoding in line with the vbe

- RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerViewModel.cs
- RetailCoder.VBE/UI/Command/FindAllImplementationsCommand.cs
- RetailCoder.VBE/UI/Command/FindAllReferencesCommand.cs
- RetailCoder.VBE/UI/Command/MenuItems/CommandBars/AppCommandBarBase.cs
- RetailCoder.VBE/UI/Command/MenuItems/CommandBars/RubberduckCommandBar.cs
- RetailCoder.VBE/UI/Command/MenuItems/UiDispatcher.cs
- RetailCoder.VBE/UI/Command/ShowParserErrorsCommand.cs
- RetailCoder.VBE/UI/Inspections/InspectionResultsViewModel.cs
- RetailCoder.VBE/UI/SourceControl/SourceControlViewViewModel.cs
Closes #3542 
This PR removes a bug where a try catch block has been around a dispatch instead of in the dispatched delegate. I also took the liberty to implement a log and swallow approach around all delegates dispatched to the UI thread, except those from the API. 
Moreover, this adds some more safety against COM exceptions in `AppCommandBarBase`.
> Fixing try catch on dispatch

- .gitignore
- RetailCoder.VBE/Rubberduck.csproj
- RetailCoder.VBE/packages.config
- Rubberduck.SourceControl/GitProvider.cs
- Rubberduck.SourceControl/Rubberduck.SourceControl.csproj
- Rubberduck.SourceControl/_SourceControlClassDiagram.cd
- Rubberduck.SourceControl/packages.config
- RubberduckTests/RubberduckTests.csproj
- RubberduckTests/packages.config
#2497 
API changed:
-> repository.commit() now mandates 'author' and 'commiter' as two distinct parameters. I pass into both the same value by default.
-> repository.Stage() passes to the static class 'Commands' taking the repo as a first parameters.
-> repository.Pull() undergoes the same change
-> repository.Checkout() also
-> repository.Remove() also
-> repository.Fetch() takes the biggest changes.
-It now requires by default a refSpec. As we will usually fetch everything, I hardcoded on the code the classic "+refs/heads/*:refs/remotes/origin/*".
-It also requires a logMessage, which I hardoced empty ("")
-> repository.Branches[branch].Remote changes as well. Now this collection moves to the .Network class member of the repository, as repo.Network.Remotes[branch]
Changes to be …
> Updated LibGit2Sharp to version v0.24.0 fixes #2497

- RetailCoder.VBE/AppMenu.cs
- RetailCoder.VBE/Extension.cs
- RetailCoder.VBE/UI/Command/MenuItems/CommandBars/AppCommandBarBase.cs
- RetailCoder.VBE/UI/Command/MenuItems/ParentMenus/ParentMenuItemBase.cs
- RetailCoder.VBE/UI/DockableToolwindowPresenter.cs
- Rubberduck.VBEEditor/SafeComWrappers/Abstract/ISafeComWrapper.cs
- Rubberduck.VBEEditor/SafeComWrappers/SafeComWrapper.cs
This PR increases the number of COM wrappers we release on shutdown and reduces the number of access violations. 
This is still WIP since I still have to release the window objects of the dockable tool windows. 
Currently, 13 access violations are remaining on my system for Excel. (21 before this PR)
Please note that I currently have to resort to final releasing the parents of the top-level windows; I simply have not found out yet who else is holding a different wrapper for them.
Apart from adding more `Release`/`Dispose` calls, I implemented `IDisposable` on the `SafeComWrapper`: `Dispose` releases the underlying COM object if it has not yet been released.
> More COM release on shutdown

- RetailCoder.VBE/AppMenu.cs
- RetailCoder.VBE/Extension.cs
- RetailCoder.VBE/Root/RubberduckIoCInstaller.cs
- RetailCoder.VBE/UI/Command/MenuItems/CommandBars/AppCommandBarBase.cs
- RetailCoder.VBE/UI/Command/MenuItems/ParentMenus/ParentMenuItemBase.cs
- RetailCoder.VBE/UI/Controls/SearchResultPresenterInstanceManager.cs
- RetailCoder.VBE/UI/DockableToolwindowPresenter.cs
- RetailCoder.VBE/UI/DockableWindowHost.cs
- Rubberduck.VBEEditor/SafeComWrappers/SafeComWrapper.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/Windows.cs
- Rubberduck.VBEEditor/WindowsApi/SubclassingWindow.cs
This PR contains some more tweaks relating to the shutdown issue.
Following the leads provided by @WaynePhillipsEA I added disposal code for some more com wrappers.
Doing this in the IoC installer allowed to remove the final release code in the app menu disposal. 
In addition, I changed the disposal of the subclasing windows and dockable hosts somewhat to allow them to be collected when we are unloaded via the menu. 
Atm, for me shutdown has a chance of about 50% to have no access violation and of 50% to have one. However, when I comment out the forced GC at shutdown, I get lots of access violations.
> More shutdown tweaks

- RetailCoder.VBE/UI/RubberduckUI.Designer.cs
- RetailCoder.VBE/UI/RubberduckUI.resx
- RetailCoder.VBE/UI/UnitTesting/TestExplorerControl.xaml
- Retailcoder.VBE/UI/RubberduckUI.resx
Close #3507. Allows single test to be run.
Should this be expanded to include multiple selected tests?
> Close Issue 3507 run selected unit test

- RetailCoder.VBE/UI/RubberduckUI.Designer.cs
- RetailCoder.VBE/UI/RubberduckUI.resx
- RetailCoder.VBE/UI/ToDoItems/ToDoExplorerViewModel.cs
- Retailcoder.VBE/UI/RubberduckUI.resx
- RubberduckTests/TodoExplorer/TodoExplorerTests.cs
Closes #3642
Previously the TODO markers had a trailing space in the settings (not in the German localisation however) which served as the word boundary test for identifying TODO markers in comments. This change is to use regular expressions to match the TODO markers as whole words which is more flexible and less likely to get false positive from words ending with any of the TODO markers.
Notes
1) French localised settings file also has trailing spaces but not updated as doing this created a great many XML changes (about space="preserve") so not sure if doing this right. If this is okay, I can modify the pull request.
2) Two copies of the file RubberduckUI.resx appear in the change log even though only one was changed. Seems to already have two copies in the repository (in …
> Refine criteria for matching TODO markers

- codecov.yml
Instead of checking a flat number, we allow up to 5% coverage decrease, unless in RD's core from a PR.
inspection coverage can now be checked separately.
Additionally we do not check the patches themselves. We have no really good way to check for UI changes, so it makes no sense to require patches to have coverage...
lastly the comment behaviour has been adjusted a bit to be less imagey and a tad shorter
> Smarten up the Codecov Report

- RetailCoder.VBE/Common/Hotkeys/Hotkey.cs
- RetailCoder.VBE/Settings/CodeInspectionSettings.cs
- RubberduckTests/Inspections/InspectionsHelper.cs
Add a missing `return` in a fail case for the `Hotkey.cs` and add `null` for RPS for the code inspection and also fix the `InspectionHelper` to provide name for the inspection so that it can locate in the settings correctly.
> Minor tweaks

- codecov.yml
Add additional flags for tools and ui.
Ignore Rubberduck.VBEEditor in coverage, because COM Wrappers are barely testable
Ignore RubberduckTests itself because it skews coverage stats and isn't really meaningful ...
> Smarten codecov some more

- Rubberduck.Inspections/QuickFixes/AssignedByValParameterMakeLocalCopyQuickFix.cs
- RubberduckTests/Inspections/AssignedByValParameterInspectionTests.cs
- RubberduckTests/QuickFixes/AssignedByValParameterMakeLocalCopyQuickFixTests.cs
The AssignByValueMakeLocalCopyQuickFix does not properly handle rewriting the AsTypeContext of a function.  This PR corrects the behavior.  
The current result when this QuickFix is applied to a Function:
Original code:
```vba
Private Function AddTwo(ByVal arg As Long) As Long
arg = arg + 2
AddTwo = arg
End Function
```
After the QuickFix makes a local copy of `arg` (Uncompilable):
```vba
Private Function AddTwo(ByVal arg As Long)
Dim localArg As Long
localArg = arg As Long  <-- Function's AsTypeContext is pushed to here
localArg = localArg + 2
AddTwo = localArg
End Function
```
The PR also enhances the QuickFix to retain any existing comment after the Sub/FunctionStmtContext and match the indentation format of the original code's first line.
> AssignByValueMakeLocalCopyQuickFix - corrects error when applied on a function 

- Rubberduck.Parsing/VBA/RubberduckParserState.cs
- Rubberduck.VBEEditor/QualifiedModuleName.cs
- Rubberduck.VBEEditor/SafeComWrappers/Abstract/ICodeModule.cs
- Rubberduck.VBEEditor/SafeComWrappers/VB6/CodeModule.cs
- Rubberduck.VBEEditor/SafeComWrappers/VBA/CodeModule.cs
- RubberduckTests/Mocks/MockProjectBuilder.cs
This PR reintroduces computing the content hash of a component when creating a QMN for it. This is an attempt to deal with issue #3753. Removing the calculation of the content hash is the change from PR #3735 most probably causing the problems.
For some reason, the components acquired from the VBEAPI sometimes get removed by the VBE although our RCW is still holding a reference. This behaviour causes exceptions when later trying to access properties of the component. Apparently, one way to stabelize the component is to access its code module. Exactly this is guaranteed to happen when we compute the content hash of the module and save it to a public property. (This prevents the optimizer from removing the redundant code.)
> Reintroduce content hash on QMNs

- Rubberduck.VBEEditor/ComManagement/TypeLibs/TypeLibsSupport.cs
Background: the TypeLib API is only safe to access in the main thread, as the VBE maintains the type library in the main thread, and the exposed objects (ITypeLib/ITypeInfo) are not implemented with any built-in thread safety.
This PR replaces GetIUnknownForObject with GetIUnknownForObjectInContext to detect inappropriate threaded access to the TypeLib API, and throws an error in such a case.
> Detect inappropriate thread access to TypeLib API

- Rubberduck.Parsing/VBA/Attributes.cs
Fixes #3772 
The simple most fix for the issue, which is contained in commit one of this PR, is a two character change. (`_values` --> `Values` in `HasValue`)
However, to make `AttributeNodes` less confusing and prone to throw exceptions in case the constructor taking a context is used, I redesigned the class a bit.
> Fix for AttributeNode

- codecov.yml
Status checks for certain areas of the project are a cool idea in theory, the problem is that codecov apparently doesn't correctly report coverage for reports that apply to multiple flags.  
Long story short, this feature would've been nice if it worked, but it doesn't....
> remove flags from status checks

- Rubberduck.Parsing/Grammar/VBAParser.g4
- RubberduckTests/Grammar/VBAParserTests.cs
This requires an additional modification to endOfStatement to keep
consuming any "leading" whitespace for the following statement.
Fixes #3789
> Enforce ending NEWLINE on commentBody

- RetailCoder.VBE/UI/Command/ReparseCommand.cs
- RetailCoder.VBE/UI/RubberduckUI.Designer.cs
- RetailCoder.VBE/UI/RubberduckUI.de.resx
- RetailCoder.VBE/UI/RubberduckUI.resx
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.Parsing/VBA/ParserState.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
This PR introduces two new values in `ParserState`: `Started` and `UnexpectedError`.
`Started` gets set right after starting a parse, which makes it feel more responsive and prevents the user from requesting multiple parses by rapidly clicking the refresh button. (The `RequestParseCommand` is deactivated in this state.)
`UnexpactedError` gets set only whenever we encounter an unexpected exception while performing a parsing run. This indicates to the user that something has gone wrong they probably cannot do something about. (The `RequestParseCommand` is actiated in this state.)
I hope I did not forget anything that needed to get changed after adding the states. 
The french translation for the states is currenlty missing. 
Closes #3779
Closes #2816
> Add New ParserStates Started and UnexpectedError

- Rubberduck.VBEEditor/ComManagement/TypeLibs/TypeLibsAPI.cs
fix VBETypeLibsAPI_Object as exposed via Application.VBE.AddIns("Rubberduck.Extension").Object
broken since changes in PR #3783
> fix VBETypeLibsAPI_Object as exposed via AddIns("Rubberduck.Extension").Object

- RetailCoder.VBE/Rubberduck.csproj
- RetailCoder.VBE/UI/Command/ReparseCommand.cs
- RetailCoder.VBE/UI/Command/SettingsCommand.cs
- RetailCoder.VBE/UI/Inspections/InspectionResultsViewModel.cs
- RetailCoder.VBE/UI/RubberduckUI.Designer.cs
- RetailCoder.VBE/UI/RubberduckUI.resx
- RetailCoder.VBE/UI/Settings/GeneralSettingsViewModel.cs
- RetailCoder.VBE/UI/Settings/SettingsForm.cs
- RetailCoder.VBE/UI/ToDoItems/ToDoExplorerViewModel.cs
- RetailCoder.VBE/UI/UnitTesting/TestExplorerViewModel.cs
- RetailCoder.VBE/VBERuntime/IVBESettings.cs
- RetailCoder.VBE/VBERuntime/RegistryWrapper.cs
- RetailCoder.VBE/VBERuntime/VBESettings.cs
- RubberduckTests/RubberduckTests.csproj
- RubberduckTests/Settings/GeneralSettingsTests.cs
- RubberduckTests/TodoExplorer/TodoExplorerTests.cs
- RubberduckTests/VBE/VBESettingsTests.cs
Fixes #3807 
Introduces a new `VBESettings` class to provide some access to the VBE settings stored in the registry
Introduces a new `RegistryWrapper` class which aids testability for the registry operations; basically a stripped down version of the `Microsoft.Win32.Registry` static class.
Will now check that `Compile On Demand` is enabled during parsing and warn the user. Additionally, if the user enables the `Compile Before Parse` option via the general settings and the `Compile On Demand` is enabled, the user will be prompted whether they wish to update that. Unfortunately, it is necessary to restart to make the changes effective because in testing, VBE do not re-read the registry settings once it has loaded. As a consequence, a write to the registry will be inconsistent with what is …
> Compile before parse fix

- Rubberduck.Main/Root/RubberduckIoCInstaller.cs
Apparently some PR broke the IoC registration for inspections and quick fixes. Only `ParseTreeInspections` were registered correctly. Other inspections and all quick fixes were not registered at all or registered having service type of `Object`. This PR's purpose is to restore the functionality.
> Fixed inspections and quick fixes registration in Castle Windsor

- Rubberduck.Deployment/InnoSetup/Installer Build Script.iss
Closes #3884 
Considered prompting to delete but decided it's too much of a hassle and opted for the KISS route -- the settings will never be deleted. If they don't like it, they can clean it up manually. Besides, with per-machine install, I will never be able to track all users folder, so there's that....
> Remove user settings deletion

- Rubberduck.Inspections/Concrete/UnreachableCaseInspection/ParseTreeExpressionEvaluator.cs
- Rubberduck.Inspections/Concrete/UnreachableCaseInspection/ParseTreeValueVisitor.cs
- Rubberduck.Inspections/Concrete/UnreachableCaseInspection/RangeClauseFilter.cs
- Rubberduck.Inspections/Concrete/UnreachableCaseInspection/SelectCaseStmtContextWrapper.cs
- Rubberduck.Inspections/Concrete/UnreachableCaseInspection/UnreachableCaseInspection.cs
- RubberduckTests/Inspections/UnreachableCaseInspectionTests.cs
Follow-up work for remaining comments for merge  #3868 
1. Strengthened `SelectExpression `type evaluations. e.g., allows inspection of `SelectExpression `Type `Variant ` or other non-base-types if the CaseStatement Types represent a consistent inspectable type.
2. Added dirty-flag/caching to make `ToString()`/`GetHashCode` a more performant.
3. Retrieving integer division symbol from `VBAParser.DefaultVocabulary`.
4. Fixes bug: using the same variable name for different Select Case constructs, within the same module was not resolved properly.
5.  Fixes bug: `ParseTreeValueResults` were not cleared prior to additional invocations of the inspection.
There is more follow-up work to be done after v2.2.  Thought #1,4,5 above would be good to get into v2.2.
> 3868 comments

- Rubberduck.Deployment/InnoSetup/Installer Build Script.iss
Fixes #3916 
I considered adding a `/override` but decided against it as this means one more combination to test for what is already difficult to test project. Hopefully, simply checking for the admin is sufficient for the scenarios we need to support.
> Tighten down the requirement for elevation to only admins, not power users

- Rubberduck.Parsing/Binding/Bindings/IndexDefaultBinding.cs
- Rubberduck.Parsing/ComReflection/ReferencedDeclarationsCollector.cs
- RubberduckTests/Binding/IndexDefaultBindingTests.cs
This PR closes #3153
This PR deals with two issues regarding (indexed) default members:
1. We have not been able to resolve indexed default members accessed on index bindings, i.e. on results of function/property get calls, array accesses, or other indexed default members. This was covered up by wrong assumptions in the tests, which also had other problems in their setup. I corrected the tests, added new ones and amended the `IndexDefaultBinding` to make them all pass.
2. The `ReferencedDeclarationsCollector` had a tiny bug with the effect that the default members for classes from referenced libraries were never added to the corresponding class module declarations. I corrected that. Unfortunately this is untestable right now, since the `ReferencedDeclarationsCollector` is one big blob …
> Fixing indexed default members

- Rubberduck.Core/UnitTesting/IFakes.cs
- Rubberduck.Core/UnitTesting/TestEngine.cs
- Rubberduck.Main/ComClientLibrary/UnitTesting/FakesProviderFactory.cs
- Rubberduck.Main/Root/RubberduckIoCInstaller.cs
- Rubberduck.Main/Rubberduck.Main.csproj
- Rubberduck.VBEEditor/Utility/DisposalActionContainer.cs
- RubberduckTests/VBEditor/Utility/DisposalActionContainerTests.cs
This fixed part of the shutdown issue for me. However, there are two caveats.
1. I had to reset my settings in order to get a clean exit. So, there is probably something wrong with the new default settings loading, which did not work for me anyways. (I could not find the Case not reachable inspection in the inspections settings.)
2. After changing the inspections severity for one inspection in the settings window, I got an eternally hanging processes on shutdown in the debugger; no parse required. With this I mean that I had to kill VS to make it respond again to anything.  
The two points above require further investigation, but I think this PR is a step in the right direction.
> Inject a concrete factory for the FakesProvider

- Rubberduck.Parsing/Grammar/VBALexer.g4
- Rubberduck.Parsing/Grammar/VBAParser.g4
- RubberduckTests/Grammar/VBAParserTests.cs
This PR changes the parser and lexer to enable us to parse VB6 forms.
If there are more constructs that have to be added, we can add them once we find an example we cannot parse.
> Parsing vb forms

- Rubberduck.Deployment/InnoSetup/Installer Build Script.iss
Closes #3921 
I made some changes to the `RegisterAddIn()` function and in testing, the bug that was previously observed no longer exhibits and I am able to install as an admin and thus register the IDE for myself. However, I would appreciate others testing to verify it's not "just my computer" symptoms.
Pending: Update the messaging around admin not being able to register as they should no longer apply. Will remove after tests.
> Remove the restrictions on the admin elevation

- Rubberduck.Core/Refactorings/MoveCloserToUsage/MoveCloserToUsageRefactoring.cs
- RubberduckTests/QuickFixes/MoveFieldCloserToUsageQuickFixTests.cs
- RubberduckTests/Refactoring/MoveCloserToUsageTests.cs
Fixes #3964 
First line after insertion was given no indentation. This PR checks the indentation of the line prior to the insertion and adds padding so that the same indentation is preserved.
A reparse is also requested after the refactoring has completed.
> Move closer refactoring indent fix

- Rubberduck.Core/UnitTesting/TestMethod.cs
- Rubberduck.Core/UnitTesting/UnitTestUtils.cs
As above, should be a simple change to avoid using the VBA project name to identify the project when delving into the TypeLib API.
> UnitTests: Pass IVBProject rather than ambiguous project name to the TypeLib API

- Rubberduck.Core/UnitTesting/TestEngine.cs
fix to ensure ModuleInitialize etc is called in all VBA projects, even if the VBA project names are ambiguous.
> fix Run overload to handle ambiguous named VBA projects

- Rubberduck.Parsing/Rewriter/RewriterInfo/VariableRewriterInfoFinder.cs
- RubberduckTests/Refactoring/MoveCloserToUsageTests.cs
Fixes #3974 
Add special case where a variable declaration has a line number. Normally the declaration and following new line (end of statement) are removed which helps avoid a blank line being left behind. However, with a line number on the declaration the brings the code from the following line to the line with a line number. This can cause invalid code e.g. when the following line has a line number itself.
Incidentally, I can see unreachable code in the file VariableRewriterInfoFinder. The condition `if (blockStmtIndex == containingBlock.ChildCount)` doesn't make sense because it is comparing the (zero-based) index of an item to the number of items and it must always be less?
> Stop removing new line when removing an expression with a line number

- Rubberduck.Deployment/BuildRegistryScript.ps1
Fixes build error when building without the C++ build toll installed.
> Fixed assembly loading on fall back in deployment.

- Rubberduck.Deployment/Rubberduck.Deployment.csproj
Thanks to @Hosch250  for the nudge - the contributors no longer need to manually set the ExecutionPolicy just to build the deployment, removing a common build error and thus simplifying the setup for contributors.
> Simplify the ExecutionPolicy configuration in deployment

- Rubberduck.CodeAnalysis/Inspections/Concrete/EmptyModuleInspection.cs
- Rubberduck.Parsing/Grammar/VBAParser.g4
- Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs
- Rubberduck.Parsing/Symbols/IdentifierReferenceListener.cs
- Rubberduck.Parsing/VBA/COMReferenceSynchronizerBase.cs
- Rubberduck.VBEEditor/Events/VBENativeServices.cs
- RubberduckTests/Refactoring/RenameTests.cs
This PR closes #4056 
I took the third option outlined in the issue and it was much more straight forward than expected. Apparently, nothing was really using the separate contextx for the visibility.
I also improved the handling of com wrappers in `VBENativeServices`, which was leaking tons of wrappers. This had a positive effect on the com issues at the shutdown of RD, as far as I could judge in the debugger.
> Fix rename of UDTs

- Rubberduck.Parsing/Binding/Bindings/SimpleNameDefaultBinding.cs
- Rubberduck.Parsing/Grammar/VBAParser.g4
- RubberduckTests/Grammar/VBAParserTests.cs
Closes #4111 
There were a few issues:
1. Was using `ASSIGN` instead of `EQ`
2. Was using `lExpression` instead of `expression`
3. Was not referenced from `mainBlockStmt`
4. No tests
> Grammar - fix MID statement

- Rubberduck.Main/ComClientLibrary/Abstract/UnitTesting/IFakesProvider.cs
- Rubberduck.Main/ComClientLibrary/UnitTesting/FakeBase.cs
- Rubberduck.Main/ComClientLibrary/UnitTesting/Fakes/Date.cs
- Rubberduck.Main/ComClientLibrary/UnitTesting/Fakes/Now.cs
- Rubberduck.Main/ComClientLibrary/UnitTesting/Fakes/Time.cs
- Rubberduck.Main/ComClientLibrary/UnitTesting/FakesProvider.cs
- Rubberduck.Main/Rubberduck.Main.csproj
- RubberduckTests/IntegrationTests/FakeTests.bas
Adds fakes for the Now, Time and Date functions. Issue #2891 tracks the addition of each item.
Minor issue that integration test for passthrough of Time function could fail for 1 second out of every 24 hours (86 400 seconds). Not considered important enough to add complex logic to avoid this but let me know if this is needed.
> Add fakes for Now, Time and Date functions

- Rubberduck.Main/ComClientLibrary/UnitTesting/FakeBase.cs
- RubberduckTests/IntegrationTests/FakeTests.bas
Fixes #3720. Also seems to close #3721 
Using the ReturnsWhen method creates a ReturnValueInfo record with a Parameter set to a specific Argument. When calling TrackUsage with the actual arguments passed into the fake, it first calls TrySetReturnValue matching the specific parameter/argument combination. If that doesn't get a match, it then calls the other TrySetReturnValue method just to pick up any ReturnValueInfo record with the right invocation. However, that will pick up ReturnValueInfo records created with a ReturnsWhen call, even though the parameter is not matching.
To get around this, the second TrySetReturnValue method checks the ReturnValueInfo records for a Argument == string.Empty because that is how the Returns method creates the ReturnValueInfo record.
I'm unsure of using …
> Fix for 3720

- Rubberduck.Core/AutoComplete/AutoCompleteService.cs
- Rubberduck.Core/Properties/Settings.Designer.cs
- Rubberduck.Core/Properties/Settings.settings
- Rubberduck.Core/Settings/AutoCompleteSettings.cs
- Rubberduck.Core/UI/Settings/AutoCompleteSettings.xaml
- Rubberduck.Core/UI/Settings/AutoCompleteSettingsViewModel.cs
- Rubberduck.Core/app.config
- Rubberduck.Resources/Settings/AutoCompletesPage.Designer.cs
- Rubberduck.Resources/Settings/AutoCompletesPage.cs.resx
- Rubberduck.Resources/Settings/AutoCompletesPage.de.resx
- Rubberduck.Resources/Settings/AutoCompletesPage.fr.resx
- Rubberduck.Resources/Settings/AutoCompletesPage.resx
- Rubberduck.VBEditor.VBA/SafeComWrappers/VB/CodeModule.cs
When ENTER is pressed and the caret is inside a string literal, e.g.:
sql = "SELECT Foo, Bar |"
Vanilla VBE does this:
sql = "SELECT Foo, Bar "
|"
Rubberduck does this:
sql = "SELECT Foo, Bar " & _
"|"
> implemented smart-concat

- Rubberduck.Parsing/Rubberduck.Parsing.csproj
- Rubberduck.Parsing/VBA/VBACodeStringParser.cs
- RubberduckTests/Parsing/VBACodeStringParserTests.cs
- RubberduckTests/RubberduckTests.csproj
The parser is meant to support scenarios where we need to work with code that are still up in the air. The parser is totally disconnected from the main parser and takes in a `string` that only needs to represent a minimally valid code module body and builds a valid parse tree. 
This can be used for example, in code preview, so that rewriting can be handled using the rewriter API for example.
> Introduce CodeStringParser

- Rubberduck.Parsing/ComReflection/ComAlias.cs
- Rubberduck.Parsing/ComReflection/ComBase.cs
- Rubberduck.Parsing/ComReflection/ComCoClass.cs
- Rubberduck.Parsing/ComReflection/ComDocumentation.cs
- Rubberduck.Parsing/ComReflection/ComEnumeration.cs
- Rubberduck.Parsing/ComReflection/ComEnumerationMember.cs
- Rubberduck.Parsing/ComReflection/ComField.cs
- Rubberduck.Parsing/ComReflection/ComInterface.cs
- Rubberduck.Parsing/ComReflection/ComMember.cs
- Rubberduck.Parsing/ComReflection/ComModule.cs
- Rubberduck.Parsing/ComReflection/ComParameter.cs
- Rubberduck.Parsing/ComReflection/ComProject.cs
- Rubberduck.Parsing/ComReflection/ComStruct.cs
- Rubberduck.Parsing/ComReflection/ComType.cs
- Rubberduck.Parsing/ComReflection/ComVariant.cs
- Rubberduck.Parsing/ComReflection/ReferencedDeclarationsCollector.cs
- Rubberduck.Parsing/ComReflection/XmlPersistableDeclarations.cs
I don't have VB6 installed yet, so this is untested there. If anything this would fix things and not break them though.
For future reference, the problem is that when caching was added to more types it was under the assumption that everything would have a Guid. This **_should only be assumed to be true of interfaces and coclasses_** (required, I believe), and I'm not 100% sure about the coclasses.
> Fixes ComReflection regression

- RubberduckTests/Binding/MemberAccessTypeBindingTests.cs
- RubberduckTests/Binding/SimpleNameDefaultBindingTests.cs
- RubberduckTests/Binding/SimpleNameTypeBindingTests.cs
- RubberduckTests/Inspections/MemberNotOnInterfaceInspectionTests.cs
- RubberduckTests/Inspections/ShadowedDeclarationInspectionTests.cs
- RubberduckTests/Inspections/SheetAccessedUsingStringInspectionTests.cs
- RubberduckTests/Mocks/MockProjectBuilder.cs
- RubberduckTests/Symbols/DeclarationFinderTests.cs
I made the major and minor reference mandatory in `MockProjectBuilder.AddReference`. 
The problem with this is that it is not abvious that you have to provide them when referencing a library in tests. In paricular, there have been two tests referencing the Excel object model, where the major version `1` and minor version `8` had not been provided.
Before, the versions simply defaulted to `0`, which is not too helpful.
I would like to add that I am not too happy with the current design since it is possible to reference other projects that do not have a version number, e.g. other Excel workbooks.
> Mandatory Major and Minor Version when addin References in Tests

- Rubberduck.Deployment/BuildRegistryScript.ps1
- Rubberduck.Deployment/Rubberduck.Deployment.csproj
- Rubberduck.Interaction/Rubberduck.Interaction.csproj
- Rubberduck.Refactorings/Rubberduck.Refactorings.csproj
- Rubberduck.Resources/Rubberduck.Resources.csproj
Thanks to @rkapka for the assistance - there is an issue with space in the path for powershell script. This PR fixes the issue and also fixes the issue with MIDL which is uh, *weird* about backslash in the path (and it doesn't want to take a full path but a directory and file name separately). 
Since I was mucking in the script, I took liberty of adding auto-deletions of previous debug registration scripts with hard-coded for 10 files. 
I also noticed that newer project did not have the analyzer referenced so I added them as well.
> Deployment bug fixes & Analyzer for new projects

- Rubberduck.CodeAnalysis/Inspections/Concrete/MultilineParameterInspection.cs
Closes #3655 
Use GetText method instead of ToString so that the parameter name is picked up correctly.
> Fix issue 3655

- Rubberduck.Parsing/ComReflection/ReferencedDeclarationsCollector.cs
- RubberduckTests/Inspections/ApplicationWorksheetFunctionInspectionTests.cs
- RubberduckTests/Inspections/HostSpecificExpressionInspectionTests.cs
- RubberduckTests/Inspections/ImplicitActiveSheetReferenceInspectionTests.cs
- RubberduckTests/Inspections/ImplicitActiveWorkbookReferenceInspectionTests.cs
- RubberduckTests/Inspections/MemberNotOnInterfaceInspectionTests.cs
- RubberduckTests/Inspections/ObjectVariableNotSetInspectionTests.cs
- RubberduckTests/Inspections/SheetAccessedUsingStringInspectionTests.cs
- RubberduckTests/Mocks/MockParser.cs
- RubberduckTests/Mocks/MockVbeBuilder.cs
- RubberduckTests/QuickFixes/AccessSheetUsingCodeNameQuickFixTests.cs
- RubberduckTests/QuickFixes/ApplicationWorksheetFunctionQuickFixTests.cs
- RubberduckTests/QuickFixes/IgnoreOnceQuickFixTests.cs
- RubberduckTests/Refactoring/RenameTests.cs
- RubberduckTests/Symbols/DeclarationFinderTests.cs
This PR closes #4182 
Moreover, the fix makes `MockParser.AddTestLibrary` obsolete since the parsing process will pick up all serialized declarations from referenced projects. Acordingly, I removed it along with all uses.
This had a good effect on test execution times.
> Fix loading serialized declarations from non standard path

- Rubberduck.API/VBA/Parser.cs
- Rubberduck.Main/Root/RubberduckIoCInstaller.cs
- Rubberduck.Parsing/VBA/Parsing/ModuleParser.cs
- Rubberduck.VBEEditor/Rubberduck.VBEditor.csproj
- Rubberduck.VBEEditor/SafeComWrappers/VB/Abstract/IVBComponent.cs
- Rubberduck.VBEEditor/SafeComWrappers/VB/Abstract/IVBE.cs
- Rubberduck.VBEEditor/SourceCodeHandling/CodePaneSourceCodeHandler.cs
- Rubberduck.VBEEditor/SourceCodeHandling/ITempSourceFileHandler.cs
- Rubberduck.VBEEditor/SourceCodeHandling/SourceFileHandlerSourceCodeHandlerAdapter.cs
- Rubberduck.VBEditor.VB6/ExternalFileTempSourceFileHandlerEmulator.cs
- Rubberduck.VBEditor.VB6/Rubberduck.VBEditor.VB6.csproj
- Rubberduck.VBEditor.VB6/SafeComWrappers/VB/VBComponent.cs
- Rubberduck.VBEditor.VB6/SafeComWrappers/VB/VBE.cs
- Rubberduck.VBEditor.VB6/TempSourceFileHandler.cs
- Rubberduck.VBEditor.VBA/Rubberduck.VBEditor.VBA.csproj
- Rubberduck.VBEditor.VBA/SafeComWrappers/VB/VBComponent.cs
- Rubberduck.VBEditor.VBA/SafeComWrappers/VB/VBE.cs
- Rubberduck.VBEditor.VBA/TempSourceFileHandler.cs
- RubberduckTests/IoCContainer/IoCRegistrationTests.cs
- RubberduckTests/IoCContainer/IoCResolvingTests.cs
This PR adds some more safety in the `ISourceFileHandler` (now `ITempSourceFileHandler`) around reading the files. I chose to rename the interface and the implementations to convey that they are not to be used to handle permanent exports and imports. 
I also ensured that the `ISourceCodeHandler` implementations never retun `null` and made the attributes passs use the file exported by the VBE or documant modules in order to allow getting the attributes.
> More safety around handling the temp files in the parser

- Rubberduck.VBEEditor/Rubberduck.VBEditor.csproj
- Rubberduck.VBEEditor/SafeComWrappers/Abstract/IComIndexedProperty.cs
- Rubberduck.VBEEditor/SafeComWrappers/Abstract/IEventSource.cs
- Rubberduck.VBEEditor/SafeComWrappers/SafeRedirectedEventedComWrapper.cs
- Rubberduck.VBEEditor/SafeComWrappers/VB/Abstract/ICommandBarButtonEvents.cs
- Rubberduck.VBEEditor/SafeComWrappers/VB/Abstract/ICommandBarEvents.cs
- Rubberduck.VBEEditor/SafeComWrappers/VB/Abstract/IEvents.cs
- Rubberduck.VBEEditor/SafeComWrappers/VB/Abstract/IVBE.cs
- Rubberduck.VBEditor.VB6/Rubberduck.VBEditor.VB6.csproj
- Rubberduck.VBEditor.VB6/SafeComWrappers/Office/CommandBarButton.cs
- Rubberduck.VBEditor.VB6/SafeComWrappers/VB/CommandBarButtonEvents.cs
- Rubberduck.VBEditor.VB6/SafeComWrappers/VB/CommandBarEvents.cs
- Rubberduck.VBEditor.VB6/SafeComWrappers/VB/Events.cs
- Rubberduck.VBEditor.VB6/SafeComWrappers/VB/VBE.cs
- Rubberduck.VBEditor.VBA/SafeComWrappers/Office/CommandBarButton.cs
- Rubberduck.VBEditor.VBA/SafeComWrappers/VB/VBE.cs
Closes #3949 
OK, so technically it's an event *source* that was (perhaps) leaking... but I just couldn't resist that PR title.
This PR addresses an item of technical debt spotted during PR #3935. For expediency at the time, VB6 events for CommandBarButtons were hooked up using chained access to raw RCW objects. This was entirely due to the unpleasant way that older Office libraries (such as the v8 that VB6 uses) modelled button click events.
To remediate, I've created some new SafeComWrappers for CommandBarEvents. These are then used to safely pass the correct RCW into a refactored SafeRedirectedEventComWrapper base class. ~~Note that as we have no need for any of this on the VBA side, the relevant property just throws NotSupportedException. I think this is valid, as its something that …
> Fix the leaky (event) sink!

- Rubberduck.VBEEditor/SafeComWrappers/Abstract/HostApplicationBase.cs
This PR tries te address #4283.
Tha hacky solution is to castch the `InvalidCastException`, log it and use `null` as target. Currently, we only ever use the application name anyway, which is saved independently of the underlying COM object.
> Dirty hack to not blow up for hosts with unexpected COM setups

- Rubberduck.Main/Root/RubberduckIoCInstaller.cs
- Rubberduck.VBEditor.VB6/SafeComWrappers/VB/AddIn.cs
Closes #4280.
This is just a quick hack to remove the Forms context menu from VB6 RD. I'll open another issue to put back the menu, which will need some thought as to how best to hook the form designer load event and attach the menu at the right time.
F5'd in VB6 and VBA to make sure no other menus affected. Tested all project types and tried cancelling the dialog - all work now.
> Quick hack to fix VB6 crash on certain project types

- Rubberduck.Parsing/Grammar/VBAParser.g4
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
- RubberduckTests/Grammar/VBAParserTests.cs
Fixes #4302
Also added missing using to fix `next`
> Grammar tweak for indexed properties in form header

- Rubberduck.Core/CodeAnalysis/CodeMetrics/CodeMetricsViewModel.cs
- Rubberduck.Core/Navigation/CodeExplorer/CodeExplorerItemViewModel.cs
- Rubberduck.Core/Navigation/CodeExplorer/CodeExplorerProjectViewModel.cs
- Rubberduck.Core/Navigation/CodeExplorer/CodeExplorerViewModel.cs
- Rubberduck.Core/Rubberduck.Core.csproj
- Rubberduck.Core/UI/CodeExplorer/CodeExplorerControl.xaml
- Rubberduck.Core/UI/CodeExplorer/Commands/AddComponentCommand.cs
- Rubberduck.Core/UI/CodeExplorer/Commands/AddMDIFormCommand.cs
- Rubberduck.Core/UI/CodeExplorer/Commands/SetAsStartupProjectCommand.cs
- Rubberduck.Resources/CodeExplorer/CodeExplorerUI.Designer.cs
- Rubberduck.Resources/CodeExplorer/CodeExplorerUI.resx
- Rubberduck.VBEEditor/SafeComWrappers/VB/Abstract/IVBProjects.cs
- Rubberduck.VBEditor.VB6/SafeComWrappers/VB/VBProject.cs
- Rubberduck.VBEditor.VB6/SafeComWrappers/VB/VBProjects.cs
- Rubberduck.VBEditor.VBA/SafeComWrappers/VB/VBProjects.cs
Closes #4305.
This PR adds a menu entry to VB6 RD Code Explorer to Set as startup.
- Only enabled when more than 1 project in the session, and the node's project is not already set as startup
- Indicates the current start up project by bolding the project node (as per PE)
Not visible to VBA,
Also fixed a couple of RCW leaks with AddCommands
> VB6: Set as start up project

- Rubberduck.CodeAnalysis/QuickFixes/RemoveDuplicatedAnnotationQuickFix.cs
- Rubberduck.Parsing/Grammar/VBAParser.g4
- Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs
- RubberduckTests/Annotations/DeclarationsListenerAnnotationsTests.cs
- RubberduckTests/RubberduckTests.csproj
This PR changes two points regarding how the `DeclarationSymbolsListener` finds annotations:
1. It is now able to find member annotations even if these are line-continued. Previously, it was expecting at least one annotation per physical line, not logical line.
2. The determination of the declaration section is no longer delegated to the VBE. Now, it ends on the first line above the member annotations of the first module body element, i.e. on the first physical line above the block of consecutive logical lines right above the first module body element.
> Fix module annotation recognition

- Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ExpressionFilterFactory.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/LetCoerce.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ParseTreeExpressionEvaluator.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ParseTreeValue.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/TypeTokenPair.cs
- RubberduckTests/Inspections/UnreachableCase/ExpressionFilterUnitTests.cs
- RubberduckTests/Inspections/UnreachableCase/ParseTreeExpressionEvaluatorUnitTests.cs
- RubberduckTests/Mocks/MockVbeBuilder.cs
- RubberduckTests/UnitTesting/EngineTests.cs
This PR closes #4397 
I added `CultureInfo.InvariantCulrure` in a lot of `ToString`, `Parse` and `TryParse` calls, primarily in the `LetCoercer`.
Moreover, I performed some style adjustment regarding anonymous functions. 
Finally, I set up `IsInDesignMode` on the mock VBE as `true` in order to make the test engine tests pass that where previously inconclusive.
> Fix URC inspection for international users

- Rubberduck.Parsing/Rubberduck.Parsing.csproj
- Rubberduck.Parsing/VBA/ComReferenceLoading/COMReferenceSynchronizerBase.cs
- Rubberduck.Parsing/VBA/ComReferenceLoading/ICOMReferenceSynchronizer.cs
- Rubberduck.Parsing/VBA/Extensions/DictionaryExtensions.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.Parsing/VBA/ParsingStageService.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
This PR closes #3300.
So far, the logic which references to unload was seriously borked resulting in never unloading anything. 
Moreover, we never considered that priority changes could invalidate references. 
Both problems get fixed via this PR.
> Refresh references on project priority change

- Rubberduck.CodeAnalysis/CodePathAnalysis/Walker.cs
Use of `default` was keeping me from building.
> Revert use of 'default' language feature to lower c# version

- Rubberduck.VBEditor.VB6/SafeComWrappers/Office/CommandBarButton.cs
- Rubberduck.VBEditor.VBA/SafeComWrappers/Office/CommandBarButton.cs
This tiny PR fixes the rewrapping of `CommandBarButton`s that caused the corresponding RCWs to be released twice instead of once.
> Fix rewrapping of CommandBarButtons as CommandBarControls

- Rubberduck.VBEEditor/QualifiedModuleName.cs
Calculating the content hash of the module on creation of a QMN is actively hurting their usability in hot-paths. The content hash was not really used and only was left there because it seemed to prevent some strange behaviour of COM components. Testing, I did no longer run into the strange behaviour. So, I think it is prudent to remove the content hash.
> Remove content hash from the QMN

- Rubberduck.Core/AutoComplete/Service/SelfClosingPairCompletionService.cs
- Rubberduck.VBEEditor/SourceCodeHandling/CodePaneSourceCodeHandler.cs
- RubberduckTests/AutoComplete/CodePaneHandlerTests.cs
- RubberduckTests/AutoComplete/SelfClosingPairCompletionTests.cs
SCP was missing a case where caret was located before the first non-whitespace character of a code line.
```vb
| foo
```
Given input `"`, the above now produces the expected result:
```vb
"|" foo
```
> SCP hotfix

- Rubberduck.Parsing/Symbols/Declaration.cs
Closes #3038 
The PR changes the storage from `ConcurrentBag` to `ConcurrentDictionary` and adds a check to remove references for a declaration, which fixes the issues where count of references is incorrect.
It was originally reported that `ConcurrentDictionary` caused unit tests to fail. However, in the intervening time, we have had changed our unit tests and it now passes without problem.
> Fix references count

- Rubberduck.CodeAnalysis/CodePathAnalysis/Extensions/NodeExtensions.cs
- Rubberduck.CodeAnalysis/CodePathAnalysis/Nodes/Abstract/NodeBase.cs
- Rubberduck.CodeAnalysis/CodePathAnalysis/Nodes/INode.cs
- Rubberduck.CodeAnalysis/CodePathAnalysis/Nodes/Implementations/AssignmentNode.cs
- Rubberduck.CodeAnalysis/CodePathAnalysis/Nodes/Implementations/BlockNode.cs
- Rubberduck.CodeAnalysis/CodePathAnalysis/Nodes/Implementations/BranchNode.cs
- Rubberduck.CodeAnalysis/CodePathAnalysis/Nodes/Implementations/DeclarationNode.cs
- Rubberduck.CodeAnalysis/CodePathAnalysis/Nodes/Implementations/GenericNode.cs
- Rubberduck.CodeAnalysis/CodePathAnalysis/Nodes/Implementations/LoopNode.cs
- Rubberduck.CodeAnalysis/CodePathAnalysis/Nodes/Implementations/ReferenceNode.cs
- Rubberduck.CodeAnalysis/CodePathAnalysis/Walker.cs
- Rubberduck.CodeAnalysis/Inspections/Abstract/MemberAccessMayReturnNothingInspectionBase.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/AssignmentNotUsedInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/MemberAccessMayReturnNothingInspection/ExcelMemberMayReturnNothingInspection.cs
- Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs
- Rubberduck.Resources/Inspections/InspectionInfo.resx
- Rubberduck.Resources/Inspections/InspectionNames.Designer.cs
- Rubberduck.Resources/Inspections/InspectionNames.resx
- Rubberduck.Resources/Inspections/InspectionResults.Designer.cs
- Rubberduck.Resources/Inspections/InspectionResults.resx
- Rubberduck.Resources/Rubberduck.Resources.csproj
- Rubberduck.Resources/Settings/AutoCompletesPage.Designer.cs
- Rubberduck.Resources/Settings/SettingsUI.Designer.cs
- RubberduckTests/Inspections/ExcelMemberMayReturnNothingInspectionTests.cs
This also unscrews the csproj that was preventing the resx files from generating the designers.
Note that the members being inspected are not intended to be an exhaustive list at this point.
> Add Inspection for members that can return Nothing. Ref #4440

- Rubberduck.CodeAnalysis/Inspections/Concrete/AssignmentNotUsedInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/FunctionReturnValueNotUsedInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/UnassignedVariableUsageInspection.cs
- Rubberduck.Core/UI/Refactorings/ExtractInterface/ExtractInterfaceView.xaml
- Rubberduck.Core/UI/Refactorings/ExtractInterface/InterfaceMemberViewModel.cs
- RubberduckTests/Inspections/AssignmentNotUsedInspectionTests.cs
- RubberduckTests/Inspections/FunctionReturnValueNotUsedInspectionTests.cs
- RubberduckTests/Inspections/UnassignedVariableUsageInspectionTests.cs
- RubberduckTests/QuickFixes/ConvertToProcedureQuickFixTests.cs
- `UnassignedVariableUsage` and `AssignmentNotUsed` inspections now ignore arrays
- `FunctionReturnValueNotUsed` ignores otherwise unused functions
> Misc. bugfixes

- Rubberduck.Parsing/VBA/DeclarationCaching/DeclarationFinder.cs
- RubberduckTests/Refactoring/RenameTests.cs
Resolves #4349.  Removes Enums/UDTs rename conflict detection false-positive.
Added a failing repro test for last reported false-positive and some tweaks to the VBA input code for prior #4349 tests.
> Fixes 4349...take two

- Rubberduck.Deployment/Rubberduck.Deployment.csproj
Due to how nuget changed how they cache packages and that they are now external to the solution folder, it is possible to have case where the package isn't present within the solution and therefore we would fail to build. This PR now will check in 2 different places.
Note: this is really a hack since the Right Way Of Doing Things isn't supported. Ref: https://github.com/NuGet/Home/issues/4837
> Add a check for easy hook's nuget package from nuget cache

- Rubberduck.Core/UI/Command/FindAllImplementationsCommand.cs
- Rubberduck.Core/UI/Command/FindAllReferencesCommand.cs
Appends ` (get)`, ` (let)`, or ` (set)` to the identifier name when the target declaration is a property.
> Include property accessor type in the "search results" tab

- Rubberduck.CodeAnalysis/QuickFixes/IgnoreOnceQuickFix.cs
- Rubberduck.Parsing/Grammar/VBAParser.g4
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
- RubberduckTests/QuickFixes/IgnoreOnceQuickFixTests.cs
Closes #4579.
Priviously, the quickfix assumed implicitly that it worked on something inside a module. Moreover, it did not use the right annotation for module annotations. 
In addition, the quickfix now honors the indentation.
> Rewrite ignore once quickfix

- Rubberduck.CodeAnalysis/Inspections/Concrete/IllegalAnnotationInspection.cs
- RubberduckTests/Inspections/IllegalAnnotationsInspectionTests.cs
These annotation can be placed anywhere and do not necessarily bind to a declaration or identifier reference.
Closes  #4594
> Always deem annotations with GeneralAnnotation flag legal

- Rubberduck.CodeAnalysis/Inspections/Concrete/VariableRequiresSetAssignmentEvaluator.cs
- Rubberduck.Parsing/VBA/DeclarationCaching/DeclarationFinder.cs
- RubberduckTests/Inspections/ObjectVariableNotSetInspectionTests.cs
- RubberduckTests/QuickFixes/UseSetKeywordForObjectAssignmentQuickFixTests.cs
Closes #4037
Closes #4318
This PR should remove next to all false-positives for the `ObjectVariableNotSetInspection` not connected to indexed default member accesses. 
I opted not to err on the safe side for `NewExpr` because the legitimate cases are very rare and having false-negatives for simple qualified type expressions is worse from my point of view.  
A real fix is pending the implementation of an expression type derivation engine.
> Fix for variable not set inspection

- Rubberduck.CodeAnalysis/Inspections/Concrete/AttributeValueOutOfSyncInspection.cs
- Rubberduck.CodeAnalysis/QuickFixes/AdjustAttributeValuesQuickFix.cs
- Rubberduck.Core/Properties/Settings.Designer.cs
- Rubberduck.Core/Properties/Settings.settings
- Rubberduck.Core/app.config
- Rubberduck.Parsing/Annotations/AnnotationType.cs
- Rubberduck.Parsing/Annotations/ModuleAttributeAnnotation.cs
- Rubberduck.Parsing/Symbols/Attributes.cs
- Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs
- Rubberduck.Resources/Inspections/InspectionInfo.de.resx
- Rubberduck.Resources/Inspections/InspectionInfo.resx
- Rubberduck.Resources/Inspections/InspectionNames.Designer.cs
- Rubberduck.Resources/Inspections/InspectionNames.de.resx
- Rubberduck.Resources/Inspections/InspectionNames.resx
- Rubberduck.Resources/Inspections/InspectionResults.Designer.cs
- Rubberduck.Resources/Inspections/InspectionResults.de.resx
- Rubberduck.Resources/Inspections/InspectionResults.resx
- Rubberduck.Resources/Inspections/QuickFixes.Designer.cs
- Rubberduck.Resources/Inspections/QuickFixes.de.resx
- Rubberduck.Resources/Inspections/QuickFixes.resx
- RubberduckTests/Inspections/AttributeValueOutOfSyncInspectionTests.cs
- RubberduckTests/QuickFixes/AdjustAttributeValuesQuickFixTests.cs
This PR is the next step after PR #4641 and based on that PR.
This PR introduces the new `AttributeValueOutOfSyncInspection` along with the corresponding `AdjustAttributeValuesQuickFix`.
The inspection finds all instances of attribute annotations for which there is a corresponding attribute, but the value(s) do not match. So, it covers the empty spot of the `MissingAttributeInspection`. In particular, it deals with the `@PredeclaredId` and `@Exposed` annotations for which the corresponding attribute always exists in class modules.
The `AdjustAttributeValuesQuickFix` does exactly what the name suggests. 
I verified that this works in the VBE using the example of the `@PredeclaredId` annotation.
> Attribute value out of sync inspection

- Rubberduck.CodeAnalysis/CodePathAnalysis/Walker.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/AssignmentNotUsedInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/ModuleWithoutFolderInspection.cs
- RubberduckTests/Inspections/ModuleWithoutFolderInspectionTests.cs
These are the last two commits from PR #4686
I have extracted them because they fix two small unrelated issues whose fix should go into the next release.
This PR closes #4653
The problem was that the `AssignmentNotUsedInspection also considered module variable, whose `ParentScopingDeclaration` is a module declaration and, thus, has a `null` context.
Now, member variables are no longer considered because the inspection only seems to make sense for local variables.
This PR also makes the `MissingFolderAnnotationInspection` actually ignore modules with an `@IgnoreModule` annotation for this inspection.
> Some small fixes from 4686

- Rubberduck.CodeAnalysis/QuickFixes/IQuickFixFailureNotifier.cs
- Rubberduck.CodeAnalysis/QuickFixes/QuickFixFailureNotifier.cs
- Rubberduck.CodeAnalysis/QuickFixes/QuickFixProvider.cs
- Rubberduck.Interaction/Input/IMessageBox.cs
- Rubberduck.Parsing/Rewriter/IRewriteSession.cs
- Rubberduck.Parsing/Rewriter/RewriteSessionBase.cs
- Rubberduck.Parsing/Rewriter/RewritingManager.cs
- Rubberduck.Resources/Inspections/QuickFixes.Designer.cs
- Rubberduck.Resources/Inspections/QuickFixes.de.resx
- Rubberduck.Resources/Inspections/QuickFixes.resx
- RubberduckTests/QuickFixes/QuickFixProviderTests.cs
- RubberduckTests/Rewriter/AttributesRewriteSessionTests.cs
- RubberduckTests/Rewriter/CodePaneRewriteSessionTests.cs
- RubberduckTests/Rewriter/RewriteManagerTests.cs
- RubberduckTests/Rewriter/RewriteSessionTestBase.cs
This PR closes  #4688
After this PR, whenever a rewrite session checks out a rewriter that is already dirt, i.e. whose underlying parse tree is stale, the rewrite session invalidates itself. This causes any subsequent call to `TryRewrite` to fail.
In order to communicate the reason for the failure better, I changed the boolean property `IsInvalidated` to a property `Status` returning an enum value. This property can be set once to another value than `Valid` in order to invalidate the rewriter. Afterwards, all attempts to set the property are ignored. Thus, for any invalid session it shows the original reason for the invalidation.
Using this information, I added a notification mechanism to the `QuickFixProvider` informing about any failure to apply a rewriter. Currently, onlyfor a failure …
> Stop rewriting dirty modules

- Rubberduck.CodeAnalysis/Inspections/Abstract/InspectionBase.cs
- Rubberduck.CodeAnalysis/Inspections/Abstract/InspectionResultBase.cs
- Rubberduck.CodeAnalysis/Inspections/Results/DeclarationInspectionResult.cs
- Rubberduck.CodeAnalysis/Inspections/Results/IdentifierReferenceInspectionResult.cs
- Rubberduck.CodeAnalysis/Inspections/Results/QualifiedContextInspectionResult.cs
- Rubberduck.Core/UI/Inspections/AggregateInspectionResult.cs
- Rubberduck.Core/UI/Inspections/InspectionResultsViewModel.cs
- Rubberduck.Parsing/Inspections/Abstract/IInspection.cs
- Rubberduck.Parsing/Inspections/Abstract/IInspectionResult.cs
- RubberduckTests/Inspections/InspectionResultTests.cs
This PR closes #2023
This PR introduces the base framework for inspection result invalidation. Each inspection result now has a member `ChangedInvalidateResult` taking the modified modules and returning whether the result got invalidated by the changes. 
The base implementation checks whether the module on the inspection result got modified. If not, it asks the inspection whether it thinks that the result is stale. `DeclarationInspectionResults` and `IdentifierInspectionResults` also take the module of the corresponding declaraion into account. `AggregateInspectionResults` are always considered stale as there is no information about the contents.
For the inspections, the check whether a result is stale defaults to true. If anything else is desired, the corresponding virtual method on …
> Invalidate inspection results after parsing

- Rubberduck.CodeAnalysis/Inspections/Concrete/ProcedureCanBeWrittenAsFunctionInspection.cs
- RubberduckTests/Inspections/ProcedureShouldBeFunctionInspectionTests.cs
Closes #4655 
Added `TryGetValue()` where the inspection accessed a dictionary using the key without verification checks.  Since I could not determine a specific use case that caused the missing key issue, adding protection to accessing the dictionary may be all that is/was needed to clear the issue.
> 4655 key not found exception

- Rubberduck.Main/Extension.cs
- Rubberduck.SettingsProvider/XmlPersistanceService.cs
- RubberduckTests/Settings/GeneralSettingsTests.cs
Closes #4694 
Closes #4668
Also adds an unit test to prove that the default settings will be loaded even if the file is missing. Also, the `InitializeAddIn` is now completely wrapped in the try/catch to ensure that if exception are thrown anywhere else, we will get an error message and logs rather than just silently loading a non-working instance.
> Fixes 4964 (installing with no menu showing)

- Rubberduck.CodeAnalysis/Inspections/Concrete/NonReturningFunctionInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/ParameterCanBeByValInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/UnassignedVariableUsageInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/VariableNotAssignedInspection.cs
- Rubberduck.Parsing/VBA/DeclarationCaching/DeclarationFinder.cs
- RubberduckTests/Inspections/ParameterCanBeByValInspectionTests.cs
- RubberduckTests/Symbols/DeclarationFinderTests.cs
This PR closes #4719.
This is a redesign of the `ParameterCanBeByValInspection`, which was implemented in a confusing way.
Now, the parts for interfaces and events use the same base logic to determin whether a parameter of an individual member could be passed by value. This logic also has been redesigned heavily. Now, it really looks at the references to the parameter and evaluates whether these references correspond to assignments or ByRef parameters.
This PR also fixes that the inspection ignored that in VBA an implemented interface can have an implementation of its own.
> Fix ParameterCanBeByValInspection

- Rubberduck.Resources/Templates.cs.resx
- Rubberduck.Resources/Templates.fr.resx
Both Czech and French has a resource in template that wasn't meant to be localized. The PR removes it.
> Remove the non-localizable resources

- Rubberduck.Core/Navigation/CodeExplorer/CodeExplorerViewModel.cs
- Rubberduck.Resources/Inspections/InspectionNames.de.resx
- Rubberduck.Resources/Inspections/InspectionNames.resx
- RubberduckTests/Inspections/GeneralInspectionTests.cs
Distinguish between IsMissing inspection names (closes #4740).
This also tweaks the expansion of nodes in the CE to not expand on single-click.
> Last minute fixes.

- Rubberduck.Core/UI/AddRemoveReferences/AddRemoveReferencesModel.cs
- Rubberduck.Core/UI/AddRemoveReferences/AddRemoveReferencesPresenterFactory.cs
- Rubberduck.Core/UI/AddRemoveReferences/AddRemoveReferencesViewModel.cs
- RubberduckTests/AddRemoveReferences/AddRemoveReferencesSetup.cs
- RubberduckTests/AddRemoveReferences/AddRemoveReferencesViewModelTests.cs
Force a reparse on Apply - this apparently wasn't propagating the VBE events because the dialog is modal.
> Fix regression on Add/Remove References Apply.

- Rubberduck.VBEEditor/Utility/ISelectionService.cs
- Rubberduck.VBEEditor/Utility/SelectionService.cs
- RubberduckTests/VBEditor/Utility/SelectionServiceTests.cs
This service provides access to the active selection and selection of individual modules without involving COM wrappers directly; the interface only uses QMNs and selections.
It is currently not used anywhere. Future PRs might change that.
> Introduce the ISelectionService

- RubberduckTests/Mocks/MockProjectBuilder.cs
- RubberduckTests/Mocks/MockVbeBuilder.cs
- RubberduckTests/Refactoring/Rename/RenameTestExecution.cs
- RubberduckTests/Refactoring/Rename/RenameTests.cs
The mock setup has been broken in the refactoring dialog PR #4072.
The rename test setup never used the UseLibraries property. Thus, tests relying on it failed.
> Fix mock setup and rename test setup

- Rubberduck.Parsing/Grammar/VBAParser.g4
- RubberduckTests/Grammar/VBAParserTests.cs
The grammar has the following for module config properties
```
BEGINPROPERTY whiteSpace unrestrictedIdentifier (LPAREN numberLiteral RPAREN)? (whiteSpace GUIDLITERAL)? endOfStatement
(moduleConfigProperty | moduleConfigElement)*
ENDPROPERTY endOfStatement
```
However, I have found a valid VB6 source file that contains the following
```
BeginProperty Panels {8E3867A5-8586-11D1-B16A-00C0F0283628} 
NumPanels       =   1
BeginProperty Panel1 {8E3867AB-8586-11D1-B16A-00C0F0283628} 
EndProperty
EndProperty
```
I have modified the grammar to expect zero or more config properties or config elements.
> Grammar cannot handle an empty moduleConfigProperty

- Rubberduck.CodeAnalysis/Inspections/Concrete/ThunderCode/KeywordsUsedAsMemberInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/ThunderCode/LineContinuationBetweenKeywordsInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/ThunderCode/NegativeLineNumberInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/ThunderCode/NonBreakingSpaceIdentifierInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/ThunderCode/OnErrorGoToMinusOneInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/ThunderCode/ThunderCodeFormatExtension.cs
- Rubberduck.Parsing/Grammar/VBALexer.g4
- Rubberduck.Parsing/Grammar/VBAParser.g4
- Rubberduck.Resources/CodeExplorer/CodeExplorerUI.Designer.cs
- Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs
- Rubberduck.Resources/Inspections/InspectionInfo.resx
- Rubberduck.Resources/Inspections/InspectionNames.Designer.cs
- Rubberduck.Resources/Inspections/InspectionNames.resx
- Rubberduck.Resources/Inspections/InspectionResults.Designer.cs
- Rubberduck.Resources/Inspections/InspectionResults.resx
- Rubberduck.Resources/Inspections/InspectionsUI.Designer.cs
- Rubberduck.Resources/Inspections/QuickFixes.Designer.cs
- Rubberduck.Resources/Menus/RubberduckMenus.Designer.cs
- Rubberduck.Resources/Rubberduck.Resources.csproj
- Rubberduck.Resources/Settings/SettingsUI.Designer.cs
- Rubberduck.Resources/Settings/ToDoExplorerPage.Designer.cs
- Rubberduck.Resources/Settings/UnitTestingPage.Designer.cs
- Rubberduck.Resources/Templates.Designer.cs
- Rubberduck.Resources/ToDoExplorer/ToDoExplorerUI.Designer.cs
- Rubberduck.Resources/UnitTesting/TestExplorer.Designer.cs
- RubberduckTests/Inspections/ThunderCode/ThunderCodeInspectionTests.cs
Closes #4778
Screenshot of Thundercode at action:
At present 3 inspections are provided:
1) Use of non-breaking space
2) Use of keywords in either an enum or a UDT
3) Weird line continuations
Note that I bucked the convention of not adding line breaks to the inspection results, primarily because without it, it does not read as easily and the nod to ThunderFrame gets lost in the text. I hope that is OK.
> Implement ThunderCode inspections

- Rubberduck.Core/UI/About/AboutControl.xaml
- Rubberduck.Core/UI/About/AboutControl.xaml.cs
- Rubberduck.Core/UI/About/AboutControlViewModel.cs
- Rubberduck.Core/UI/About/AboutDialog.Designer.cs
- Rubberduck.Resources/About/AboutUI.Designer.cs
- Rubberduck.Resources/About/AboutUI.cs.resx
- Rubberduck.Resources/About/AboutUI.de.resx
- Rubberduck.Resources/About/AboutUI.es.resx
- Rubberduck.Resources/About/AboutUI.fr.resx
- Rubberduck.Resources/About/AboutUI.resx
This also modifies the copyright year in the bottom label so that it automatically updates (as @retailcoder suggested). Interestingly, the ViewModel was ready for that, but the string resources weren't (they had a hard-coded `2018` instead of `{0}`.
A few extra notes:
1. I also changed the `GitHubIssueUrl` so that now it gives you the option to choose the bug template
2. I thought the trailing dot in the copy version label looked a bit weird with the hyperlink style, so I removed it
3. The code to obtain the path to the log file is taken from [here](https://stackoverflow.com/a/11629408/1712861)
4. I just used Google Translate for the Czech and French translations (which means I am not entirely sure of what I have written there!)
> Add option to view log in explorer. Ref #4797

- Rubberduck.CodeAnalysis/Inspections/Concrete/HungarianNotationInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/MoveFieldCloserToUsageInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/ParameterCanBeByValInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/ProcedureNotUsedInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/ShadowedDeclarationInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/UnderscoreInPublicClassModuleMemberInspection.cs
- Rubberduck.CodeAnalysis/QuickFixes/IsMissingOnInappropriateArgumentQuickFix.cs
- Rubberduck.Core/UI/CodeExplorer/Commands/OpenDesignerCommand.cs
- Rubberduck.Core/UI/Command/Refactorings/RefactorExtractInterfaceCommand.cs
- Rubberduck.Parsing/Binding/Bindings/IndexDefaultBinding.cs
- Rubberduck.Parsing/Binding/Bindings/MemberAccessDefaultBinding.cs
- Rubberduck.Parsing/Binding/Bindings/MemberAccessTypeBinding.cs
- Rubberduck.Parsing/Binding/Bindings/SimpleNameTypeBinding.cs
- Rubberduck.Parsing/Symbols/ClassModuleDeclaration.cs
- Rubberduck.Parsing/Symbols/Declaration.cs
- Rubberduck.Parsing/Symbols/DocumentModuleDeclaration.cs
- Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs
- Rubberduck.Parsing/VBA/DeclarationCaching/DeclarationFinder.cs
- Rubberduck.Parsing/VBA/DeclarationResolving/DeclarationResolveRunnerBase.cs
- Rubberduck.Parsing/VBA/DeclarationResolving/DeclarationSymbolsListener.cs
- Rubberduck.Parsing/VBA/ReferenceManagement/CompilationPasses/TypeAnnotationPass.cs
- Rubberduck.Parsing/VBA/ReferenceManagement/CompilationPasses/TypeHierarchyPass.cs
- Rubberduck.Parsing/VBA/ReferenceManagement/ReferenceResolveRunnerBase.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
- Rubberduck.Refactorings/Common/DeclarationExtensions.cs
- Rubberduck.Refactorings/ImplementInterface/ImplementInterfaceRefactoring.cs
- Rubberduck.Refactorings/IntroduceField/IntroduceFieldRefactoring.cs
- Rubberduck.Refactorings/IntroduceParameter/IntroduceParameterRefactoring.cs
- RubberduckTests/CodeExplorer/CodeExplorerComparerTests.cs
This is basically just a stub ATM, and is intended to house document specific functionality (mainly to allow caching of properties).
Closes #4724
> Split Documents into subclass of ClassModuleDeclaration

- Rubberduck.Parsing/Grammar/VBAParser.g4
- RubberduckTests/Grammar/VBAParserTests.cs
- RubberduckTests/Inspections/ThunderCode/ThunderCodeInspectionTests.cs
Note that this doesn't enforce the same constraints as the VBE when parsing the lineSpecialForm. Most notably, the form `foo.Line -(x, y),` does not provoke a parser error, even though it does not compile.
The grammar should correctly deal with all cases that do compile.
> Fix line special form grammar

- Rubberduck.CodeAnalysis/CodeMetrics/CodeMetricsAnalyst.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
Add exception logging to RPS#OnStateChange and CodeMetricsAnalyst, fixes #4814
> Stop CodeMetrics from faceplanting Rubberduck completely

- Rubberduck.CodeAnalysis/CodeMetrics/CodeMetricsAnalyst.cs
- Rubberduck.CodeAnalysis/CodeMetrics/NestingLevelMetric.cs
- Rubberduck.Core/CodeAnalysis/CodeMetrics/CodeMetricsViewModel.cs
- Rubberduck.Core/Navigation/CodeExplorer/CodeExplorerViewModel.cs
- Rubberduck.Parsing/Common/ParsingStageTimer.cs
- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.Parsing/VBA/Parsing/IModuleParser.cs
- Rubberduck.Parsing/VBA/Parsing/ParseRunner.cs
- Rubberduck.Parsing/VBA/Parsing/ParseRunnerBase.cs
- Rubberduck.Parsing/VBA/Parsing/SynchronousParseRunner.cs
- RubberduckTests/CodeExplorer/CodeExplorerViewModelTests.cs
- RubberduckTests/CodeExplorer/MockedCodeExplorer.cs
As mentioned in issue  #4905, we have quite a lot of lock contention in the actual parsing process. This PR removes the contention by first collecting the parse results into a list using local locks. (This approach is faster than using a `ConcurrentBag`.) Then everything gets written to the parser state in one synchronous operation. This saves some, but not much, time in the parcing process. (About 1-2.5s out of 24s for my sample workbook.) Note, that logging on `Trace` level will introduce heavy lock contention on the logger and noticably slow down parsing.
In addition, this PR introduces some safety around the state changed handlers of the CE. Now, these wait for tasks sent to the UI thread. This prevents the parsing process from going on, which is important because this prevents a …
> Speed up parsing (slightly)

- Rubberduck.Core/Navigation/RegexSearchReplace/RegexSearchReplace.cs
- Rubberduck.Parsing/Binding/BindingService.cs
- Rubberduck.Parsing/Binding/DefaultBindingContext.cs
- Rubberduck.Parsing/Binding/Expressions/IndexExpression.cs
- Rubberduck.Parsing/Binding/Expressions/MemberAccessExpression.cs
- Rubberduck.Parsing/Binding/Expressions/NewExpression.cs
- Rubberduck.Parsing/Binding/Expressions/ParenthesizedExpression.cs
- Rubberduck.Parsing/Binding/Expressions/ResolutionFailedExpression.cs
- Rubberduck.Parsing/Binding/Expressions/TypeOfIsExpression.cs
- Rubberduck.Parsing/Binding/Expressions/UnaryOpExpression.cs
- Rubberduck.Parsing/Binding/IBindingContext.cs
- Rubberduck.Parsing/Binding/ProcedurePointerBindingContext.cs
- Rubberduck.Parsing/Binding/TypeBindingContext.cs
- Rubberduck.Parsing/Symbols/IdentifierReference.cs
- Rubberduck.Parsing/VBA/ReferenceManagement/BoundExpressionVisitor.cs
- Rubberduck.Refactorings/Common/DeclarationExtensions.cs
This PR replaces the dynamic call in the binding stage of the references resolver.
This has two main advantages: it is easier to navigate the code when debugging (no need to find some code and run it through the debugger to follow the execution flow) and it is slightly faster.
> Remove dymanic calls from resolver

- Rubberduck.VBEEditor/Utility/AddComponentService.cs
Closes #4919 
This is more in line with the VBE's own behaviour.
As stated in the linkes issue, it worked like that before, but the change in how templates are loaded made them not pop up anymore.
> Show components added through the AddComponentService

- Rubberduck.Core/UI/ToDoItems/ToDoExplorerViewModel.cs
From an email reporting, it was observed that decompile do not work on Access. Investigating, it's not really the decompile but in fact the reparse command being executed during the startup which also compiles the codebase, giving an appearance of not working. This is further confirmed by the fact that if a project has broken code, dialog will be shown asking to parse code anyway at the startup. We do not want to parse code during startup as this is usually too premature. This seemed to be caused by the change of `RefreshCommand` which is invoked during the load. The hot fix converts the RefreshCommand into a CommandBase, so it is property-injected rather than newed up directly.
> Hotfix to TodoExplorer 

- Rubberduck.Core/UI/Command/MenuItems/CommandBars/SerializeProjectsCommandMenuItem.cs
- Rubberduck.VBEEditor/ComManagement/ComSafeBase.cs
- Rubberduck.VBEEditor/ComManagement/IComSafe.cs
- Rubberduck.VBEEditor/ComManagement/StrongComSafe.cs
- Rubberduck.VBEEditor/ComManagement/WeakComSafe.cs
- Rubberduck.VBEEditor/SourceCodeHandling/SourceFileHandlerComponentSourceCodeHandlerAdapter.cs
This PR does two things:
First, it fixes the oversight that the export encoding was not specified when substituting code via a file.
ref #4906 
Second, it restricts tracing of the `ComSafe` to when the compilation constant `TRACE_COM_SAFE` is specified instead of tracing it on all debug builds. This makes testing performance easier while still keeping the possibility to trace if needed for some investigation.
> Fix attributes encoding issue

- Rubberduck.SettingsProvider/Persistence/XmlPersistenceService.cs
Closes #4966. Previously was exporting to %appdata%\Rubberduck\ and overwriting
rubberduck.config. Now exports to chosen directory and uses chosen filename.
> Correct exporting settings file

- Rubberduck.Core/UI/CodeExplorer/CodeExplorerControl.xaml
- Rubberduck.Core/UI/CodeExplorer/CodeExplorerControl.xaml.cs
Close #4879. [Should we inform the user they can't delete a document object](https://chat.stackexchange.com/transcript/message/50906814#50906814) answered with [No](https://chat.stackexchange.com/transcript/message/50906786#50906786).
> Enable Del key for CodeExplorer module removal

- Rubberduck.Core/UI/AddRemoveReferences/AddRemoveReferencesWindow.xaml
- Rubberduck.Core/UI/AddRemoveReferences/AddRemoveReferencesWindow.xaml.cs
Close #4798.
Previously when activating between `LibrarySelect` and `ProjectSelect` the footer wouldn't update if a new selection wasn't chosen. Now the footer displays the correct information whenever focus changes.
> Synchronize reference explorer with selected item

- .gitignore
Rubberduck.CodeAnalysis.xml is a build artifact, shouldn't be under SC.
> ignore the xmldoc export

- Rubberduck.CodeAnalysis/Properties/CodeInspectionDefaults.Designer.cs
- Rubberduck.CodeAnalysis/Properties/CodeInspectionDefaults.settings
- Rubberduck.Parsing/Annotations/AttributeAnnotationProvider.cs
- Rubberduck.Parsing/Annotations/ExcelHotKeyAnnotation.cs
- RubberduckTests/Annotations/AttributeAnnotationProviderTests.cs
Fixes the "add missing attribute" quickfix (double quotes were missing around the value).
<s>The quickfix to "add missing annotation" can't deal with the "\n" in "T\n14" right now, so getting the annotation from the attribute is broken ATM.</s>
> hotfix for ExcelHotkey annotation

- Rubberduck.CodeAnalysis/Inspections/Concrete/OptionExplicitInspection.cs
- Rubberduck.CodeAnalysis/QuickFixes/OptionExplicitQuickFix.cs
- Rubberduck.Core/AutoComplete/SelfClosingPairs/SelfClosingPairHandler.cs
- RubberduckTests/Inspections/OptionExplicitInspectionTests.cs
- RubberduckTests/QuickFixes/OptionExplicitQuickFixTests.cs
> Stop reporting missing 'Option Explicit' in otherwise empty modules

- Rubberduck.Core/UI/Controls/GroupingGrid.xaml
The problem was the binding mode on `InitialExpandedState`, that needed to be `OneWay`.
> Fixes all-at-once GroupingGrid collapse/expand

- Rubberduck.Core/UI/ToDoItems/ToDoExplorerViewModel.cs
- RubberduckTests/TodoExplorer/TodoExplorerTests.cs
Closes #5119 
This fixes the bad changes introduced in the #4833 where the navigate command wasn't correctly injected. Reviewing the view model, there were few eyebrow-raisers within the class, so I took the opportunity to make it less eyebrow-raising and a bit more mainstream.
> Clean up the ToDoExplorerViewModel class and add arrange to the tests.

- Rubberduck.Core/Common/ExportFormatter.cs
- Rubberduck.Core/UI/CodeExplorer/CodeExplorerWindow.cs
- Rubberduck.Core/UI/Controls/SearchBox.xaml
- Rubberduck.Core/UI/Inspections/InspectionResultsControl.xaml
- Rubberduck.Core/UI/Inspections/InspectionResultsViewModel.cs
- Rubberduck.Core/UI/Settings/InspectionSettings.xaml
- Rubberduck.Core/UI/Settings/InspectionSettingsViewModel.cs
- Rubberduck.Resources/Inspections/InspectionsUI.Designer.cs
- Rubberduck.Resources/Inspections/InspectionsUI.resx
- Rubberduck.Resources/RubberduckUI.Designer.cs
- Rubberduck.Resources/RubberduckUI.resx
Close #5080
I have a BrainTickle over the use of [InspectionsUI.ResourceManager.GetString("CodeInspectionSeverity_All", CultureInfo.CurrentUICulture);](https://github.com/IvenBach/Rubberduck/blob/Issue5080_Text_filter_for_Code_Inspections/Rubberduck.Core/UI/Settings/InspectionSettingsViewModel.cs#L81). Is it done this way because of localization? In previous PR I recall using `InspectionsUI.CodeInspectionSeverity_All` and assumed it was good.
> Add description filter for Code Inspections

- Rubberduck.Parsing/Binding/Bindings/IndexDefaultBinding.cs
- Rubberduck.Parsing/Binding/Bindings/ProcedureCoercionDefaultBinding.cs
- Rubberduck.Parsing/Binding/DefaultBindingContext.cs
- Rubberduck.Resources/Inspections/InspectionResults.Designer.cs
- Rubberduck.Resources/Inspections/InspectionResults.resx
- RubberduckTests/Grammar/ResolverTests.cs
- RubberduckTests/Inspections/DefaultMemberRequiredInspectionTests.cs
- RubberduckTests/Inspections/ProcedureRequiredInspectionTests.cs
Closes  #5147
This PR fixes that both the `IndexDefaultBinding` and the `ProcdureCoercionBinding` did not consider recursive function calls. For these, the expression referring to the function is classified as a variable becasue that is appropriate for the variable holding the return value. So, this situation needs to be special cased.
> Fixes around recursive function calls

- RubberduckTests/Inspections/UnreachableCase/UnreachableCaseInspectionTests.cs
Closes #3962.  The issue was actually corrected by a previous PR (probably #4127) and a unit test linked to the issue already existed.  However, while reviewing the test, I realized that it could possibly generate a false-positive (passing) result.   So, this PR simply identifies that #3962 is resolved and includes only a modification to the unit test.
> 3962_UnreachableCaseInspection

- Rubberduck.Core/app.config
Autocomplete should now be shipped enabled by default. Closes #5157
> Autocomplete enabled by default.

- Rubberduck.CodeAnalysis/Inspections/Concrete/ParameterCanBeByValInspection.cs
- RubberduckTests/Inspections/ParameterCanBeByValInspectionTests.cs
`DeclarationType.Enumeration` was explicitly excluded, along with `DeclarationType.UserDefinedType`. Now I can see why a UDT would need to be excluded, but not an enum. Removing the exclusion fixes the issue.
> Fixes "parameter can be byval" false negative with enums

- Rubberduck.CodeAnalysis/Inspections/Abstract/IdentifierReferenceInspectionBase.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/DefaultMemberRequiredInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/ProcedureRequiredInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/UseOfBangNotationInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/UseOfRecursiveBangNotationInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/UseOfUnboundBangNotationInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/ValueRequiredInspection.cs
- Rubberduck.CodeAnalysis/QuickFixes/ExpandBangNotationQuickFix.cs
- Rubberduck.Parsing/VBA/ReferenceManagement/BoundExpressionVisitor.cs
- Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs
- Rubberduck.Resources/Inspections/InspectionInfo.de.resx
- Rubberduck.Resources/Inspections/InspectionInfo.resx
- Rubberduck.Resources/Inspections/InspectionNames.Designer.cs
- Rubberduck.Resources/Inspections/InspectionNames.de.resx
- Rubberduck.Resources/Inspections/InspectionNames.resx
- Rubberduck.Resources/Inspections/InspectionResults.Designer.cs
- Rubberduck.Resources/Inspections/InspectionResults.de.resx
- Rubberduck.Resources/Inspections/InspectionResults.resx
- Rubberduck.Resources/Inspections/QuickFixes.Designer.cs
- Rubberduck.Resources/Inspections/QuickFixes.de.resx
- Rubberduck.Resources/Inspections/QuickFixes.resx
- RubberduckTests/Inspections/DefaultMemberRequiredInspectionTests.cs
- RubberduckTests/Inspections/ProcedureRequiredInspectionTests.cs
- RubberduckTests/Inspections/UseOfBangNotationInspectionTests.cs
- RubberduckTests/Inspections/UseOfRecursiveBangNotationInspectionTests.cs
- RubberduckTests/Inspections/UseOfUnboundBangNotationInspectionTests.cs
- RubberduckTests/Inspections/ValueRequiredInspectionTests.cs
- RubberduckTests/QuickFixes/ExpandBangNotationQuickFixTests.cs
- RubberduckTests/QuickFixes/QuickFixTestBase.cs
Closes #4406 
Deals with the non-control part of issue #5093 
This PR introduces the `UseOfBangNotationInspection`, which finds all uses of the bang operator. It also provides a quick fix that turns the bang notation into an explicit default member access, passing the argument as a string.
> Use of bang notation inspection

- Rubberduck.CodeAnalysis/Inspections/Concrete/VariableNotUsedInspection.cs
- RubberduckTests/Inspections/VariableNotUsedInspectionTests.cs
Resolves #5088.  The existing inspection looked for declarations with zero references, but did not evaluate the case(s) where all references were assignments only.  Also, did some refactoring of tests to reduce duplicate boilreplate code.
> Resolve issue 5088

- Rubberduck.CodeAnalysis/Inspections/Concrete/ImplementedInterfaceMemberInspection.cs
- RubberduckTests/Inspections/ImplementedInterfaceMemberInspectionTests.cs
Resolves #5143.  `ImplementedInterfaceMemberInspection` now inspects class modules with the `@Interface` annotation even if the interface has yet to be implemented by another class.  Incorporates `InspectionTestsBase` into the test class.
> ImplementedInterfaceMemberInspection evals Annotated-only and implemented interfaces

- Rubberduck.CodeAnalysis/Rubberduck.CodeAnalysis.csproj
- Rubberduck.Core/Rubberduck.Core.csproj
- Rubberduck.Deployment/Rubberduck.Deployment.csproj
- Rubberduck.Interaction/Rubberduck.Interaction.csproj
- Rubberduck.JunkDrawer/Rubberduck.JunkDrawer.csproj
- Rubberduck.Parsing/Rubberduck.Parsing.csproj
- Rubberduck.Refactorings/Rubberduck.Refactorings.csproj
- Rubberduck.RegexAssistant/Rubberduck.RegexAssistant.csproj
- Rubberduck.Resources/Rubberduck.Resources.csproj
- Rubberduck.SettingsProvider/Rubberduck.SettingsProvider.csproj
- Rubberduck.SmartIndenter/Rubberduck.SmartIndenter.csproj
- Rubberduck.UnitTesting/Rubberduck.UnitTesting.csproj
- Rubberduck.VBEEditor/Rubberduck.VBEditor.csproj
- Rubberduck.VBEditor.VB6/Rubberduck.VBEditor.VB6.csproj
- Rubberduck.VBEditor.VBA/Rubberduck.VBEditor.VBA.csproj
- RubberduckTests/RubberduckTests.csproj
This brings the number of build warnings down from over 1600 to under 300.
> suppress warning 1591 about missing xmldoc comment

- Rubberduck.CodeAnalysis/Inspections/Concrete/SuspiciousLetAssignmentInspection.cs
- Rubberduck.CodeAnalysis/QuickFixes/ExpandDefaultMemberQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/UseSetKeywordForObjectAssignmentQuickFix.cs
- Rubberduck.Parsing/Binding/Bindings/IndexDefaultBinding.cs
- Rubberduck.Parsing/Symbols/IdentifierReference.cs
- Rubberduck.Parsing/VBA/ReferenceManagement/BoundExpressionVisitor.cs
- Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs
- Rubberduck.Resources/Inspections/InspectionInfo.de.resx
- Rubberduck.Resources/Inspections/InspectionInfo.resx
- Rubberduck.Resources/Inspections/InspectionNames.Designer.cs
- Rubberduck.Resources/Inspections/InspectionNames.de.resx
- Rubberduck.Resources/Inspections/InspectionNames.resx
- Rubberduck.Resources/Inspections/InspectionResults.Designer.cs
- Rubberduck.Resources/Inspections/InspectionResults.de.resx
- Rubberduck.Resources/Inspections/InspectionResults.resx
- RubberduckTests/Inspections/IndexedUnboundDefaultMemberAccessInspectionTests.cs
- RubberduckTests/Inspections/SuspiciousLetAssignmentInspectionTests.cs
- RubberduckTests/QuickFixes/ExpandBangNotationQuickFixTests.cs
- RubberduckTests/QuickFixes/ExpandDefaultMemberQuickFixTests.cs
- RubberduckTests/QuickFixes/UseSetKeywordForObjectAssignmentQuickFixTests.cs
Closes #5099 
Closes #5201
This PR introduces the `SuspiciousLetAssignmentInspection`. It finds all Let assignments in which both sides are objects and either have suitable default members or are of type `Object` and there is no explicit `Let` keyword. (The cases in which there is no suitable default member on any side is already covered by the `ObjectVariableNotSetInspection`.) The case with explicit `Let` does not yield a result because one has to assume that the default member is intentional in that case.
There are two fixes for the  `SuspiciousLetAssignmentInspection`, the enhanced `ExpandDefaultMemberInspectionQuickFix`, which expands the default members of both sides and is deactivated for results involving unboud default members, and the `UseSetKeywordForObjectAssignmentQuickFix`, …
> Suspicious Let assignment inspection

- Rubberduck.Core/UI/Controls/SearchBox.xaml
Closes #5137 
You are now able to clear a SearchBox with a key press, not just a button press, by using the Esc key. See example below. This applies to the Code Explorer, To-Do Explorer and the Inspections window.
https://gyazo.com/4d5722a60b4ecac38db112a0dbcdda05
> Added the ClearSearchCommand to the SearchBox ValueContainer.

- Rubberduck.Core/UI/Converters/ImageSourceConverter.cs
Closes #4660
Using the advice from this [SO thread](https://stackoverflow.com/questions/33532680/disposing-a-memory-stream-properly-wpf-image-conversion), this seems to work. However, the memory profiling seems to have paradoxically resulted in a slight memory increase, but that might be due to extraneous factors. 
Suggestions welcome to positively prove this helped the matter.
> Plug the WPF leak... maybe.

- Rubberduck.Parsing/VBA/ParseCoordinator.cs
In the PR #5182 there was a block for `LOAD_USER_COM_PROJECTS` that got deleted but didn't get refactored. As per #5217 this is now the suspect for crashing.
This PR put it back in its own back. Note that `ref` are used to preserve the current semantics now that it's in its own method. Added a comment as well.
> Correct the missed conditional for LOAD_USER_COM_PROJECTS

- Rubberduck.Core/UI/Notifiers/MemberAttributeRecoveryFailureNotifier.cs
- Rubberduck.Parsing/Rewriter/IMemberAttributeRecoveryFailureNotifier.cs
- Rubberduck.Parsing/Rewriter/MemberAttributeRecoverer.cs
- RubberduckTests/Inspections/EmptyModuleInspectionTests.cs
- RubberduckTests/Rewriter/MemberAttributeRecovererTests.cs
Closes #5222
Now, the key used to identify members is (memberName, memberType) instead od just memberName. This is necessary because Get, Let and Set properties share the same name.
> Fix member attributes recovery for properties

- Rubberduck.Parsing/Binding/Bindings/MemberAccessDefaultBinding.cs
- Rubberduck.Parsing/VBA/DeclarationResolving/DeclarationSymbolsListener.cs
- Rubberduck.Parsing/VBA/ReferenceManagement/BoundExpressionVisitor.cs
- RubberduckTests/Grammar/ResolverTests.cs
Closes #3238
This PR changes the identifier name on enum elements defined with enclosing brackets to the text withing the outermost enclosing brackets. This agrees withe the handling of the VBE as can be seen from the IntelliSense dropdown.
Moreover, the `IdentifierName` of references with bracketed members is changed to that of the referenced declaration. Having it include the brackets and thus differing from that of the declaration is rather surprising.
> Fix enum member resolution

- Rubberduck.Core/Navigation/CodeExplorer/CodeExplorerViewModel.cs
- Rubberduck.Core/UI/CodeExplorer/CodeExplorerControl.xaml
- Rubberduck.Core/UI/CodeExplorer/Commands/ImportCommand.cs
- Rubberduck.Core/UI/CodeExplorer/Commands/ReplaceProjectContentsFromFilesCommand.cs
- Rubberduck.Core/UI/CodeExplorer/Commands/UpdateFromFileCommand.cs
- Rubberduck.Resources/CodeExplorer/CodeExplorerUI.Designer.cs
- Rubberduck.Resources/CodeExplorer/CodeExplorerUI.de.resx
- Rubberduck.Resources/CodeExplorer/CodeExplorerUI.resx
- Rubberduck.Resources/RubberduckUI.Designer.cs
- Rubberduck.Resources/RubberduckUI.de.resx
- Rubberduck.Resources/RubberduckUI.resx
- Rubberduck.VBEEditor/Extensions/ComponentTypeExtensions.cs
- Rubberduck.VBEEditor/Utility/ModuleNameFromFileExtractor.cs
- Rubberduck.VBEditor.VB6/SafeComWrappers/VB/VBComponents.cs
- Rubberduck.VBEditor.VBA/SafeComWrappers/VB/VBComponents.cs
- RubberduckTests/CodeExplorer/CodeExplorerViewModelTests.cs
- RubberduckTests/CodeExplorer/MockedCodeExplorer.cs
- RubberduckTests/Mocks/MockProjectBuilder.cs
Closes #4781
This PR introduces two new import commands, `ReplaceProjectContentsFromFilesCommand` and `UpdateFromFilesCommand`. The first removes all reimportable components from the target project before importing from the selected files. (A confirmation dialog is planned.) The second one removes existing components with the same component name before importing from file. This will abort, if either a component name exists multiple times in the files to import or the file extension of the file to import for a component name does not correspond to the component type of an existing component of the same name.
The user interaction around the confirmation and aborting the import still has to be implemented, as well as the inclusion into the context menu. However, I wanted to get this out for …
> SC style import commands

- Rubberduck.Core/UI/Settings/GeneralSettingsView.cs
- Rubberduck.Core/UI/Settings/SettingsForm.cs
- Rubberduck.Core/UI/Settings/SettingsView.cs
- Rubberduck.Resources/Settings/SettingsUI.Designer.cs
- Rubberduck.Resources/Settings/SettingsUI.resx
Subclassed GeneralSettingsView to allow header instructions and button text to remain synchronized for further updates.
Instructions were a bit off previously with a recent PR.
> Update GeneralSettings header instructions

- Rubberduck.Parsing/UIContext/UiDispatcher.cs
This PR changes the behaviour of `UiDispatcher.StartTask` in case we are already on the UI synchronization context/ In this case, it will perform the requested action immediately and return a completed task. This removes the potential deadlock from creating a new task from the UI thread and then waiting for it.
> Make the UI dispatcher more deadlock safe

- Rubberduck.CodeAnalysis/Inspections/Results/IdentifierReferenceInspectionResult.cs
- Rubberduck.Core/UI/Command/RunSelectedTestMethodCommand.cs
- Rubberduck.UnitTesting/UnitTesting/TestEngine.cs
- RubberduckTests/UnitTesting/MockedTestEngine.cs
Closes #5053
This PR fixes a few bugs around hanging RD. 
The main change is in the test engine, which now requests the suspension on a background thread and pushes to the UI thread from within the suspension action. This avoids the deadlock experienced in #5053. Since we cannot execute the tests before the parse has ended anyway, the states in which the tests can be run has been restricted to `Ready` only. 
In addition, this PR fixes to NREs I introduced in earlier PRs. One is in the `CanExecute` method of the `RunSelectedTestMethodCommand`, which did not handle that nothing at all might be selected. The second one is in `ChangesInvalidateIsnpectionResult` on `IdentifierReferenceInspectionResult`, which assumed that the `Target` declaration could never be `null`. This is no longer true …
> Fixes around deadlocks

- Rubberduck.VBEEditor/Utility/SelectionService.cs
This method seems to sporadically cause COM exceptions making rewrites fail. (See #5242.)
This is a symptomatic fix to keep RD usable. A real fix for the cause of the exception should follow later.
> Log and swallow COM exceptions in SelectionProvider.OpenModules

- Rubberduck.Core/UI/Inspections/InspectionResultsControl.xaml
- Rubberduck.Core/UI/UnitTesting/TestExplorerControl.xaml
Closes #5265
Closes #5302
This fixes several problems with the scroll bars in the results windows. The basic problem was that the recently introduced scroll viewer around the entire control had vertical scrolling enabled. This took precedence over the grouping grid's own vertical scroll viewer. 
Now, the data grid can be scrolled independently again and the scroll wheel works again as well. Hopefully, this also improves the performance of the windows by making virtualization work properly again. As an addition, the fix for the test results to not move the horizontal scroll bar on selection of an item was ported to the inspection results window.
The control is not ideal now since the vertical scroll bar vanishes when scrolling to the left horizontally, but I do not know how to fix that.
> Fix scroll bars in test and inspection reults windows

- Rubberduck.Core/UI/CodeExplorer/Commands/ExportCommand.cs
Close #5304. Fixes exporting a single worksheet to use `.doccls` instead of `.cls`.
> Export worksheet as doccls instead of cls file

- Rubberduck.Core/UI/Inspections/InspectionResultsControl.xaml
- Rubberduck.Core/UI/UnitTesting/TestExplorerControl.xaml
This fixes the scroll viewers in both the TestExplorerControl and The InspectionResultsControl.
The fix is to move them directly around the grouping grid. When doing this, one has to be careful to move the grouping grind into some container that can be attached to a grid because specifying a grid row inside a scrollviewer apparently attaches the control to nowhere at all and thus stops it from displaying. To handle this, I moved the grouping grid for the inspection results into a grid inside a border, which I attached to the main grid row.
In addition, added a vertical scrollviewer to the bottom panel since is can overflow to the bottom if the user resizes the window. This leads to some rows not being visible, wich is not always apparent from the contents of the control. Now, the vertical …
> Scroll viewer again

- Rubberduck.CodeAnalysis/Inspections/Concrete/FunctionReturnValueAlwaysDiscardedInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/FunctionReturnValueDiscardedInspection.cs
- RubberduckTests/Inspections/FunctionReturnValueAlwaysDiscardedInspectionTests.cs
- RubberduckTests/Inspections/FunctionReturnValueDiscardedInspectionTests.cs
I forgot to handle output lists in addition to argument lists. This PR rectifies this.
> Fix FunctionReturnValue(Always)DiscardedInspection

- Rubberduck.VBEEditor/Utility/AddComponentService.cs
- Rubberduck.VBEEditor/Utility/IAddComponentService.cs
So far, the `IAddComponentService` did not provide a possibility to name the new component. This is unfortunate, since the component is not returned, in order to shield the using code from using SCWs. 
This PR changes this by adding an optional parameter for the component name. That the name actually gets assigned is not fully guaranteed since a name collision will cause a `COMException`, which will be logged ans swallowed.  It is the callers responsibility to make sure that no component of the desired name already exists.
> Let AddComponentService optionally take a component name

- Rubberduck.CodeAnalysis/Inspections/Concrete/ProcedureNotUsedInspection.cs
- Rubberduck.Parsing/Annotations/Concrete/ModuleCleanupAnnotation.cs
- Rubberduck.Parsing/Annotations/Concrete/ModuleInitializeAnnotation.cs
- Rubberduck.Parsing/Annotations/Concrete/TestCleanupAnnotation.cs
- Rubberduck.Parsing/Annotations/Concrete/TestInitializeAnnotation.cs
- Rubberduck.Parsing/Annotations/Concrete/TestMethodAnnotation.cs
- Rubberduck.Parsing/Annotations/ITestAnnotation.cs
- RubberduckTests/Inspections/ProcedureNotUsedInspectionTests.cs
Closes #5281
**Reason for the change:**
As seen in #5281, annotations that are meant to be used in tests were allowing `ProcedureNotUsedInspection`s to pop-up where they did not make sense.
**Description of change:**
1. Marked test annotations with a marking interface.
2. Ignored annotations with the marking interface for declarations of the `ProcedureNotUsedInspection`.
> ProcedureNotUsedInspection ignores declarations that have ITestAnnotations

- Rubberduck.Core/UI/Settings/GeneralSettingsViewModel.cs
Closes #5259 
**Description of Problem:**
When a hotkey is disabled & does not have a modifier, the hotkey modification label is displayed, but it is expected to be displayed only when the hotkey is enabled.
**Proposed Solution:**
Excluding disabled hotkeys when determining which hotkeys should display the modification label. Thanks for narrowing the search for me @Vogel612.
> Hotkey Mod Label: Exclude Disabled Hotkeys

- Rubberduck.Core/UI/Command/MenuItems/CommandBars/AppCommandBarBase.cs
- Rubberduck.Core/UI/Command/MenuItems/CommandBars/RubberduckCommandBar.cs
- Rubberduck.Core/UI/Inspections/InspectionResultsViewModel.cs
- Rubberduck.Parsing/VBA/RubberduckParserState.cs
This PR does two things.
First, it introduces more high level exception handling. More precisely, we now log and swallow exceptions in the async void responsible for refreshing inspection results. Anything bubbling out there would most likely take down the host, as observed in #5349. Moreover, `FindChildByTag` called when changing the status message on the command bar now also handles `InvalidCastException`s.  This should guarantee that the COM registration issues in #5349 only affect the status label and nothing else.
I also added to this PR a second small improvement. I introduced a second event for status changes whose handler is executed before the usual one, basically giving it a higher priority. This allows to guarantee that the status label update always runs first by only …
> Additional top level exception handling and better status message sequencing

- appveyor.yml
This should improve build stability by eliminating a point of failure with the download of the coverage uploader depending on chocolatey again
> revert codecov bash uploader introduction

- Rubberduck.CodeAnalysis/Inspections/Concrete/Excel/SheetAccessedUsingStringInspection.cs
- Rubberduck.JunkDrawer/Output/StringExtensions.cs
- Rubberduck.Parsing/Annotations/Concrete/ObsoleteAnnotation.cs
- Rubberduck.Parsing/Annotations/Concrete/TestMethodAnnotation.cs
- Rubberduck.UnitTesting/UnitTesting/TestMethod.cs
- RubberduckTests/Inspections/SheetAccessedUsingStringInspectionTests.cs
- RubberduckTests/QuickFixes/AccessSheetUsingCodeNameQuickFixTests.cs
….and back
This is used to fix SheetAccessUsingStringInspection in case the sheet name contains a double quote.
> Add string extension to convert from VBA string literals to strings 

- Rubberduck.Parsing/Grammar/VBAParser.g4
- RubberduckTests/Grammar/VBAParserTests.cs
> Fix argumentList

- Rubberduck.Core/UI/CodeExplorer/Commands/DragAndDrop/CodeExplorerMoveToFolderDragAndDropCommand.cs
> Prohibit dragging and dropping a folder into itself

- Rubberduck.Core/UI/Refactorings/EncapsulateField/EncapsulateFieldView.xaml
Closes #5447 
Simple fix, one-liner.  #5447 and title says it all.
> Improve EncapsulateField property name TextBox content alignment

- Rubberduck.Core/UI/Inspections/InspectionResultsControl.xaml
This reverts one of the two changes in the PR introducing the problems observed in issue #5442.
This PR serves to generate a prerelease to investigate whether this solves the problem for those affected by the problem; unfortunately, I have not been able to reproduce it myself.
> Stop suppressing RequestBringIntoView in InspectionResultsControl

- Rubberduck.CodeAnalysis/Inspections/Abstract/MemberAccessMayReturnNothingInspectionBase.cs
- Rubberduck.Core/UI/UnitTesting/TestExplorerViewModel.cs
- RubberduckTests/Inspections/ExcelMemberMayReturnNothingInspectionTests.cs
This PR fixes the two NREs discovered in the log posted for #5493. One of them might have an impact on the issue, the other certainly not.
The fix for the inspection base class does not cover all possible situations. However, it covers those for the currently sole implementation and adds a doc-comment explaining the remaining restriction.
> Fix for two NREs

- Rubberduck.Core/UI/UnitTesting/TestExplorerControl.xaml
This PR is another stab at resolving issue  #5442 
Not swallowing that event in the test explorer made the sample project provided in the issue stop freezing for me. (In PR #5482, it had already been removed from the inspection results window, but not from the test explorer as it had been added in a different PR than the one introducing the issue, probably a later one.)
I hope this change also works for other people.
Once we know that it really works in the field, we might reintroduce a handler, but using a better scheme than swallowing the event to handle the original problem for which the handler has been added.
> Remove handler for RequestBringIntoView from TestExplorer

- Rubberduck.Core/UI/UnitTesting/TestExplorerViewModel.cs
This uses live grouping and live filtering in the test explorer, which is the built-in functionality to allow updates of the grouping based on property changes. This is faster than refreshing the entire collection view each time and also does not have the negative side effects of changing the selected items and expended states all the time.
As such, it will help with #5052, but the main issue there seems to a different one.
> Use live grouping and live filtering in TestExplorer

- Rubberduck.Core/UI/CodeExplorer/CodeExplorerControl.xaml
- Rubberduck.Core/UI/Inspections/InspectionResultsControl.xaml
- Rubberduck.Core/UI/UnitTesting/TestExplorerControl.xaml
This adds a delay of 400ms to the search boxes in the test explorer, the inspection results window and the CE. This means that a somewhat below average typer with a typing speed of 150cpm will just not trigger a UI refresh while typing.
In particular in the CE, the delay is considerably shorter than the refresh time for the filter change.
> Add delay to search box input

- Rubberduck.Core/UI/Inspections/InspectionResultsControl.xaml
- Rubberduck.Core/UI/Inspections/InspectionResultsControl.xaml.cs
- Rubberduck.Core/UI/UnitTesting/TestExplorerControl.xaml
- Rubberduck.Core/UI/UnitTesting/TestExplorerControl.xaml.cs
Closes #5527
To achieve this, a new request from the original source is performed with a rectangle extending to the left into negative space. As a result, vertical scrolling is preserved, but horizontal scrolling suppressed.
Testing with the project I could reproduce the freeze with before deactivating the general bring into view suppression, I do not get a freeze again. So, I hope this way of suppressing the horizontal scroll is safe.
> Suppress only horizontal scroll in inspection results window and test explorer

- Rubberduck.CodeAnalysis/Inspections/Concrete/FunctionReturnValueDiscardedInspection.cs
- RubberduckTests/Inspections/FunctionReturnValueDiscardedInspectionTests.cs
Closes #5480
This has always been intended, but the corresponding test setup was bad. The reason to ignore results for built-in functions is that there are lots of built-in functions used for their side-effects or those of the members of the return value, e.g. `MsgBox` and `Err`.
> Disable FunctionReturnValueDiscardedInspection for built-in functions

- Rubberduck.Core/UI/Styles/DefaultStyle.xaml
- Rubberduck.RegexAssistant/i18n/AssistantResources.de.resx
- Rubberduck.Resources/About/AboutUI.de.resx
- Rubberduck.Resources/CodeExplorer/CodeExplorerUI.Designer.cs
- Rubberduck.Resources/CodeExplorer/CodeExplorerUI.de.resx
- Rubberduck.Resources/CodeExplorer/CodeExplorerUI.resx
- Rubberduck.Resources/Inspections/QuickFixes.de.resx
- Rubberduck.Resources/Menus/RubberduckMenus.de.resx
- Rubberduck.Resources/Refactorings/Refactorings.de.resx
- Rubberduck.Resources/RegexAssistant/RegexAssistantUI.de.resx
- Rubberduck.Resources/RubberduckUI.Designer.cs
- Rubberduck.Resources/RubberduckUI.de.resx
- Rubberduck.Resources/RubberduckUI.resx
- Rubberduck.Resources/Settings/AutoCompletesPage.Designer.cs
- Rubberduck.Resources/Settings/AutoCompletesPage.resx
- Rubberduck.Resources/UnitTesting/TestExplorer.Designer.cs
- Rubberduck.Resources/UnitTesting/TestExplorer.de.resx
- Rubberduck.Resources/UnitTesting/TestExplorer.resx
These are the German translations for the currently untranslated resources, apart from those for which a translation does not make a lot of sense.
In addition, the endings of several resources have been aligned.
Finally, I have added a default style for `CheckBoxe`s that centers the content vertically since I have observed on my system that the default seems to be _top_ alignment, which shifts the labels to the top relative to the box itself.
> German translations

- Rubberduck.Core/UI/About/AboutControlViewModel.cs
- Rubberduck.Core/UI/About/AboutDialog.cs
- Rubberduck.Core/UI/Command/AboutCommand.cs
- Rubberduck.Core/UI/Inspections/InspectionResultsControl.xaml
- Rubberduck.Core/UI/Inspections/InspectionResultsViewModel.cs
- Rubberduck.Core/UI/WebNavigator.cs
This PR adds a simple button linking to the /inspections website page that opens the details page for the selected inspection.
From that page, the user can view the otherwise inaccessible-from-within-RD xmldoc content for the selected inspection, navigate to the xmldoc content for the available quickfixes, and submit a pull request to add new examples or fix typos in the documentation.
This PR also consolidates the web-browser commands ("about" dialog also spawns a process like this) into a simple `IWebNavigator` interface, so that the "go to some url" wheel doesn't need reinventing every time.
> Link to inspection details pages

- Rubberduck.Parsing/VBA/ParseCoordinator.cs
- Rubberduck.VBEEditor/ComManagement/TypeLibs/Utility/VarDescExtensions.cs
This enables the parsing of user's VBA project by removing the conditional flag, meaning it will be now be on for every parse. By itself not much will have changed, but we want to get this in pre-releases to ensure there are no issues with using TypeLib APIs that we did not anticipate. 
Also, the check for constants in VBA projects was incorrect. The plan was to check `oInst = 0`, not `lpVarValue != IntPtr.Zero`. That has been corrected.
> Remove com project flag

- Rubberduck.Parsing/Preprocessing/VBAConditionalCompilationParser.g4
- RubberduckTests/Preprocessing/VBAPreprocessorTests.cs
Closes #5294
This PR simply replaces the token reference `WS` in all rules in the precompiler grammar with the `whiteSpace` rule copied over from the regular grammar.
> Allow line continuations in precompiler directives

- Rubberduck.Main/ComClientLibrary/UnitTesting/PermissiveAssertClass.cs
- Rubberduck.UnitTesting/ComClientHelpers/PermissiveObjectComparer.cs
- Rubberduck.VBEEditor/Variants/VariantComparer.cs
- Rubberduck.VBEEditor/Variants/VariantConverter.cs
- Rubberduck.VBEEditor/Variants/VariantNativeMethods.cs
- RubberduckTests/UnitTesting/AssertTests.cs
- RubberduckTests/UnitTesting/PermissiveAssertTests.cs
The PermissiveAssert class is broken. This PR makes it acts using the same semantics as used by VBA by using the [`VarCmp` function](https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-varcmp) to do the comparison. In testing, I found it was necessary to also change the type to handle some comparisons like `True = "True"`. This also refactors the `Variants` namespace a little bit.
> Fix PermissiveAssertClass

- Rubberduck.CodeAnalysis/Inspections/Concrete/ImplicitByRefModifierInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/MisleadingByRefParameterInspection.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/PassParameterByValueQuickFix.cs
- Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs
- Rubberduck.Resources/Inspections/InspectionInfo.resx
- Rubberduck.Resources/Inspections/InspectionNames.Designer.cs
- Rubberduck.Resources/Inspections/InspectionNames.resx
- Rubberduck.Resources/Inspections/InspectionResults.Designer.cs
- Rubberduck.Resources/Inspections/InspectionResults.resx
- RubberduckTests/Inspections/ImplicitByRefModifierInspectionTests.cs
- RubberduckTests/Inspections/MisleadingByRefParameterInspectionTests.cs
- RubberduckTests/QuickFixes/PassParameterByValueQuickFixTests.cs
Closes #3486 
Closes #5374 
Recruits `PassParameterByValueQuickFix` to correct explicit `ByRef` declarations.
Additionally updates `ImplicitByRefParameterInspection` to ignore implicit `ByRef` modifiers for the value-parameter of property mutators per #3486 comment.
> Add MisleadingByRefParameterInspection

- Rubberduck.CodeAnalysis/Inspections/Concrete/ThunderCode/NegativeLineNumberInspection.cs
- Rubberduck.Parsing/VBA/DeclarationResolving/DeclarationSymbolsListener.cs
- RubberduckTests/Inspections/ThunderCode/ThunderCodeInspectionTests.cs
Closes #5544
There will no longer be a result for the negative line number inspection for `On Error GoTo -1`, unless the `-1` actually refers to an existing line label.
This also fixes a bug in the declaration resolver because of which we lost the minus sign for all negative line numbers.
> Fix neg line number detected in legitimate go to neg one

- Rubberduck.Parsing/Binding/Bindings/IndexDefaultBinding.cs
- RubberduckTests/Inspections/DefaultMemberRequiredInspectionTests.cs
Closes #5581
The problem was that the empty argument list gets parsed as an argument list with a single missing argument and the `IndexDefaultBinding` did not account for it. Since the missing argument is actually a valid way to parse the empty argument list and the parser cannot know whether there is an optional parameter or not, I chose to catch this in the `IndexDefaultBinding`.
> Fix missing default member result for optional parentheses on properties

- Rubberduck.Refactorings/EncapsulateField/ConflictDetection/EncapsulateFieldConflictFinder.cs
- Rubberduck.Refactorings/EncapsulateField/Extensions/StringExtensions.cs
- RubberduckTests/Refactoring/EncapsulateField/EncapsulateFieldUseBackingField/EncapsulateArrayFieldTests.cs
- RubberduckTests/Refactoring/EncapsulateField/EncapsulateFieldUseBackingField/EncapsulateFieldTests.cs
- RubberduckTests/Refactoring/EncapsulateField/EncapsulateFieldUseBackingField/EncapsulateFieldUseBackingFieldRefactoringActionTests.cs
- RubberduckTests/Refactoring/EncapsulateField/EncapsulateFieldUseBackingField/EncapsulateUDTFieldTests.cs
- RubberduckTests/Refactoring/EncapsulateField/EncapsulateFieldUseBackingUDTMember/EncapsulateUsingStateUDTTests.cs
- RubberduckTests/Refactoring/EncapsulateField/EncapsulateFieldValidatorTests.cs
- RubberduckTests/Refactoring/EncapsulateField/EncapsulationIdentifiersTests.cs
Closes #5425 
The PR changes the `EncapsulateFieldRefactoring` declaration identifier modification scheme to increment identifiers without using an underscore.
The `EncapsulateFieldRefactoring` currently appends "_1" and the increments the value as necessary to resolve conflicting property and backing field names.  Introducing the underscore generated members that could not be subsequently used as an interface member (without renaming to eliminate the underscore).   
Equally important: The expected effect of changing the incrementing scheme was several failing tests.  However, one test did not pass by simply removing the underscores from the expected results.  The modified test surfaced a `EncapsulateFieldConflictFinder` bug that is also fixed in this PR.
> Modify EncapsulateFieldRefactoring to generate Identifiers without underscores

- Rubberduck.Parsing/VBA/ReferenceManagement/ReferenceResolveRunnerBase.cs
Closes #5624
Materialize additional supertype interfaces before adding them to the collection they are based on.
I should have tested this on Access, but apparently didn't. On Excel, the problem does not surface since this interface construction is specific to Access.
> Fix bug in supertype name derivation

- Rubberduck.Parsing/ComReflection/XmlComProjectSerializer.cs
- Rubberduck.VBEEditor/ComManagement/TypeLibs/TypeLibVBEExtensions.cs
- RubberduckBaseProject.csproj
There is an access violation when one tries to parse too soon or at wrong time which then leaks the pointer and causes Access to becomes unstable and thus can crash when exiting normally. This helps fixes and also 2 minor changes for developer's convenience.
> Potentially fix the AV when running Rubberduck with Access

- Rubberduck.CodeAnalysis/QuickFixes/Concrete/IgnoreInModuleQuickFix.cs
- Rubberduck.Parsing/VBA/DeclarationCaching/DeclarationFinder.cs
- RubberduckTests/Inspections/VariableTypeNotDeclaredInspectionTests.cs
- RubberduckTests/QuickFixes/IgnoreInModuleQuickFixTests.cs
Closes #5690
Closes #5686
This PR fixes two issues previously not covered in tests and not encountered regularly in real code.
1. The `IgnoreModuleQuickFix` added the annotation in the target's module instead of the one the inspection result was in. This only ever makes a difference for identifier reference results for which the referenced declaration is in another module. In the referenced issue, this meant that we tries to change the code behind of a built-in module, which failed silently.
2. We ignored the type defined on a `ReDim` statement when it declares a variable, leading to the false-positive in the issue above and generally preventing the correct resolution of member accesses to array members.
The fix for 1. is straightforward; use the module on the qualified selection instead …
> Fix ignore module quick fix and ReDim array types

- Rubberduck.Deployment/InnoSetup/Rubberduck.Installer.Build.iss
The ISS script was using http, so the start menu link would be http. This changes to use https.
> Use the HTTPS, Luke

- Rubberduck.Parsing/Symbols/Declaration.cs
`VB_VarDescription` attributes are not being taken into account when evaluating `Declaration.Description`. This PR fixes that, making variable descriptions appear in both the Code Explorer's bottom panel and the RD commandbar.
> Make DescriptionString work with VB_VarDescription attributes.

- Rubberduck.Core/UI/CodeExplorer/Commands/AddTemplateCommand.cs
- Rubberduck.Core/UI/CodeExplorer/Commands/RenameCommand.cs
This PR enables the CE "Rename" command for sub-member nodes (i.e. UDT and Enum members).
> Enable Rename command for sub-member nodes

- Rubberduck.CodeAnalysis/Inspections/Concrete/UseMeaningfulNameInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/VariableNotUsedInspection.cs
- RubberduckTests/Inspections/VariableNotUsedInspectionTests.cs
This PR stops `VariableNotUsedInspection` issuing results for undeclared variables, fixing #5439. Assuming it's enabled, the undeclared variable should still get red-flagged by `UndeclaredVariableInspection`.
> Stop reporting undeclared variables as "unused"

- Rubberduck.Core/AppMenu.cs
- Rubberduck.Core/UI/CodeExplorer/Commands/AnnotateDeclarationCommand.cs
- Rubberduck.Main/Root/RubberduckIoCInstaller.cs
- Rubberduck.VBEEditor/CommandBarLocation.cs
- Rubberduck.VBEEditor/CommandBarSite.cs
- Rubberduck.VBEEditor/VbeCommandBarMenuNames.cs
- Rubberduck.VBEditor.VB6/SafeComWrappers/VB/AddIn.cs
- Rubberduck.VBEditor.VBA/SafeComWrappers/VB/AddIn.cs
- RubberduckTests/Mocks/MockAddinBuilder.cs
Code pane context menu was being inserted as a child of the `CommandBar` at index 9, and other parent menus were also being inserted as a child of a `CommandBar` object at a specific index. This PR changes the indexing to fetch parent commandbars by their `Name`, which seems more reliable.
> Fix context menus

- Rubberduck.Core/UI/UnitTesting/ComCommands/AddTestMethodBase.cs
- Rubberduck.Core/UI/UnitTesting/ComCommands/AddTestMethodCommand.cs
- Rubberduck.Core/UI/UnitTesting/ComCommands/AddTestMethodExpectedErrorCommand.cs
- RubberduckTests/Commands/UnitTestCommandTests.cs
Closes #4169
This PR addresses the uncompilable code generated when adding a UnitTest TestMethod.
The fundamental issue involved was an incorrect insertion point for the generated code.  
1. Noticed that the commands did not use the `RewritingManager`.  So, they now do.
2. The two 'Add Test' command classes (`AddTestMethodCommand` and `AddTestMethodExpectedErrorCommand`) had identical code except for a single function call.  So, the PR introduces a base class to make these commands more DRY and consistent.
3. There were a number of `'TODO` comments in the tests regarding temporal coupling.  These were addressed as well.
This is my first PR within the UnitTest area.   I'm hoping, no basic design/architecture 'rules' have not been violated by my changes.  The commands did not use the …
> UnitTests: Fix AddTestMethod commands to generate compilable code

- Rubberduck.CodeAnalysis/QuickFixes/Concrete/IgnoreOnceQuickFix.cs
#5704 was merged with the `AnnotateEntryPointQuickFix` applicable to all annotation-enabled inspections. This PR makes the quickfix only available for `ProcedureNotUsedInspection`, as intended.
> Hotfix AnnotateEntryPointQuickFix inspections

- Rubberduck.CodeAnalysis/Inspections/Abstract/ImplicitSheetReferenceInspectionBase.cs
- Rubberduck.CodeAnalysis/Inspections/Abstract/ImplicitWorkbookReferenceInspectionBase.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/AssignmentNotUsedInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/SheetAccessedUsingStringInspection.cs
- Rubberduck.Parsing/Binding/Bindings/SimpleNameDefaultBinding.cs
- Rubberduck.Parsing/Symbols/VariableDeclaration.cs
- Rubberduck.Parsing/VBA/DeclarationCaching/DeclarationFinder.cs
- Rubberduck.Parsing/VBA/DeclarationResolving/DeclarationResolveRunnerBase.cs
- Rubberduck.Resources/RubberduckUI.Designer.cs
- Rubberduck.Resources/RubberduckUI.resx
- RubberduckTests/Symbols/SelectedDeclarationProviderTests.cs
This PR completes the work done on supertype resolution.
An unqualified `Cells` member call resolves to `Excel._Global.Cells` same as before in, say, `ThisWorkbook`:
But now in `Sheet1` the same identical code is now resolving to `Excel._Worksheet.Cells`:
The *implicit ActiveSheet* and *implicit containing sheet* reference inspections still work as intended after including the `_Worksheet` superclass in the class names array.
Interestingly it's the `Worksheet` type that comes up on qualified instance member calls:
As a result, `Sheet1.Cells` resolves to a member of `Excel.Worksheet`, as it should:
> Completes the resolution of document module supertypes

- Rubberduck.VBEEditor/ComManagement/TypeLibs/TypeLibVBEExtensions.cs
Closes #5722
Reverts the change from #5675 -- left a inline comment explaining the situation for future attempts.
> Revert the attempt to avoid an AV

- Rubberduck.CodeAnalysis/Inspections/Concrete/ParameterCanBeByValInspection.cs
Explains why the inspection isn't flagging a `ByRef` parameter that is passed as an argument to a procedure that also accepts it `ByRef`; also adds an example for that specific scenario.
> Added remarks to xmldoc

- Rubberduck.Parsing/Annotations/Concrete/EntryPointAnnotation.cs
ContentUpdater app is unable to parse the example code because the code is outside of the `<module>` tag.
> fixes the EntryPointAnnotation broken xmldoc example

- Rubberduck.CodeAnalysis/Inspections/Abstract/ImplicitSheetReferenceInspectionBase.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/ImplicitActiveSheetReferenceInspection.cs
- RubberduckTests/Inspections/ImplicitActiveSheetReferenceInspectionTests.cs
- RubberduckTests/Inspections/InspectionTestsBase.cs
This patch makes the ImplicitActiveSheetReference inspection tests to now correctly set the document module supertypes in the test code, and adds a test that confirms the fix for the referenced issue.
> Hotfix for ImplicitActiveSheetReference inspection

- Rubberduck.Resources/Inspections/InspectionInfo.cs.resx
- Rubberduck.Resources/Inspections/InspectionNames.cs.resx
- Rubberduck.Resources/Inspections/InspectionResults.cs.resx
- Rubberduck.Resources/Inspections/QuickFixes.cs.resx
- Rubberduck.Resources/Menus/RubberduckMenus.cs.resx
- Rubberduck.Resources/Rubberduck.Resources.csproj
- Rubberduck.Resources/RubberduckUI.cs.resx
- Rubberduck.Resources/Settings/AutoCompletesPage.Designer.cs
- Rubberduck.Resources/Settings/AutoCompletesPage.cs.resx
- Rubberduck.Resources/Settings/SettingsUI.cs.resx
- Rubberduck.Resources/Settings/UnitTestingPage.Designer.cs
- Rubberduck.Resources/Settings/UnitTestingPage.cs.resx
- Rubberduck.Resources/Templates.cs.resx
Czech translations should be updated.
There are 3 items (key names) that were renamed to something else (we talked about that in chat) in ResX manager.
- Neutral language is missing, 
- Czech language is translated. 
Didn't know if I could delete those so I let them there.
```
Key                         #
IllegalAnnotationInspection 113
IllegalAnnotationInspection 113
IllegalAnnotationInspection 121
```
> Update Czech Translations for v2.5.2

- Rubberduck.CodeAnalysis/Inspections/Concrete/ParameterNotUsedInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseEvaluation/UnreachableCaseInspector.cs
- Rubberduck.Core/UI/CodeExplorer/CodeExplorerControl.xaml
- Rubberduck.Core/UI/CodeExplorer/Commands/CodeExplorerFindAllReferencesCommand.cs
- Rubberduck.Core/UI/Command/ComCommands/FindSymbolCommand.cs
- Rubberduck.Core/UI/Command/MenuItems/CommandBars/RubberduckCommandBar.cs
- Rubberduck.Core/UI/Controls/FindAllReferencesAction.cs
- Rubberduck.Core/UI/Controls/FindAllReferencesService.cs
- Rubberduck.Core/UI/Controls/IdentifierReferenceExtensions.cs
- Rubberduck.Core/UI/Controls/SearchResultItem.cs
- Rubberduck.Core/UI/Controls/SearchView.xaml
- Rubberduck.Core/UI/Converters/CodeExplorerNodeToIconConverter.cs
- Rubberduck.Core/UI/Converters/DeclarationToDeclarationTypeStringConverter.cs
- Rubberduck.Core/UI/Converters/DeclarationToIconConverter.cs
- Rubberduck.Core/UI/Converters/SearchResultToXamlConverter.cs
- Rubberduck.Core/UI/FindSymbol/FindSymbolControl.xaml
- Rubberduck.Core/UI/FindSymbol/FindSymbolControl.xaml.cs
- Rubberduck.Core/UI/FindSymbol/FindSymbolDialog.cs
- Rubberduck.Core/UI/FindSymbol/FindSymbolViewModel.cs
- Rubberduck.Core/UI/FindSymbol/SearchResult.cs
- Rubberduck.Parsing/Symbols/ArgumentReference.cs
- Rubberduck.Parsing/Symbols/IdentifierReference.cs
- Rubberduck.Parsing/VBA/DeclarationCaching/DeclarationFinder.cs
- Rubberduck.VBEEditor/Selection.cs
The feature had been broken for some time; this PR restores its functionality.
The number of items in the dropdown is limited to a hard-set 30 for now.
Also introduces the possibility to highlight (bold, black on yellow) a `Selection` in the search result text of a `SearchResultItem`, and leverages this possibility for _find all references_.
> Restore FindSymbol search feature

- Rubberduck.VBEditor.VB6/SafeComWrappers/VB/AddIn.cs
Reverts a commit that fixed VBA menu positioning but broke VB6 integration.
> Hotfix for VB6

- Rubberduck.Core/UI/Inspections/InspectionResultsUI.it.resx
- Rubberduck.Refactorings/RefactoringsUI.it.resx
- Rubberduck.Refactorings/RefactoringsUI.resx
- Rubberduck.Resources/CodeExplorer/CodeExplorerUI.it.resx
- Rubberduck.Resources/RubberduckUI.it.resx
- Rubberduck.Resources/Settings/AutoCompletesPage.it.resx
- Rubberduck.Resources/ToDoExplorer/ToDoExplorerUI.it.resx
- Rubberduck.Resources/UnitTesting/TestExplorer.it.resx
Minor Italian translation missed in IvenBach's ConsolidateResourceCleanup and ancestral typo (I think) in English default RefactoringsUI resource file.
> Consolidate resource Italian translation

- Rubberduck.Parsing/Grammar/VBAParser.g4
- Rubberduck.Parsing/Symbols/DeclarationLoaders/SpecialFormDeclarations.cs
- Rubberduck.Parsing/VBA/ReferenceManagement/IdentifierReferenceResolver.cs
- RubberduckTests/Grammar/VBAParserTests.cs
Closes #5775
Previously, missing arguments, i.e. left out optional positional arguments followed by provided arguments, were not supported.
This is a minimal fix honoring that the first two arguments, the coordinate tuple and the radius, are not optional.
> Fix optional parameters in Circle special form

- Rubberduck.Core/UI/CodeExplorer/CodeExplorerControl.xaml
Closes #5777
It still pointed at the old key in the old location.
> Fix Add-Remove references caption in CE context menu

- Rubberduck.Deployment/InnoSetup/Includes/Czech.CustomMessages.iss
- Rubberduck.Deployment/InnoSetup/Includes/English.CustomMessages.iss
- Rubberduck.Deployment/InnoSetup/Includes/French.CustomMessages.iss
- Rubberduck.Deployment/InnoSetup/Includes/German.CustomMessages.iss
- Rubberduck.Deployment/InnoSetup/Includes/Spanish.CustomMessages.iss
- Rubberduck.Deployment/InnoSetup/Rubberduck.Installer.Build.iss
- Rubberduck.Deployment/InnoSetup/WorkloadConfigs/Legacy/rubberduck.config
- Rubberduck.Deployment/InnoSetup/WorkloadConfigs/README.md
Adds a new wizard page to the installer with a checkbox to optionally seed `%appdata%\Rubberduck\rubberduck.config` with a default configuration file that disables a number of features and inspections, documented in a readme.md file.
> Introducing workload configs

- Rubberduck.CodeAnalysis/Inspections/Concrete/EmptyStringLiteralInspection.cs
Adds a remark in the xmldoc (will appear on that inspection's page once xmldoc assets are reprocessed) to mention potential impact on unit testing with a PermissiveAssertClass.
> xmldoc patch

- Rubberduck.Core/UI/AddRemoveReferences/AddRemoveReferencesWindow.xaml
- Rubberduck.Core/UI/AddRemoveReferences/AddRemoveReferencesWindow.xaml.cs
Fixes #5553 
Moving the code from the GetFocus handler to the SelectionChanged handler ensures that we're not looking at it when there the selection is Null.
> Eliminate NRE when tabbing through AddRemoveReferencesWindow

- Rubberduck.Core/Common/RubberduckHooks.cs
- RubberduckTests/Symbols/SelectedDeclarationProviderTests.cs
Fixes #4376 
Cause a standard Windows Beep when a user attempts to use a hot-key combo for a RD feature that is not currently executable.
> Add beep if hotkey command isn't enabled

- Rubberduck.Core/Rubberduck.Core.csproj
This reverts changes from adecadf and 440992a that incorrectly
reintroduced a specific AssemblyVersion specification in Rubberduck.Core.csproj
> Fix #5857 by partially reverting csproj changes

- Rubberduck.CodeAnalysis/Inspections/Concrete/FunctionReturnValueAlwaysDiscardedInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/FunctionReturnValueDiscardedInspection.cs
- Rubberduck.Parsing/ParserRuleContextExtensions.cs
- RubberduckTests/Inspections/FunctionReturnValueAlwaysDiscardedInspectionTests.cs
- RubberduckTests/Inspections/FunctionReturnValueDiscardedInspectionTests.cs
Closes #5853
Previously, we did not always determine correctly whether there is a member access on the return value of a function. The problem  was that the reference in a member access expression goes to the unrestricted identifier while it goes to the whole simple name expression in case of a simple name expression. This makes it necessary to deal with them in different ways; the first member access parent of a reference to a member access is the member access itself while it is a further member access for all other kinds of references.
This affected both kinds of function return value discarded inspections, since they use the same logic to determine whether a reference is used.
> Fix return value discarded inspection

- Rubberduck.Refactorings/Rename/RenameCodeDefinedIdentifierRefactoringAction.cs
- RubberduckTests/Refactoring/Rename/RenameTests.cs
This PR accomplishes a portion of the opportunities identified by #5844.  The changes modify `RenameRefactoring's` default behavior to qualify all external references of a renamed declaration. 
If this default is acceptable, then it can lead to less restrictive rename conflict detection logic since any rename collisions in external modules would be eliminated.
> Modify RenameRefactoring to use ReplaceReferencesRefactoringAction

- Rubberduck.CodeAnalysis/Inspections/Concrete/VariableNotAssignedInspection.cs
- Rubberduck.Parsing/Symbols/Declaration.cs
- Rubberduck.Parsing/Symbols/IdentifierReference.cs
- Rubberduck.Parsing/VBA/ReferenceManagement/BoundExpressionVisitor.cs
- Rubberduck.Parsing/VBA/ReferenceManagement/IdentifierReferenceResolver.cs
- RubberduckTests/Inspections/VariableNotAssignedInspectionTests.cs
Closes #5845
This inspection usually ignores arrays because they are technically valid without assignment. Moreover, it is a bit unclear what it means for them not to be assigned. (one index vs. all indices)
In the case of a Variant used as an array without an assignment to it, which is possible using a ReDim statement, we do not know that the variable represents an array. So, an inspection result was issued, although some or all array slots were assigned to.
To deal with this, a new property IsReDim has been introduced on the IdentifierReference that stores whether this reference is the array reference in a ReDim statement; it is set in the resolver.
Whenever we see such a reference on a Variant, we can be sure that it is used as an array at some point. In a sense, the ReDim statement …
> Fix VariableNotAssigned for Variants used as arrays

- Rubberduck.Parsing/Binding/DefaultBindingContext.cs
- Rubberduck.Parsing/Symbols/Identifier.cs
- RubberduckTests/Inspections/ParameterNotUsedInspectionTests.cs
Closes #5336
The problem is that expressions prefer to resolve built-in type names as built-in types in favor of simple name expressions in order to be able to distinguish them. Unfortunately, VBA allows to name declarations like built-in types.
To fix this, whenever the default expression binding context encounters a built-in type, it first tries to bind it as a simple name. It tries to resolve it and if that is successful, it returns the binding. Otherwise, it falls back to the built-in type binding.
> Correctly resolve references to declarations named like built-in types

- Rubberduck.Main/Root/RubberduckIoCInstaller.cs
- Rubberduck.VBEEditor/ComManagement/NonDisposalDecorators/AddInNonDisposalDecorator.cs
- Rubberduck.VBEEditor/ComManagement/NonDisposalDecorators/CommandBarsNonDisposalDecorator.cs
- Rubberduck.VBEEditor/ComManagement/NonDisposalDecorators/NonDisposalDecoratorBase.cs
- Rubberduck.VBEEditor/ComManagement/NonDisposalDecorators/VBComponentNonDisposalDecorator.cs
- Rubberduck.VBEEditor/ComManagement/NonDisposalDecorators/VBComponentsNonDisposalDecorator.cs
- Rubberduck.VBEEditor/ComManagement/NonDisposalDecorators/VBProjectNonDisposalDecorator.cs
- Rubberduck.VBEEditor/ComManagement/NonDisposalDecorators/VBProjectsNonDisposalDecorator.cs
- Rubberduck.VBEEditor/ComManagement/NonDisposalDecorators/VbeNonDisposalDecorator.cs
- Rubberduck.VBEEditor/ComManagement/ProjectsRepository.cs
- RubberduckTests/Mocks/MockProjectBuilder.cs
- RubberduckTests/VBEditor/ProjectsRepositoryTests.cs
This PR adds decorators for several com wrapper types to suppress disposal attempts on them.
This is relevant in two places. First, the wrappers handed out by the `ProjectsRepository` are references to cashed wrappers; only the repository itself should be allowed to dispose the instances when it clears its cache. 
Second, disposal of the com wrappers bound in CW is non-deterministic. In order to avoid running into concurrency issues on shutdown, CW should not be allowed to dispose the wrappers. This will than happen deterministically when disposing the `ComSafe`.
> Non-disposal decorators for more COM wrapper safety

- Rubberduck.CodeAnalysis/Inspections/Concrete/EmptyModuleInspection.cs
- Rubberduck.Parsing/Grammar/VBAParser.g4
- Rubberduck.Parsing/Rewriter/RewriterInfo/ConstantRewriterInfoFinder.cs
- Rubberduck.Parsing/Symbols/Identifier.cs
- Rubberduck.Parsing/Symbols/ValuedDeclaration.cs
- Rubberduck.Parsing/VBA/DeclarationResolving/DeclarationSymbolsListener.cs
- Rubberduck.Parsing/VBA/Parsing/AttributeListener.cs
- RubberduckTests/Inspections/IllegalAnnotationsInspectionTests.cs
- RubberduckTests/Inspections/MissingAttributeInspectionTests.cs
- RubberduckTests/QuickFixes/AddMissingAttributeQuickFixTests.cs
Closes #5926 
This PR adds support for attributes on module level constants. 
This required adding the corresponding contexts in the context listener and actually attaching them to the generated `ValuedDeclaration`s. 
Since only module constants can have attributes, a further level has been added in the grammar to reflect the distinction.
> Acknowledge that module constants can have attributes

- Rubberduck.CodeAnalysis/Inspections/Concrete/ProcedureCanBeWrittenAsFunctionInspection.cs
Nothing big, but I think this sounds better...
> Typo in reasoning - ProcedureCanBeWrittenAsFunction

- Rubberduck.Parsing/VBA/Parsing/AttributeListener.cs
- RubberduckTests/Inspections/MissingAttributeInspectionTests.cs
Fixes #5947
This PR adds the the missing part to actually attach attributes to module constants. Previously, the attributes listener only saved attributes for variables, not constants.
> Fix missing part for VarDesc on constants 

- Rubberduck.Core/UI/ToDoItems/ToDoExplorerViewModel.cs
This change alters the todo marker detection to require the marker be at the start of the comment, optionally preceded by whitespace and ending in a word boundary.
See #5957
> Refine TODO Marker detection

- Rubberduck.Core/UI/Settings/IndenterSettingsViewModel.cs
Fixes #5285 
The `_emptyLineHandlingMethod` field was missing from the set of initializations in the `IndenterSettingsViewModel` constructor.
> Fix EmptyLineHandlingMethod user setting initialization

- Rubberduck.Resources/Inspections/InspectionNames.Designer.cs
- Rubberduck.Resources/Inspections/InspectionNames.cs.resx
- Rubberduck.Resources/Inspections/InspectionNames.de.resx
- Rubberduck.Resources/Inspections/InspectionNames.es.resx
- Rubberduck.Resources/Inspections/InspectionNames.fr.resx
- Rubberduck.Resources/Inspections/InspectionNames.it.resx
- Rubberduck.Resources/Inspections/InspectionNames.resx
- Rubberduck.Resources/Inspections/InspectionResults.Designer.cs
- Rubberduck.Resources/Inspections/InspectionResults.cs.resx
- Rubberduck.Resources/Inspections/InspectionResults.de.resx
- Rubberduck.Resources/Inspections/InspectionResults.es.resx
- Rubberduck.Resources/Inspections/InspectionResults.fr.resx
- Rubberduck.Resources/Inspections/InspectionResults.it.resx
- Rubberduck.Resources/Inspections/InspectionResults.resx
Issue #5973 surfaced an inconsistency between the content/phrasing of the `Code Inspections` result description and the `ProcedureNotUsedInspection's` `InspectionName` resource used by the `Settings` editor.
Inconsistencies were found for all of the current 'XXXNotUsedInspection' types:
- `ConstantNotUsedInspection`
- `LineLabelNotUsedInspection`
- `ParameterNotUsedInspection`
- `ProcedureNotUsedInspection`
- `VariableNotUsedInspection`
This PR proposes to:
1. Modify the `InspectionName` resource to a phrase of the form "XXX is not used" in preference to "XXX is not referred to".
2. Delete translated "XXXNotUsedInspection" resources for both `InspectionNames` and `InspectionResults`. Re-visiting the translations looks warranted. For example, the German translations contained three forms …
> Improve resource consistency for `XXXNotUsedInspections'

- Rubberduck.CodeAnalysis/Inspections/Concrete/UDTMemberNotUsedInspection.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/RemoveUnusedDeclarationQuickFix.cs
- Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs
- Rubberduck.Resources/Inspections/InspectionInfo.resx
- Rubberduck.Resources/Inspections/InspectionNames.Designer.cs
- Rubberduck.Resources/Inspections/InspectionNames.resx
- Rubberduck.Resources/Inspections/InspectionResults.Designer.cs
- RubberduckTests/Inspections/GeneralInspectionTests.cs
- RubberduckTests/Inspections/UDTMemberNotUsedInspectionTests.cs
Related issue: #5974
Rubberduck provides both tools and encouragement to use `Private User Defined Type` (UDT) members in preference to module-level variables.  However, RD lacks any inspections for UDT members that are similar to those for Fields.  
This PR inspects for UDT Members that are declared but never assigned or used.  The `RemoveUnusedDeclarationQuickFix` supports the removal of the declarations flagged by this inspection.
> Introduce UDTMemberNotUsedInspection

- Rubberduck.Refactorings/RefactoringsUI.it.resx
- Rubberduck.Resources/Inspections/InspectionInfo.it.resx
- Rubberduck.Resources/Inspections/InspectionNames.it.resx
- Rubberduck.Resources/Inspections/InspectionResults.it.resx
- Rubberduck.Resources/Inspections/InspectionResults.resx
Italian translation for 2.5.2.6096-pre and fix a typo in InspectionResults.resx
> Italian translation 2.5.2.6096-pre (and a typo)

- Rubberduck.SmartIndenter/LogicalCodeLine.cs
- RubberduckTests/SmartIndenter/LineContinuationTests.cs
Fixes Indenter #5960 .
On ')" - Function Call End - the Alignment got resetted, whereby often the LineConttinuiation '_" was taken as Alignment position.
After that I had to adjust one Test that worked not as intended i think.
> Fix inconsistant indentation #5960

- Rubberduck.SmartIndenter/AbsoluteCodeLine.cs
- Rubberduck.SmartIndenter/LogicalCodeLine.cs
- RubberduckTests/SmartIndenter/MultiSegmentLineTests.cs
Fix #5929 .
The 'then'-Statement triggered an Indent even tough the line got continued with ':'.
Edited Test for IfThenElseOnSameLine to contain valid VBA Code and check #5929
> Fix Indent if-then-colon #5929

- Rubberduck.SmartIndenter/AbsoluteCodeLine.cs
- Rubberduck.SmartIndenter/LogicalCodeLine.cs
- RubberduckTests/SmartIndenter/LineContinuationTests.cs
Fix for #4795.
'PtrSafe' was not recognized as a valid part of the declare statement and was therefore not ignored during line continuation alignment
Add Test for Declare PrtSafe.
> Fix Indenter "Declare PtrSafe"

- Rubberduck.Parsing/Symbols/Declaration.cs
Ref #5964
There are uncommon but theoretically valid cases when the `AsTypeDeclaration` of a declaration is set to null. In these cases, a missing null check when setting `IsSelfAssigned` caused an NRE. Adding the null check prevents this and, as a result, makes the `TypeAnnotationPass` in the reference resolver safer.
This PR will remove the failure of the resolution in #5964, but I am still curious how we ended up in this situation in the first place as the only two bindings that seem to be able to provide a `null` are the one for a failed resolution, which we safeguard against, and the one for a built-in type, for which I do not know how that can turn up in a complex type annotation that is not a straight array declaration, which we treat in a special way.
Because of this lack of how …
> Add null check when assigning null to AsTypeDeclaration

- Rubberduck.CodeAnalysis/Inspections/Concrete/UnassignedVariableUsageInspection.cs
- RubberduckTests/Inspections/UnassignedVariableUsageInspectionTests.cs
Closes #5990
The problem was that an array declares as a Variant and later assigned via ReDim is not flagged as an array and thus not properly excluded from the inspection.
The approach taken here is to explicitly look for ReDim before the usage inside the same function as the reference. This approach has been taken in favor of enhancing the resolver because whether a Variant declaration is an array depends on the exact location in the code. One can define a Variant then redim it as an array and later assign a non-array value to it. This makes it comparatively complicated to figure out whether a Variant is an array in every spot. Anyway, we store the information whether a variable is an array on the declaration and this does not allow changing values over the code.
Note that that this fix …
> Make UnassignedVariableUsageInspection aware of redimmed variant arrays

- Rubberduck.CodeAnalysis/Inspections/Concrete/ConstantNotUsedInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/ProcedureNotUsedInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/VariableNotAssignedInspection.cs
- Rubberduck.CodeAnalysis/Inspections/Concrete/VariableNotUsedInspection.cs
- RubberduckTests/Inspections/ConstantNotUsedInspectionTests.cs
- RubberduckTests/Inspections/ProcedureNotUsedInspectionTests.cs
- RubberduckTests/Inspections/VariableNotAssignedInspectionTests.cs
- RubberduckTests/Inspections/VariableNotUsedInspectionTests.cs
Closes #5291
Closes #5908
The two issues are not closed in the sense of the original request. Instead, this PR aligns the handling in accordance with the result of the discussion in #5908.
There are two main changes in which not used/assigned items are reported by the various inspections.
1. Unused interface members are now generally reported. The rational is that these members can be removed from the interface (and the implementations) if nobody uses them.
2. Public members in exposed class modules are never reported as unused or unassigned. The rational is that exposed classes are intended for external use. Accordingly, the uses or assignments are probably intended to be done by another project, which might bot be loaded at the moment. In addition, one has to consciously expose a module …
> Align handling of interfaces in not used inspections

- Rubberduck.Core/UI/Converters/SearchResultToXamlConverter.cs
Closes #5952
The results of Find All References take the input code from the reference's line in the VBE and the highlight selection based on the reference selection. If this happens in a dirty state, the highlight can be outside the input code on the line that is now on the line the reference was on before. Previously, this caused an `ArgumentOutOfBoundExcetion` in the UI code when applying the highlight, which brought down the host. Now, we check whether the highlight is within the input code and only apply it if this check passes.
The navigation properly navigates to the last known selection of the reference.
I guess displaying the code at and navigating to the last known position is still useful. So, outright deactivating the feature in a dirty state might not be the best option.
> Handle inconsistent results from Find All references gracefully

- Rubberduck.Main/ComClientLibrary/UnitTesting/AssertClass.cs
- RubberduckTests/UnitTesting/AssertTests.cs
Fixes #5827 by returning from the equality test as soon as the first difference is found rather than checking for other differences which could error (due to different ranks) or pass because the last attribute checked is equal.
> Sequence equals tests#5827

- Rubberduck.Refactorings/Common/CodeBuilder.cs
- Rubberduck.Refactorings/Common/DeclarationExtensions.cs
- Rubberduck.Resources/Refactorings/Refactorings.Designer.cs
- Rubberduck.Resources/Refactorings/Refactorings.resx
- RubberduckTests/CodeBuilderTests.cs
Modifications:
1. Fixes a latent Let/Set code block creation bug:  creating a code block from parameterized Get prototypes fail.
2. Adds `DeclarationType.PropertyLet` and `DeclarationType.PropertySet` to the list of valid prototypes for generating code. 
Item 1: Discovered while working with `CodeBuilder` to resolve #5886.  
Item 2: The resolution to #5886 _should_ look a lot like `IntroduceGetAccessorQuickFix`.  However, `IntroduceGetAccessorQuickFix` is not using the `CodeBuilder`.  The `CodeBuilder` was not an option since creating a Get property code block using a Let/Set prototype declaration was not supported.
> CodeBuilder improvements:  Get <=> Let/Set code block creation

- Rubberduck.Parsing/ParserRuleContextExtensions.cs
- RubberduckTests/Grammar/ParserRuleContextExtensionNullArgumentsTests.cs
This PR modifies public `ParserRuleContextExtensions` class functions that were generating NREs as a result of null arguments.
> Fix ParserRuleContextExtensions class NREs due to null arguments

- Rubberduck.CodeAnalysis/Inspections/Concrete/MultipleDeclarationsInspection.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/ConvertToProcedureQuickFix.cs
While reviewing the links between inspections and quickfixes, I stumbled upon a quickfix that was linking to an inspection that was probably renamed, or no longer exists anyway - resulting in a link on the site going to a HTTP 404 error page.
I'll push more commits in this branch if I see others.
> Some xmldoc fixes

- RubberduckTests/Grammar/ParserRuleContextExtensionTests.cs
- RubberduckTests/Grammar/ParserRuleContextExtensionsNullArgumentsTests.cs
- RubberduckTests/Grammar/ParserRuleContextExtensionsTests.cs
This PR addresses some technical debt.  
While working on #6039, noticed that the existing `ParserRuleContextExtensions` tests were implemented using an `NUnit` style/capability inconsistent with the vast majority (if not _all_ ) of the RD unit tests.
Also, both `ParserRuleContextExtensions` test file names were modified/renamed as the class name prefix for both were missing the final 's'.
> Refactor ParserRuleContextExtensions Tests

- Rubberduck.Refactorings/Common/CodeBuilder.cs
- RubberduckTests/CodeBuilderTests.cs
This PR fixes a `CodeBuilder` latent bug regarding the creation of `Property Let/Set` code block(s) based on a `Property Let/Set` prototype.
MCVE:
```
'Use as a prototype for CodeBuilder to generate a Property Set member
Public Property Let Test(ByVal RHS Variant)
End Property
```
yields a `Property Set` with a duplicated Value parameter:
```
Public Property Set Test(ByVal RHS Variant, ByVal RHS Variant)
Err.Raise 5					'TODO: Implement member
End Property
```
> Fix CodeBuilder create Let/Set code block issue

- Rubberduck.Main/ComClientLibrary/UnitTesting/FakeBase.cs
- Rubberduck.Main/ComClientLibrary/UnitTesting/Fakes/Date.cs
- Rubberduck.Main/ComClientLibrary/UnitTesting/Fakes/Time.cs
- Rubberduck.Main/ComClientLibrary/UnitTesting/FakesProvider.cs
- Rubberduck.Main/ComClientLibrary/UnitTesting/StubBase.cs
- RubberduckTests/IntegrationTests/FakeTests.bas
Fixes https://github.com/rubberduck-vba/Rubberduck/issues/4476, fixes https://github.com/rubberduck-vba/Rubberduck/issues/5944
The fix for 4476 is simply to change the list of return values from being static as that meant it was shared across multiple fakes and so a return value intended for one fake could be used by another, causing type conversion errors (as well as unintended values).
The fix for 5944 introduces a way to disable another fake temporarily. This is necessary when one hooked function uses the passthrough feature to call the native function which itself contains a call to another hooked function. We don't want that behaviour anyway as someone hooking the Now function for example would not expect it to change the result of the Date function. I've done this for the Date and …
> Fakes fixes

- Rubberduck.UnitTesting/CodeGeneration/TestCodeGeneratorStatics.cs
(otherwise remove the indention after `On Error GoTo {TestFailLabel}` lines)
> chore: harmonize indention of empty lines in `TestCodeGenerator`

- RubberduckBaseProject.csproj
I noticed a simple typo in the base project SDK version.  Quick correction
> Correcting a typo in Project.Sdk

- Rubberduck.CodeAnalysis/QuickFixes/Concrete/AccessSheetUsingCodeNameQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/AddMissingAttributeQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/AddStepOneQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/AdjustAttributeValuesQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/AnnotateEntryPointQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/AssignedByValParameterMakeLocalCopyQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/ChangeIntegerToLongQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/ChangeProcedureToFunctionQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/ConvertToProcedureQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/DeclareAsExplicitTypeQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/ExpandBangNotationQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/ExpandDefaultMemberQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/IgnoreInModuleQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/IgnoreOnceQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/PassParameterByValueQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/QualifyWithMeQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/Refactoring/MoveFieldCloserToUsageQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/Refactoring/RenameDeclarationQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/RemoveDuplicatedAnnotationQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/RemoveRedundantOptionStatementQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/ReplaceQualifierWithMeQuickFix.cs
- Rubberduck.CodeAnalysis/QuickFixes/Concrete/UntypedFunctionUsageQuickFix.cs
- Rubberduck.Resources/Inspections/InspectionResults.de.resx
- Rubberduck.Resources/Inspections/QuickFixes.Designer.cs
- Rubberduck.Resources/Inspections/QuickFixes.cs.resx
- Rubberduck.Resources/Inspections/QuickFixes.de.resx
- Rubberduck.Resources/Inspections/QuickFixes.es.resx
- Rubberduck.Resources/Inspections/QuickFixes.fr.resx
- Rubberduck.Resources/Inspections/QuickFixes.it.resx
- Rubberduck.Resources/Inspections/QuickFixes.resx
- (Maybe hopefully) fixed #6095
- Unified layout of QuickFix classes:
- Put override bools always at bottom
- Put description override always above them
- Changed to => for Description wherever possible
- Where not, unified indentation
- Added RenameDeclarationQuickFix string to QuickFix*.resx files
- Changed RenameDeclarationQuickFix.cs to use QuickFix*.resx
> Unified QuickFix classes' layout & added Rename-QuickFix localization
